### PR TITLE
Cardano: Conway certificates and tagged sets

### PR DESCRIPTION
**Pull request by jaskp**
Update with select Cardano Conway features:
- Transactions with new *stake registration* and *deregistration* certificates and a *DRep vote delegation* certificate (does not include any new key derivations nor voting procedures)
- Flag that globally sets the CBOR encoding of "sets" to include the 258 tag. Without it, "sets" are just plain CBOR arrays.
- Increase of URL length limit from 64 to 128 bytes

Resources:
https://github.com/IntersectMBO/cardano-ledger/blob/master/eras/conway/impl/cddl-files/conway.cddl
https://github.com/cardano-foundation/CIPs/tree/master/CIP-0005
https://github.com/cardano-foundation/CIPs/tree/master/CIP-1694
https://sancho.network/tools-resources/faq/#4-certificate-and-transaction-field-witnesses-and-deposits

### CODE REVIEW

**Review by matejcik — COMMENTED** [review]
code content ACK. please do the following to get up-to-date:
1. rebase on current main
2. regenerate UI fixtures for TT and TR
3. force-push the code
4. add `translations` label to the PR
5. when the CI is done, run `./tests/update_fixtures.py ci` and `./tests/update_fixtures.py ci --github`
6. commit the changes in a fixup
7. check that the CI now passes

one or more steps may fail because you are an external contributor, i'll try to follow up

**Comment by davidmisiak** [comment]
Hi, I rebased and added the translations. Unfortunately, I cannot add the label, and CI has not started it seems.

https://github.com/trezor/trezor-firmware/pull/3509 is in a similar state.

**Comment by matejcik** [comment]
you should now be able to run `update_fixtures.py ci --github`

i'll repush the branch so that gitlab runs it

**Comment by davidmisiak** [comment]
Pushed changes from `update_fixtures.py ci --github`.

**Comment by matejcik** [comment]
try also `update_fixtures.py ci` without `--github`, i think the gitlab pipeline is done too

**Comment by davidmisiak** [comment]
I'm getting this (with no changes in `fixtures.json`):
```
❯ ./tests/update_fixtures.py ci
Updating from CI...
Branch: feat/cardano/conway/stake-certs
Checking branch feat/cardano/conway/stake-certs
Checking job core click R test
Checking job core click test
Checking job core device R test
Checking job core device test
Checking job core persistence test
No results yet.
Checking job legacy device test
Updating results from core click R test...
Updated 0 tests.
Updating results from core click test...
Updated 0 tests.
Updating results from core device R test...
Updated 0 tests.
Updating results from core device test...
Updated 0 tests.
Updating results from core persistence test...
Updated 0 tests.
Updating results from legacy device test...
Updated 0 tests.
--------------------------------------------------------------------------------
Updated 0 tests in total.
Updated fixtures.json with data from CI.
```

By the way, what's the difference between the github and gitlab pipeline?

**Comment by matejcik** [comment]
> By the way, what's the difference between the github and gitlab pipeline?

practically speaking, gitlab also runs T2B1 click tests which are broken in github.
(well they're broken mostly everywhere but they work on gitlab so we keep it around)
with that said I believe that you're not touching click tests so we don't expect failures there.

**Review by matejcik — APPROVED** [review]

**Comment by matejcik** [comment]
please squash the fixup so I can merge

**Comment by davidmisiak** [comment]
Squashed

**Pull request merged**
