### PR TITLE
Add trezor support for Verge

### PR DESCRIPTION
**Pull request by marpme**
superseeds the previously made PR #816

### CODE REVIEW

**Comment by matejcik** [comment]
file `coins.json` does not exist anymore. please remove it.
`coins_details.json` is autogenerated by us, please remove it

**Comment by prusnak** [comment]
Merged, thanks!

**Comment by Ruxiol** [comment]
I just did update Trezor ONE to 1.9.3 but i still dont see Verge on coin list, can yo please explain why, thanks!

**Comment by tsusanka** [comment]
@Ruxiol you mean on wallet.trezor.io? We do not support the coin there, only in firmware. You need to use some Verge wallet such as its [Electrum fork](https://github.com/vergecurrency/electrum/releases)

**Comment by bosomt** [comment]
@tsusanka @prusnak is there way to test it on our side ? 
Via **Verge Electrum**  or via `trezorctl` ?

**Comment by tsusanka** [comment]
@bosomt No need.

**Pull request merged**
