### PR TITLE
automatic generation of CMakeLists

### PR DESCRIPTION
**Pull request by TychoVrahe**
Generates `CMakeLists.txt` automatically during compilation, respecting what is currently being build (eg. firmware/ bootloader/emulator) and other settings like model, bitcoin only etc. This enables IDE to correctly parse the C source code

@hiviah since you probably use this the most, let me know if this is useful to you and doesn't break your workflow somehow.

### CODE REVIEW

**Comment by hiviah** [comment]
This is pretty cool.

Though could you add some parameter so that it won't always overwrite the `CMakeLists.txt` on each build, only when parameter is put on command line? Sometimes I change some of the definitions in `CMakeLists.txt` (usually when checking differences in code paths for `PRODUCTION=1`) or alternate between bootloader and firmware build?

**Comment by TychoVrahe** [comment]
sounds reasonable: making this optional https://github.com/trezor/trezor-firmware/pull/2776/commits/3e5d1573bfbc4797d32e4dd01e175eee1ec94b9d

**Comment by hiviah** [comment]
I think there is type confusion because Makefile sets `CMAKELISTS` to string `"0"` and not the integer `0` when retrieved via `ARGUMENTS.get('CMAKELISTS', 0)`.

Probably the simplest fix is to convert the value to int in SConscript which appears to make it work as intended (see patch - I zipped it because github wouldn't allow it as patch even though it's valid according its own rules)
[create_cmakelists.patch.zip](https://github.com/trezor/trezor-firmware/files/10546504/create_cmakelists.patch.zip)

**Comment by TychoVrahe** [comment]
thanks, committed the patch: https://github.com/trezor/trezor-firmware/commit/cbe2fceb61352be540a89dc104cc4b9fa2049e94

**Review by hiviah — APPROVED** [review]

**Pull request merged**
