### PR TITLE
Binance: Fix the "coin" blueprint

### PR DESCRIPTION
**Pull request by notatestuser**
Removed the quotes around the amount int to produce valid json sign bytes for a transfer.

The sign bytes for this type of transaction should look like the following snippet:
```json
{"account_number":"259344","chain_id":"Binance-Chain-Tigris","data":null,"memo":"TREZOR Test!","msgs":[{"inputs":[{"address":"bnb1g2j62k0q0w02ha98kwyznahv2l5d8ez7tgge3u","coins":[{"amount":1,"denom":"BNB"}]}],"outputs":[{"address":"bnb1g2j62k0q0w02ha98kwyznahv2l5d8ez7tgge3u","coins":[{"amount":1,"denom":"BNB"}]}]}],"sequence":"6","source":"0"}
```

All of the three transaction types have now been tested on a real device.

Please let me know if there are any test cases that should be updated. I have found [this one](https://github.com/trezor/trezor-firmware/blob/7b4b2eddf732d6d107301f104ec43a3f5f1b711f/tests/device_tests/test_msg_binance_sign_tx.py#L65) but it does not appear to match what the firmware currently produces.

### CODE REVIEW

**Comment by ciny** [comment]
> I have found this one but it does not appear to match what the firmware currently produces.

The JSON text vectors are converted into protobuf messages in binance.sign_tx and sent over to the device. That test now fails so the expected_signature value will need to be updated. What confuses me is that that signature and values are from test fixtures in your javascript-sdk [here](https://github.com/binance-chain/javascript-sdk/blob/master/__tests__/fixtures/transfer.json#L156), seems the fixtures were generated with some buggy code :)

**Comment by notatestuser** [comment]
Well spotted. The amounts used to be serialized to strings on the Testnet, but that was later changed. There is a good chance that it the fixture is outdated. Thank you for flagging it up.

**Comment by notatestuser** [comment]
Hey @ciny, I have updated the sign bytes and the expected signature.

**Comment by prusnak** [comment]
I've merged the commit to master, but this won't be included in the tomorrow's release, because we are way after the freeze has happened. It will be released in the next release which will happen on 2.10.2019

**Comment by prusnak** [comment]
This is now released on beta as firmware 2.1.6 as promised

**Pull request merged**
