### PR TITLE
Add PIVX support

### PR DESCRIPTION
**Pull request by panleone**
The scope of this PR is adding again PIVX support to the firmware.
We have been delisted years ago because there were no wallets supporting Trezor (https://github.com/trezor/trezor-firmware/pull/1359).
PIVX has a new wallet called my PIVX wallet (https://mypivxwallet.org/), I have personally contributed to add hardware support for Ledger (https://github.com/PIVX-Labs/MyPIVXWallet/pull/31) and I am willing to add also support for Trezor  :)

### CODE REVIEW

**Comment by Hannsek** [comment]
Hello @panleone,

Thank you for submitting the pull request. However, we have some inquiries regarding the integration of PIVX with Trezor.

Presently, there is no existing wallet that offers support for PIVX on the Trezor platform. Although you mentioned your intention to address this, we have not observed significant demand or interest from the community for PIVX integration with Trezor.

Considering these factors, we have decided not to proceed with merging this pull request at the moment.

**Comment by Fuzzbawls** [comment]
this is an unfortunate misstep. requiring demand **before** adoption is crude and unnecessary

**Comment by iseyodea** [comment]
I would really like to see pivx on trezor.

**Comment by Fuzzbawls** [comment]
SPMT and PET4L both have trezor integration. while these are not full feature wallets, they still act as methods for users to manage their funds.

**Pull request closed without merging**
