### PR TITLE
Code improvement on printf

### PR DESCRIPTION
**Pull request by mgiannopoulos24**
File: `core/embed/bootloader/emulator.c`

Will it change much if you swap:

- Line 65: printf("File '%s' does not contain a valid firmware image.\n");
- Line 72: printf("File '%s' does not contain a valid vendor header.\n");
- Line 78: printf("File '%s' does not contain a valid firmware image.\n");

To: 

- Line 65: printf("File '%s' does not contain a valid firmware image.\n", filename);  
- Line 72: printf("File '%s' does not contain a valid vendor header.\n", filename);
- Line 78: printf("File '%s' does not contain a valid firmware image.\n", filename);

### CODE REVIEW

**Comment by prusnak** [comment]
Remove the comments please

**Comment by mgiannopoulos24** [comment]
I did it.

**Comment by matejcik** [comment]
you somehow re-added the comments, please remove them again :woman_shrugging:

**Comment by mgiannopoulos24** [comment]
Okay, I think now its fixed.

**Pull request merged**
