### PR TITLE
fix(legacy): show dialog before rebooting to bootloader

### PR DESCRIPTION
**Pull request by prusnak**

### CODE REVIEW

**Review by tsusanka — APPROVED** [review]
LGTM. Maybe @hiviah could review as well?

**Comment by tsusanka** [comment]
I am also pinging @matejzak for the copy.

**Comment by tsusanka** [comment]
Anthonny and Matej came up with

> Restart device in bootloader mode?

to avoid the double "boot" in "reboot bootloader". What do you think? We can discuss on Slack further..

**Review by hiviah — APPROVED** [review]

**Comment by prusnak** [comment]
Changed the wording in 3b770c5ff1ba4a7a50edfa3362a7ed0509916530

**Review by tsusanka — APPROVED** [review]

**Pull request merged**
