### PR TITLE
Increase 'SignIdentity.challenge_hidden' max_size to 512 bytes

### PR DESCRIPTION
**Pull request by romanz**
Following https://github.com/romanz/trezor-agent/issues/408.

### CODE REVIEW

**Review by prusnak — APPROVED** [review]
LGTM

**Comment by iskradelta** [comment]
Verified with a custom build it works on a Trezor One

**Comment by matejcik** [comment]
please add a [changelog entry](https://docs.trezor.io/trezor-firmware/misc/changelog.html#adding-changelog-entry)

**Comment by romanz** [comment]
Added in 826a4e41f4e0064908af522902397811462937cb (also modified the commit message).

**Comment by prusnak** [comment]
> How long does it usually take to get a signed official image, like a v1.11.3?

There will be a release in March.

**Comment by romanz** [comment]
Many thanks!

**Pull request merged**
