### PR TITLE
fix(common): remove Firo

### PR DESCRIPTION
**Pull request by prusnak**
using Firo leads to unspendable coins, let's remove this coin until we can spend the coins again

context:
- https://github.com/trezor/trezor-firmware/issues/1588
- https://github.com/firoorg/electrum-firo/issues/3

(kind of) fixes https://github.com/trezor/trezor-firmware/issues/1588

### CODE REVIEW

**Comment by matejcik** [comment]
I'd suggest delisting Firo from tio/coins, but keeping firmware support until the next release, so that people who are helped by #1565 can send their coins out?

**Comment by yura-pakhuchiy** [comment]
Please consider https://github.com/trezor/trezor-firmware/issues/1588#issuecomment-833520062 before making decision

**Comment by matejcik** [comment]
superseded by #1647

**Comment by a-bezrukov** [comment]
Hi Guys,
We are reworking these large transactions and moving the long data into the extra payload area. It's hard to provide any ETA on this, but this work is starting right now.
Thanks.

**Pull request closed without merging**
