### PR TITLE
peercoin support

### PR DESCRIPTION
**Pull request by backpacker69**
This PR enables peercoin support including signing peercoin messages for both main and testnet networks on trezor one and t. 

We have also prepared and launched blockbook instances for peercoin network on https://blockbook.peercoin.net/ and https://tblockbook.peercoin.net/ for trezor wallet to connect to.

Testing of signing messages and transactions on physical Trezor T was performed on peercoin network with successful result.

### CODE REVIEW

**Comment by prusnak** [comment]
When will you release Peercoin wallet with Trezor support?

**Comment by backpacker69** [comment]
> When will you release Peercoin wallet with Trezor support?

magnum wallet already supports us afaik

**Comment by peerchemist** [comment]
Magnumwallet.co supports Trezor and Peercoin.

**Comment by prusnak** [comment]
Superseded by https://github.com/trezor/trezor-firmware/pull/740 where I made some structural changes.

**Comment by bosomt** [comment]
Peercoin vs Trezor is not supported.
Please see 

image

If i select Trezor and then peercoin then Trezor says Another U2F device was used and wallet says please confirm on your Ledger.

Af course it ends in error

**Comment by prusnak** [comment]
@backpacker69 @peerchemist please talk to Magnum Wallet so they enable Trezor support for Peercoin

**Comment by backpacker69** [comment]
we've contacted them, do you have any idea when next firmware release containing ppc support will be available?

**Comment by prusnak** [comment]
1st of January 2020

**Pull request closed without merging**
