### PR TITLE
core/ui: reset_device copy change

### LINKED ISSUE #2709: UI2: tos - copy change
Change copy for these kind of screens: 
image

**Delete the initial question.**
**Change heading**
**Change buttons**
image

https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=6015%3A45701&t=gdClSu39z7PYeyy2-4

### PR DESCRIPTION
**Pull request by mmilata**
Fixes #2709.
UI diff: https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/3602753054/artifacts/master_diff/index.html

recover create 
creates createss

### CODE REVIEW

**Comment by grdddj** [comment]
The implementation is all good, I have just one topic to discuss - the usage of `FormattedText`.

In `TR` branch I am counting on deleting `FormattedText` completely, as before this `PR`, it was not used anymore - and keeping it alive (it is quite a lot of code) just for one usage might not be very economical.

Could we do it some other way here? For example, putting the bold paragraph at the bottom, just with "trezor.io/tos"? (Theoretically with longer wording - e.g. "Read more info at" to justify putting it to the next line.)

To be more detailed about the `TR` changes, I am using sort-of `FormattedText` functionality, but in a way of manually creating a list of `Op`s - so instead of having a string `"More info at {demibold}trezor.io/tos"`, I would use it as `Page.text_normal("More info at ").text_demibold("trezor.io/tos")`.

There could be more usages of this even in `TT` in the future, so we might want to create something usable for both models.

**Comment by prusnak** [comment]
Hm, nit-pick, but doesn't this look better?

```
By continuing you agree\nto Trezor Company's\nterms and conditions.
```

**Comment by Hannsek** [comment]
image

**Review by matejcik — APPROVED** [review]
LGTM but please fix the conflicts

**Comment by mmilata** [comment]
Rebased a changed text as requested, [UI diff](https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/3786004005/artifacts/master_diff/index.html).

**Review by matejcik — APPROVED** [review]

**Comment by bosomt** [comment]
**QA OK**

    revision: 20 bytes 0x0a955b4ad6d9fb5e7a1dbd3333548ffd8b33399a,

tested on all 3 options to create wallet

**Pull request merged**
