### PR TITLE
Add Syscoin support

### PR DESCRIPTION
**Pull request by sidhujag**
Create [Syscoin](https://syscoin.org) definition.

Slip-0044: https://github.com/satoshilabs/slips/blob/master/slip-0044.md
Slip-132: https://github.com/satoshilabs/slips/blob/master/slip-0132.md

SYS BIP32 path is m/84' or 44' or 49'/57'/0/0

We use BIP84 in our apps/wallets and segwit by default.

### CODE REVIEW

**Comment by matejcik** [comment]
please run `make gen`

**Comment by prusnak** [comment]
@sidhujah Which Syscoin wallet has committed to integrate Trezor so the coin support is actually usable?

**Comment by sidhujag** [comment]
@matejcik thanks done

**Comment by sidhujag** [comment]
@matejcik will you merge in the conflicts with coins.json? If I have to do it, what tool do I use its one big line and the github merge conflict tool doesn't show the diff of the changes. If you can merge it that would be great!

**Comment by prusnak** [comment]
Merged in de4c7bb855226d02d73bf0ab4160c721f9c074de

**Pull request closed without merging**
