### PR TITLE
ci/hardware: enable SD card tests and btc tests on regular build

### PR DESCRIPTION
**Pull request by mmilata**
Increase timeout since 4h isn't always enough.

### CODE REVIEW

**Comment by matejcik** [comment]
The reason SD card tests are disabled is that they are _eating_ SD cards. There is no wear leveling and so every test run is hammering the same sectors. I'm not sure if we want to be reopening this particular can of worms again?

**Comment by matejcik** [comment]
also honestly not sure we want to run btc tests on regular build? we might but it's saving significant time that we don't do that?

**Comment by mmilata** [comment]
Admins bought some kind of "endurance" SD card (+couple spares) that are meant for constantly recording cameras, we can see how long they last.

Agreed that btc tests on regular build probably improve coverage negligibly compared to the increase in test duration (72m -> 216m). I thought we can afford it for the nightly runs but it might be too much in case we want to do multiple runs in a single day.

**Comment by tsusanka** [comment]
- ACK for sd card tests, I would add them even if we would need to replace the card once in a while. Let's try it..
- Regarding bitcoin tests on regular build: I do not have a strong preference here. If we add it, do we still complete a complete pipeline for master over one night? I mean it would be nice to have a result in the morning.

**Comment by mmilata** [comment]
Currently the nightly pipeline takes almost 6h, if we add the btc tests it will take a bit over 8h. I'd say it's still feasible to run overnight, although we should set the start to earlier than 1 am so that it's finished when people start working in the morning.

**Comment by tsusanka** [comment]
We can set it to let's say 11 pm. So let's force push and merge this?

**Review by tsusanka — APPROVED** [review]

**Pull request merged**
