### PR TITLE
add Sinovate (SIN) coin data to definitions

### PR DESCRIPTION
**Pull request by MIPPL**
Hello,

I did some changes to add Sinovate (SIN).

Blockbook
https://blockbook.sinovate.io

More information:
https://sinovate.io
https://github.com/SINOVATEblockchain/SIN-core

Chainparams:
https://github.com/SINOVATEblockchain/SIN-core/blob/master/src/chainparams.cpp

### CODE REVIEW

**Comment by prusnak** [comment]
Which SIN wallet will integrate Trezor?

**Comment by MIPPL** [comment]
We can activate bip44 HD wallet in the Core client. 

Is that enough, or we also need to communicate with the trezor device?

If this is the case, can we fork a version of trezor-beta wallet, add the SIN support, and publish it under a https://trezor.sinovate.io website? 

thank you

**Comment by prusnak** [comment]
You need your own wallet to communicate with Trezor

**Comment by MIPPL** [comment]
Ok we will prepare one based on trezor-beta, add the url to the webwallet property, and ping you back when ready.

**Comment by prusnak** [comment]
Reopen when you have wallet ready to test.

**Pull request closed without merging**
