### PR TITLE
fix(core/ui): fix a few translation strings

### PR DESCRIPTION
**Pull request by obrusvit**
PR contains:
- a fix XPUB success screen title
- a small fix of button labels
- update of two IT/PT strings

### CODE REVIEW

**Review by mmilata — APPROVED** [review]

**Comment by Hannsek** [comment]
Next time please fill in the details. 🙏🏻
image

**Comment by Hannsek** [comment]
@obrusvit can we merge this pls? 🙏🏻

**Comment by obrusvit** [comment]
@mmilata I updated the PR with more strings updates. Could you please review again?
@Hannsek I'll wait for CI and re-approve, then we can merge.

**Review by mmilata — APPROVED** [review]
LGTM

**Comment by bosomt** [comment]
**QA OK**

xpub strings ok

**Info:**
 - Suite version: web 24.11.0 (ff5fe34e9ecaee40808f50c235c08cf8e588b0c8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 5120x1440
 - Device: Trezor T3T1 2.8.4 regular (revision 31d228a325b5968a2f3565b803818aaf7fa29bbb)
 - Transport: WebUsbTransport

**Pull request merged**
