### PR TITLE
Enable support for Unrecognized action types in Trezor EOS Module

### PR DESCRIPTION
**Pull request by jafri**
This PR adds support for system eosio actions that are unsignable currently using Trezor. Users are currently not able to perform many actions across multiple EOSIO chains (EOS, WAX, Telos, BOS, Lynx, Worbli, Remme, etc).

Tested on Trezor emulator with trezord-go.

Will close https://github.com/trezor/connect/issues/443

### CODE REVIEW

**Comment by prusnak** [comment]
This is not acceptable. If Trezor cannot show the contents of the transaction, it should not be able to sign it.

**Comment by jafri** [comment]
@prusnak Trezor already does not show the contents of the transaction for 90% of the actions on EOS (any action that is not a system contract).

**Comment by prusnak** [comment]
OK, we should remove the other actions which do not show the info on the display as well. Thank you for the bug report. @matejcik can you please confirm that is the case?

**Comment by matejcik** [comment]
The situation is the same as with Ethereum. We have explicit support for many actions on the system `eosio` contract, and for token transfers. Apart from that, we allow signing "unknown" actions on non-system smart contracts. There we display contract name, action name, and a checksum of the payload.

This is a step better than Ethereum, where we allow signing arbitrary "data" payloads - EOS at least tells us the contract name and the action name.
(perhaps EOS should also show the full data to be signed, instead of checksum)

I'm not familiar enough with EOS to talk about the "90 %" figure, but (a) it's likely that 90 % of existing actions on existing smart contracts don't have explicit support (because anyone can create a contract and add actions to it), and (b) it's extremely unlikely that activating these actions would come anywhere near 90 % of activity (which is hopefully mostly transfers and/or the system actions).

To me personally this seems like a reasonable tradeoff:
* actions on the system contract must be understood, decoded and displayed,
* while we allow performing arbitrary actions on non-system contracts, albeit with lowered security

Accepting unknown actions on the system contract seems dangerous, so I'd definitely reject this PR. Accepting unknown actions on non-system contracts is questionable, I can see an argument for allowing it, but we might as well decide to tighten security by disallowing them.

**Comment by matejcik** [comment]
see https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/418497706/artifacts/tests/ui_tests/reports/passed/test_msg_eos_signtx.py-test_eos_signtx_unknown.html

**Pull request closed without merging**
