### PR TITLE
include signed bootloader 2.1.0

### LINKED ISSUE #1901: release new production signed bootloader to get touchpad updates
I'd like to request that a new signed production bootloader be released in order to get the fix for #1519 into production devices.

It looks like the latest bootloader released with production signatures is 2.0.3 from early 2019 (according to `trezor-firmware/core/embed/bootloader/CHANGELOG.md` and `trezor-firmware/core/CHANGELOG.md`).

That bootloader binary is stored at `trezor-firmware/core/embed/firmware/bootloader.bin` as identified by `trezor-firmware/core/embed/firmware/bootloader_hashes.py` and `trezor-firmware/core/embed/firmware/bl_check.c`, and also by `trezor-firmware/core/tools/headertool.py trezor-firmware/core/embed/firmware/bootloader.bin`.

To note, `trezor-firmware/core/embed/bootloader/version.h` has already been updated to 2.0.4.

A new bootloader will need to be built and signed and then some files, including at least the following, will need to be updated:
- `trezor-firmware/core/embed/firmware/bootloader.bin`
- `trezor-firmware/core/embed/firmware/bl_check.c`
- `trezor-firmware/core/CHANGELOG.md`
- `trezor-firmware/core/embed/bootloader/CHANGELOG.md`

I have an affected device, and I was able to workaround the old bootloader and load a new firmware that contains this fix by opening the case and dropping on a temporary screen + ctpm. After I got the new firmware on the device, then I put the original affected display + ctpm back on and was able to use touch for all the firmware functions, but none of the bootloader functions.

With this new requested bootloader, I could have just grabbed it from the distributed production firmware binary and written it to a microSD, and then loaded the new bootloader onto the device via the microSD + boardloader. That's the way that any other affected users could more easily benefit from the work requested by this issue. Thanks!

### PR DESCRIPTION
**Pull request by matejcik**
fixes #1901 

to test it for yourself:

1. go to `SConscript.firmware` line 781 `elif PRODUCTION:` and change the vendorheader to "unsafe_signed_prod"
2. build with `PRODUCTION=1 make build_firmware`
3. run `./tools/headertool.py -D build/firmware/firmware.bin`
4. make upload

### CODE REVIEW

**Comment by mmilata** [comment]
Verified that the binary fingerprint is `1b4845b2d2869eece07c3b287ad0acf036f7ba61efc39acb2cc01ed45490d2c6`, same as build-docker.sh produces for `core/bl2.1.1`.

Tried to test it myself but `make upload` failed:
```
$ make upload
trezorctl firmware_update -f build/firmware/firmware.bin
Trezor T firmware image.
Vendor header from UNSAFE, DO NOT USE!, version 0.0
Firmware version 2.6.0 build 0
Firmware fingerprint: ad8df753e0fa2ca906a98ce90dab63fef2b8237218bda057ebb38b9d9913d11c
Invalid vendor header signature.
Firmware validation failed, aborting.
$ trezorctl firmware_update -f build/firmware/firmware.bin -s
Uploading  [------------------------------------]    0%
Update failed: ProcessError: Invalid vendor header
```

**Comment by TychoVrahe** [comment]
you need to use -s to disable signature check in cli: `trezorctl firmware_update -f build/firmware/firmware.bin -s`

**Comment by mmilata** [comment]
Still
```
$ trezorctl firmware_update -f build/firmware/firmware.bin -s
Uploading  [------------------------------------]    0%
Update failed: ProcessError: Invalid vendor header
```

**Comment by matejcik** [comment]
it's actually supposed to be I've
unsafe signed prod, not dev, sorry

**Review by mmilata — APPROVED** [review]
LGTM & installed bootloader successfully

**Review by prusnak — APPROVED** [review]
Tried this on my test device.

Both UI in the bootloader and in the firmware look great! 🖤

**Comment by mcudev** [comment]
THANK YOU! I tested that this works to fix #1901.

For reference, here's the process that I used to load this new bootloader onto a device with the touchpad problem:

1. Get production signed 2.1.0 bootloader:
```
wget https://github.com/trezor/trezor-firmware/raw/master/core/embed/firmware/bootloaders/bootloader_T2T1.bin
```

1. Verify that bootloader is the same one as is distributed in the production firmware:
```
wget https://suite.trezor.io/web/static/connect/data/firmware/2/releases.json

wget https://suite.trezor.io/web/static/connect/data/firmware/2/trezor-2.6.0.bin

dd if=trezor-2.6.0.bin of=extracted-bootloader_T2T1.bin bs=1 skip=636716 count=111104

sha256sum *.bin
fe1def034896ac55d796382a7063124254f66d1ffcaf80309c91feb2c15f53c0  bootloader_T2T1.bin
fe1def034896ac55d796382a7063124254f66d1ffcaf80309c91feb2c15f53c0  extracted-bootloader_T2T1.bin
```

1. Write new bootloader to a microSD card using the instructions at https://github.com/trezor/trezor-firmware/blob/master/docs/core/misc/boot.md#first-stage---boardloader
`sudo dd if=/dev/zero of=/dev/mmcblk0 bs=512 count=256 conv=fsync`
`sudo dd if=bootloader_T2T1.bin of=/dev/mmcblk0 bs=512 conv=fsync`

1. Insert the microSD into affected Trezor T

1. Plug the Trezor T into host and let the boardloader load the new bootloader from the microSD card

**Pull request merged**
