### PR TITLE
fix(xmr): fixes #2453, incorrect address display

### LINKED ISSUE #2453: Monero primary address discrepancy between app and device
**Describe the bug**
I'm not sure if its expected or not or if it's problem with moneroGUI or Trezor.
But i was not able to replicate it with 2.5.1 FW.
When i press show address on device i see completely different address.
But it belongs to same account /i just sent some Monero to that address and i still have same amount of xmr.

When you create secondary address it works as expected. Device and app address does match, looks like only Primary address is affected.

**Firmware version and revision**

**QA NOK** Device: model T 2.5.2 regular (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
**QA OK** Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: moneroGUI 0.18.1.0-release (Qt 5.12.8)
 - OS: macARM

**To Reproduce**
1. Go to moneroGUI/Receive
2. Click on `Shonw on device`
3. Check address on device display and confirm
5. Compare with address displayed in app

**Screenshots**
Screenshot 2022-08-17 at 11 04 29

image

image

### PR DESCRIPTION
**Pull request by ph4r05**
Fixes #2453

### CODE REVIEW

**Comment by ph4r05** [comment]
@matejcik

**Review by matejcik — APPROVED** [review]
utACK

**Review by matejcik — CHANGES_REQUESTED** [review]
@ph4r05 please add a [changelog entry](https://docs.trezor.io/trezor-firmware/misc/changelog.html#adding-changelog-entry)

**Comment by ph4r05** [comment]
like this, @matejcik ?

**Review by matejcik — APPROVED** [review]

**Pull request merged**
