### PR TITLE
Authentication check spinner

### PR DESCRIPTION
**Pull request by matejcik**
This PR adds updated copy and spinner graphic to the AuthenticateDevice flow.

In addition, because it was a prerequisite, it implements better propagation of "full name" (i.e., "Trezor Model T" for model `T`, "Trezor Model One" for `1` and so on)

### CODE REVIEW

**Comment by matejcik** [comment]
still working on this, there are some things i'm not sure about wrt the homescreen text

**Review by mmilata — APPROVED** [review]
utACK, perhaps also a good time to get rid of `My Trezor` default in `trezor/ui/layouts/tt/homescreen.py`?

**Comment by Hannsek** [comment]
They are OK. Do not forget to change the name. 👍🏻

**Comment by STew790** [comment]
**QA OK**
Authentication spinner is present when checking the authenticity of the device.

**Info:**
 - Suite version: desktop 23.10.1 (6c8d061f7305947b0270a2560e4cc65d1f7ded27)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.10.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.6.2 bitcoin-only (revision 6e5967af25de87bebd331d697e6ef940e64286ef)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
