### PR TITLE
Add CHIPO

### PR DESCRIPTION
**Pull request by CHIPO-Project**
Added our CHIPO code.
Please merge.
Thanks.

### CODE REVIEW

**Comment by CHIPO-Project** [comment]
Hello.

The files I added get an error in CI

>Files src/trezorlib/coins.json and /tmp/tmp.WuIYMPxAUx differ
It seems that there is a difference with this file and an error occurs.
Is the file I added wrong?

**Comment by prusnak** [comment]
Which CHIPO wallet will integrate Trezor?

**Comment by matejcik** [comment]
> Hello.
> 
> The files I added get an error in CI
> 
> > Files src/trezorlib/coins.json and /tmp/tmp.WuIYMPxAUx differ
> 
> It seems that there is a difference with this file and an error occurs.
> Is the file I added wrong?

you probably didn't load submodules. run `git submodule update --init --recursive` and try again

**Comment by CHIPO-Project** [comment]
> > Hello.
> > The files I added get an error in CI
> > > Files src/trezorlib/coins.json and /tmp/tmp.WuIYMPxAUx differ
> > 
> > 
> > It seems that there is a difference with this file and an error occurs.
> > Is the file I added wrong?
> 
> you probably didn't load submodules. run `git submodule update --init --recursive` and try again

CI was successful.
Thank you very much.

**Comment by prusnak** [comment]
Reopen when you have wallet ready to test.

**Pull request closed without merging**
