### PR TITLE
feat(cardano): Format stake pool ids as bech32 instead of hex

### PR DESCRIPTION
**Pull request by refi93**
Motivation: Cardano stake pool id user-facing format has been standardized in [CIP-0005](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0005/CIP-0005.md) to use bech32 and the prefix "pool". IOHK requested us to update Trezor UI accordingly. Until now, Trezor has been displaying stake pool ids in base16 encoding which was originally deemed to be a safe default before the related standards have settled.

Changes:
* introduce a `format_stake_pool_id()` helper function which encodes the pool id in bech32
* change "Pool id" to "Pool ID" in layout to match the capitalization used more widely in the community

Testing:
* `pytest tests/device_tests -k "test_cardano_sign_tx"` passes
* updated UI fixtures via `make test_emu_ui_record`

Google Drive link with the UI fixtures affected by these changes: https://drive.google.com/drive/folders/1HS5UvJBxB3COHZ_lwRvHppQfF-E67Y5k?usp=sharing

### CODE REVIEW

**Comment by matejcik** [comment]
please rebase on current master and fix any typing errors

otherwise basically LGTM

**Comment by refi93** [comment]
@matejcik done

**Comment by matejcik** [comment]
rebased fixtures as ceea21ec, waiting for CI to pass

**Comment by matejcik** [comment]
CI clear, merged as ceea21e

**Pull request closed without merging**
