### PR TITLE
build(core): skip rust library for now

### PR DESCRIPTION
**Pull request by mmilata**
Disable linking in of `trezor_lib.a` into the final image, for this release.

### CODE REVIEW

**Review by tsusanka — APPROVED** [review]
LGTM, but I did not watch Rust implementation that closely to be 100% sure it is all it needs.

**Comment by matejcik** [comment]
LGTM as well.

noting that **this should not be applied to master** but to the release branch, @tsusanka.

please edit the target branch when appropriate.

**Comment by tsusanka** [comment]
We have discussed with @mmilata that he'll try to do the release process (Monday's fine). Let's not forget to add `[RELEASE_ONLY]` to the commit message btw so the release commit check passes.

**Comment by prusnak** [comment]
@mmilata Do I understand it correctly, we won't be needing rust at all for this release? If yes, can we please also remove the `rustOverlay` and friends from the `shell.nix` in the release branch?

**Comment by mmilata** [comment]
Yes, we've decided the rust protobuf code is not polished enough for this release and without it the FFI in master is not used. Will remove it completely from the build process for the release.

**Comment by tsusanka** [comment]
@mmilata I guess we can close this since we have it (correctly) in the release branch?

**Pull request closed without merging**
