### PR TITLE
tests: new monero binary added

### PR DESCRIPTION
**Pull request by ph4r05**
- new Monero Trezor tests build, based on commit c0bc6d96cd67071e433b473bfb76a113529b1deb
- option to use already running emulator added, set env var RUN_TEST_EMU=0

### CODE REVIEW

**Comment by ph4r05** [comment]
As we have removed the python tests you can remove also `py-trezor-crypto-ph4` from the Pipfile to fix the test build (the mentioned python package requires libsodium installed)

**Comment by matejcik** [comment]
> As we have removed the python tests you can remove also `py-trezor-crypto-ph4` from the Pipfile to fix the test build (the mentioned python package requires libsodium installed)

YESSSSS 👍 💯 🥇 👍 💯 💯 💯

**Comment by prusnak** [comment]
@matejcik can you please merge this one and remove the mentioned package from the Pipfile?

**Comment by ph4r05** [comment]
@matejcik I've pushed a change removing deps from pipfiles to see how the test goes.

**Comment by ph4r05** [comment]
OK now Travis fails because of missing protoc
```
'ERROR: running develop',
 '    running prebuild',
 '    protoc command not found', 
"    error: Generating protobuf failed. Make sure you have 'protoc' in your PATH.
```

**Comment by matejcik** [comment]
yeah i'm about to fix that one, don't worry

**Comment by matejcik** [comment]
merged in f767f890cd7f88cb75a3c90ddfb3b9b1b2124c13, thanks

**Pull request closed without merging**
