### PR TITLE
T3T1 UI - passphrase flow improvement

### PR DESCRIPTION
**Pull request by obrusvit**
This PR adds reassuring screen when entering empty passphrase.

In order to do that, this includes some necessary changes:
- aa79f02ac4d967aa74521836831a02a6d38778ef adds `FlowMsg::Text` variant which enables passing `ShortString` to uPy as `str`. Btw. `ShortString` is conveniently limited to `50` chars which needs to be revisited if we implement https://github.com/trezor/trezor-firmware/issues/4084#issuecomment-2268850876 
- ebc297f3c73dc70de08e6471ca06cd082c14a68f implements new component - a simple yes/no prompt with buttons. It will be used further in some flows from Figma
- 55633a765fc1fad71dc5149cd5906930dc5002e4 switching two buttons in passphrase keyboard, one for empty passphrase, one for non-empty
- a06c83d30600b8c585d1a9be2f5a65df83b19d64 adds dedicated `PromptMsg` instead of passing empty `Option` around. This has the benefit that the `BinarySelection` from ebc297f3c73dc70de08e6471ca06cd082c14a68f can be used as `PromptScreen::new_yes_or_no()`
- 395bcb6ccf8079661f106adca66be35d2359d2b3 implements the passphrase flow

### CODE REVIEW

**Comment by Hannsek** [comment]
cc @lapohoda

**Comment by obrusvit** [comment]
@Hannsek UI changes briefly:

The confirmation of empty passphrase:
refresh00-00000001 refresh00-00000002
refresh00-00000003 refresh00-00000004

Usage of subtitle in other screens:
refresh00-00000006 refresh00-00000007

**Comment by lapohoda** [comment]
@obrusvit pls doublecheck the size of confirmation button – should be circular according to Figma

image

**Comment by obrusvit** [comment]
UI diff of FIDO2 actions are coincidental due to confirm button stylesheet change and will be superseded by https://github.com/trezor/trezor-firmware/pull/4069.

**Review by matejcik — APPROVED** [review]
utACK.

general note: it's not great that you're adding `Text(ShortString)` in there, and especially not great that you're adding it to the passphrase Confirmed() variant. What we originally intended with ComponentMsgObj (on the model_tt side) is that you return a "user is done" message, then the ComponentMsgObj impl asks the layout to give out a `&str`, and we convert _that_ to micropython.
Here, we'd want `.map()` to pass you both the original layout and the returned message -- so that you can do this part in the `map()` closure.

on the other hand, i'd prefer getting rid of `Map` component the way we use it now. and currently doing it like this fits well with overall way of doing things in mercury. We can refactor the things when refactoring time comes, i guess.

**Comment by obrusvit** [comment]
Merging amidst `T3T1` coverage failing. I'll take a look at different PR.

**Pull request merged**
