### PR TITLE
TT: button text and warning style update

### LINKED ISSUE #2938: Change text on the button
While setting locktime, on the confirmation button, there is currently `NEXT`. 

Please change it to `CONFIRM`.
IMG_8278

the same thing for confirm fee screen in eth send flow
IMG_8279

### PR DESCRIPTION
**Pull request by mmilata**
Fixes #2938. No more `NEXT` buttons. Some screens that had _Warning_ in the title were converted to use the warning layout with icon. Changed button style on the warning layout.

[UI diff](https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/4095806738/artifacts/test_ui_report/index.html) | [differing screens](https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/4095806738/artifacts/test_ui_report/differing_screens.html)

eb08e85a3829f5fe2f72300ef9b914ec1799fbb037a22b345f0a0806a8b24512 445dc7f62301c615f24269f79f7fe4b1836174290c6f1bad6adbd3f850026acc 98beecc9056ed2993feceb59f567517b7ad6fb83911d2a48f3fb14e6040c4a18 5a4f85311c57d5430fa8f187caab10a9b64ae9b2e178ce20db71c120f79a6d19 76cd72134891beb772cdbbb910fd2e808d6923cf36936df6e7ea4b7697bfa68f e2188ea4d4e4c7c6c4c66bbe7b07948214b9ae6bf8cc63b6a3de2e688716ff27

### CODE REVIEW

**Comment by mmilata** [comment]
Sure
9ce1a50f9c4834d16a82226b851d40a17c2973417199736f74d01ab176db5aa8 379d733c7e44c033e87bcfdc930e4e6444c5142dbda0d059081bbcc7da7ebd86

**Comment by Hannsek** [comment]
How come that you can fit the locktime in mono there and I in figma cannot. Magic.

**Comment by mmilata** [comment]
6px + 19 * 12px + 6px = 240, fits perfectly

**Review by Hannsek — APPROVED** [review]

**Comment by bosomt** [comment]
**QA OK**
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)

**Pull request merged**
