### PR TITLE
chore: update common defs

### PR DESCRIPTION
**Pull request by szymonlesisz**
- added Regtest and Decred to `connect.support`
- removed unsupported coins from `suite.support` 
- updated DOGE fees https://github.com/dogecoin/dogecoin/blob/master/doc/fee-recommendation.md#dust-limits those values are currently tested by QA, should be done by the end of the week

### CODE REVIEW

**Review by matejcik — APPROVED** [review]

**Comment by matejcik** [comment]
waiting for QA results before merging

**Comment by matejcik** [comment]
@szymonlesisz the relevant PR is merged in Connect, does this mean that we can merge this too?

**Comment by szymonlesisz** [comment]
yes pls, QA testing results are ok
https://github.com/trezor/trezor-suite/issues/4480#issuecomment-981430011

**Comment by matejcik** [comment]
this is now published to the `filter-repo` branch https://github.com/trezor/trezor-common/commits/filter-repo

The branch will probably become `master` in the near future, but it has a distinct history. I believe this does not matter for your usecase.

**Pull request merged**
