### PR TITLE
Add Pulsar Coin Support

### PR DESCRIPTION
**Pull request by PulsarCoin**

### CODE REVIEW

**Comment by matejcik** [comment]
Pulsar Coin is not supported in firmware so there is no point in adding a misc.json entry

**Comment by PulsarCoin** [comment]
Would it be correct to add a file in trezor-firmware/common/defs/bitcoin?

Or is Pulsar support needed elsewhere first?

Thank you!
Mason Smith

**Comment by matejcik** [comment]
If Pulsar is based on Bitcoin, then adding to `defs/bitcoin` would be appropriate, yes.

But be advised that we are currently not accepting new coin implementations anyway.

**Comment by PulsarCoin** [comment]
Thank you for the response,

We will take that into consideration. Do you have a timeline of when you
are accepting new coins? We would really appreciate the opportunity to work
with you guys to implement our coin.

Let me know!

**Pull request closed without merging**
