### PR TITLE
fix(cli): don't try to initialize device after wipe in bootloader

### PR DESCRIPTION
**Pull request by TychoVrahe**
what title says.

### CODE REVIEW

**Comment by matejcik** [comment]
I suspect it would be cleaner to try/except the `init_device` call and ignore any exception, no?

**Comment by TychoVrahe** [comment]
i wouldnt necessarily call trying something that we know will fail and handling the exception cleaner, but mainly i dont know that its gonna fail with exception (it does for current USB bootloader since we deinit on the device, but current BLE implementation just doesnt answer and cli hangs)

**Comment by matejcik** [comment]
> trying something that we know will fail and handling the exception

The point is that the caller isn't supposed to think about whether the implicit reinitialization will work or not; neither is there a reason to skip reinit unless you know in advance that it will fail.

> current BLE implementation just doesnt answer and cli hangs

this is an issue only in the bootloader, right?
so we could do "if client is bootloader then do not init"

**Comment by TychoVrahe** [comment]
ok moved the logic here https://github.com/trezor/trezor-firmware/commit/42af4086b48b6a2ed13a5b62d8f1ee1e346638b6

**Comment by matejcik** [comment]
perfect. please add a changelog entry too.

wondering what the failing upgrade test is about, it is unrelated here but...?
maybe a rebase will help?

**Review by matejcik — APPROVED** [review]

**Comment by matejcik** [comment]
yes please:
run the bootloader wipe (`trezorctl device wipe -b`) over straight webusb and over bridge
check that in previous version this would cause an exception trace
check that it does not happen anymore with master version of trezorctl

**Comment by bosomt** [comment]
**QA OK**

wiping 2.6.0/2.1.0 device:

**bridge running**

trezorctl 0.13.6
```
 ~/Trezor/trezor-firmware  on master !1  trezorctl wipe-device -b                                                                             trezor-firmware 
Wiping user data and firmware!
```

trezorctl 0.13.5
```
 ~/Trezor/trezor-firmware  on master !1  trezorctl wipe-device -b                                                                                                 
Wiping user data and firmware!
Error: trezord: read/16 failed with code 400: device disconnected during action
```

**bridge stopped**

trezorctl 0.13.6
```
 ~/Trezor/trezor-firmware  on master !1  trezorctl wipe-device -b                                                                              trezor-firmware 
Wiping user data and firmware!
```

trezorctl 0.13.5
```
 ~/Trezor/trezor-firmware  on master !1  trezorctl wipe-device -b                                                                                                
Wiping user data and firmware!
Traceback (most recent call last):
usb1.USBErrorIO: LIBUSB_ERROR_IO [-1]
```

**Pull request merged**
