### PR TITLE
Add full XRP support

### PR DESCRIPTION
**Pull request by patriksletmo**
# Summary
This pull request adds support for all 18 XRP Ledger transaction types and all common fields.

With new use-cases in web monetization, gaming and decentralized finance being built on top of the XRP Ledger, hardware wallet support for its more advanced features such as escrows, cross-currency payments and decentralized exchange orders are needed to maintain security and avoid stiffling innovation.

In short, we have:
- Maintained full backwards compatibility
- Re-written the serializer to support all [types](https://xrpl.org/serialization.html#type-list) present in transaction fields
- Implemented support for displaying all transaction fields
- Implemented support for displaying fields like flags and timestamps in a human-readable format
- Implemented support for reading the public key
- Implemented support for multi-signing 
- Please see the updated [README](https://github.com/TowoLabs/trezor-firmware/blob/ripple-full-old-messages/core/src/apps/ripple/README.md) for additional details. 

# Testing 
We have added unit tests in the `core/tests` directory and device integration tests in the `tests/device_tests` directory.

### CODE REVIEW

**Comment by prusnak** [comment]
The PR is sent against the wrong branch. Superseded by https://github.com/trezor/trezor-firmware/pull/849

**Comment by patriksletmo** [comment]
@prusnak Weren't we explicitly instructed to base our changes on the branch `ripple-full` [here](https://github.com/trezor/trezor-firmware/pull/424#issuecomment-523516077)?

Also, #848 and #849 are based upon different message formats (#424 and #818 respectively). Are you sure you want to close this PR in favor of #849?

**Comment by prusnak** [comment]
I was confused because you opened two PRs. I'll close# 849 then and reopen this one.

**Comment by patriksletmo** [comment]
Right, thank you! I was going to write an explanation to why there were two pull requests but you were quicker than me.

**Comment by patriksletmo** [comment]
We would appreciate if you could consider both this PR and #849. You are more than welcome to ask us questions about either of the implementations and we will do our best to answer them as soon as possible.

Once a decision has been made on which implementation you wish to proceed with, we intend to finalize the corresponding changes to [Trezor Connect](https://github.com/trezor/connect) and open a pull request.

**Comment by RareData** [comment]
Two months have passed without updates. What's the current status?

**Comment by prusnak** [comment]
The current status is that the PR needs to be evaluated but there are things with higher priority in the queue.

**Comment by RareData** [comment]
For transparency, do you have any public list with this prioritized queue? And is there anything we can do to assist?

**Comment by RareData** [comment]
Is this a reliable URL to watch your progress https://github.com/trezor/trezor-firmware/milestone/20?
When do you expect to plan the next sprint https://github.com/trezor/trezor-firmware/milestone/21?

**Comment by prusnak** [comment]
Issues marked with "Product Owner" label need to be evaluated first by the Product Owner, they are not assigned a milestone before this happens. Realistically, we can talk about Q3 of 2020, but not sooner. So please be patient.

**Comment by tsusanka** [comment]
Thank you for your PR, we appreciate it! I just wanted to provide an update on this from our side. Unfortunately, we don't have the capacity to review it right now. However, we'll make sure to get back to it as soon as our capacity frees up a bit, presumably during the course of 2021. Thank you for your understanding.

**Comment by RareData** [comment]
We're available around the clock, whenever your capacity frees up. If you truly stand for open-source, please do something about your one year review time. We have thousands of users wanting to trade on the XRPL DEX, send cross-currency payments, escrows and multi-sign using Trezor.

**Comment by sappenin** [comment]
Bump...

**Comment by an9218** [comment]
Please indicate the dates of execution of the request. It has been active for about a year, but nothing happens. XRP support is listed on the website, but it is actually incomplete. Trezor T was purchased for use with XRP.

**Comment by sec1000** [comment]
Do not bother guys!

**Comment by jclusso** [comment]
When is this going to be released...?!? I bought the Trezor because I thought open source firmware would be a better option yet you guys have entirely failed your users in not getting this PR through for like 2 years. This is embarassing.

**Comment by BaronVonDerpsalot** [comment]
Classic. User/customer asks "Hey this has taken forever! What's going on?!"
@matejzak or anyone at Trezor doesn't offer a response, just assigns the low priority tag and disappears. 

I've bought a D'Cent and the Trezor is now a very tiny coaster for my very tiny mugs.
Well played, Trezor!

**Comment by CreatureDev** [comment]
What's going on here
Extremely disappointed with trezor

**Comment by RareData** [comment]
A community contributor gave you ~5,000 LoC, adding support for all XRP Ledger TX types, requested by thousands of users, waiting almost 2 years... and you assign a LOW label with no further explanation? Please provide some transparency.

**Comment by RareData** [comment]
We're still available. If you require changes, say so. If you want to keep your XRP Ledger support to a minimum for whatever reason, say so. 

Trezor devices currently support ~5% of the XRP Ledger's feature set. It's like promising to support Ethereum, but in practice only supporting native ETH payments, but no transactions involving tokens or contract interactions.

**Comment by jclusso** [comment]
@karliatto @matejkriz @MrMebelMan @prusnak @tomasklim @vdovhanych any of you going to answer your customers... or just continue to ignore everyone that paid a for your product?

Also, maybe update your website and remove this section since you guys can't answer here. Support isn't 5 stars.
image

**Comment by WietseWind** [comment]
@prusnak @tsusanka and others Trezor: please allocate some time to review & hopefully merge. It's a huge omission for your users with XRP Ledger accounts *not* to have the features @RareData and @patriksletmo worked on added to your products.

**Comment by crypticrabbit** [comment]
Trezor team - I've got to agree with the rest of the discussion - please stop sitting on this, it would be terrific to have XRPL functionality in Trezor's. I know you all have likely been slammed, however, maybe @prusnak could at least give an update on the originally quoted "Q3 of 2020" estimate or @tsusanka's estimate "sometime during 2021".

I think it would be helpful to have some additional clarification - is Trezor really so strapped for resources, that devs/engineers are scheduling multiple years out? If so, that feels like a massive gap, and it leaves me questioning Trezor's longevity.

**Comment by WietseWind** [comment]
Jakub Ferschmann:
https://twitter.com/fersmi/status/1469033253004795906?s=20

> I spoke with @slush and here is his answer: "Honestly, we are and want to be a bitcoin first company. We have a lot of things on the roadmap that we need to implement and release, which are directly related to bitcoin, so I don't expect to get to this in a reasonable time."

> "Personally, I'm sorry, but we don't have the capacity to solve everything and we have to cut what is and isn't really done.
We are working on solving the community version of Trezor firmware, which would have less demands on the merge code, ..."

> "... this would partially solve this problem and at least it would be visible which projects are willing to actively keep the code. I think we'll introduce that soon, and Ripple's full support is almost an ideal candidate for this."

**Comment by x-Tokenize** [comment]
It would be great if this would be opened up for review.

The XRPL ecosystem has drastically grown since the initial pull request was opened and the basic XRPL functionality that Trezor currently provides is just not enough to utilize the ledger to it's full potential.

Please consider allocating some resources to make this a reality!

**Comment by RareData** [comment]
After 3 years of Trezor being unwilling to review our PR to add full XRP Ledger support, we made the decision to close it.

**Comment by WietseWind** [comment]
Shameful (looking at you, Trezor) that it came to this. Thank you for your amazing effort & work @RareData @patriksletmo.

**Pull request closed without merging**
