### PR TITLE
Tezos: add baking support

### PR DESCRIPTION
**Pull request by adonagy**
Ads signing for baking and endorsement operation.

Resubmitting PR from https://github.com/trezor/trezor-core/pull/473 and https://github.com/trezor/trezor-common/pull/267

### CODE REVIEW

**Comment by adonagy** [comment]
Currently working on a better way to display the signed operations. Considering worklfow.startdefault() as suggested in https://github.com/trezor/trezor-core/pull/473

**Comment by adonagy** [comment]
I created a new "baking" homescreen for the baking mode. With this approach we can display information of the last signed operation during the baking mode. 

We store the last level and the operation type in storage so in case of a restart, we can display the last signed operation when starting baking mode.

**Comment by tsusanka** [comment]
Hi there, thank you for your PR. I just wanted to give you a quick update from our side. We are interested in adding this to our firmware but we just don't have enough capacity to review it right now. We would be more than happy to take a closer look at it later, when our capacity frees up a little, likely during the course of 2021. Thank you for your understanding.

**Comment by jurajselep** [comment]
> Hi there, thank you for your PR. I just wanted to give you a quick update from our side. We are interested in adding this to our firmware but we just don't have enough capacity to review it right now. We would be more than happy to take a closer look at it later, when our capacity frees up a little, likely during the course of 2021. Thank you for your understanding.

this is great news,  we will update code to reflect latest 007 protocol update, thanks

**Comment by matejcik** [comment]
closing due to age -- the code in this PR is too hopelessly out of sync with the main branch.

also, we are currently not looking to add new features to the Tezos implementation.

**Pull request closed without merging**
