### PR TITLE
elements: support explicit addresses (p2pkh, p2sh and bech32)

### PR DESCRIPTION
**Pull request by romanz**
I have enabled Elements (#66) using the following commands:
```
$ ./common/tools/support.py set bitcoin:ELEMENTS trezor2=2.1.2
$ ./common/tools/cointool.py check
```

Also, I have regenerated `coins.json` and `coininfo.py`:
```
$ pipenv run make gen gen_check
```

### CODE REVIEW

**Comment by prusnak** [comment]
Let's remove the duplicated functions and use the following instead:

```
from bech32 import convertbits, bech32_hrp_expand
```

**Comment by romanz** [comment]
Good catch, thanks!

BTW, I think that we can add `blech32` code later, since it should be used only confidential addresses (explicit addresses are using `bech32`):
https://github.com/ElementsProject/elements/blob/3dd46d1730f4bed00f579772392345b99fdc4041/src/key_io.cpp#L69-L84

**Comment by prusnak** [comment]
What was the rationale behind creating a new scheme and not using bech32?

**Comment by romanz** [comment]
I am not sure, but IIUC the original bech32 doesn't support confidential addresses, since they contain a public blinding key (33 bytes) in addition to the witness program - so the resulting payload is above the [40 bytes limit of bech32](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#segwit-address-format).

CC: @instagibbs @stevenroose (following https://github.com/ElementsProject/elements/commit/9cb2fa051fcbe0fe66f15e6b88d224d1935376f4 and https://github.com/ElementsProject/elements/commit/0f2878036427e9b332fea6ef93f76d9898fbfb72).

**Comment by instagibbs** [comment]
Correct, it goes beyond the length that has the guaranteed "catch up to X errors".

**Comment by romanz** [comment]
Just to be sure, should I remove `blech32.py` from this PR?

**Comment by romanz** [comment]
P.S.
Also, I am not sure about the correct way of updating & re-generating `coininfo.py` - so please let me know if this PR should be split into several ones.

**Comment by romanz** [comment]
Rebased and force-pushed after https://github.com/trezor/trezor-firmware/commit/35ecfbcb3d7c62b3c346562f5ff30fec96d3b9c0.

**Comment by prusnak** [comment]
Rebased and merged as 93382a10f5b66cdfe133c0e2bbfd531859dacd1f

(we moved tests from `/python/trezorlib/tests` to `/tests`)

**Comment by romanz** [comment]
Thanks!

**Pull request closed without merging**
