### PR TITLE
chore(core): change error screens according to design

### PR DESCRIPTION
**Pull request by grdddj**
Fixes https://github.com/trezor/trezor-firmware/issues/3168:
- change the design of (not only) Fido error message

### CODE REVIEW

**Comment by Hannsek** [comment]
image

1. row: change `close` to `try again` please
2. row: from which flow this screen comes? When users would see this?
3. row: 👌🏻

**Comment by grdddj** [comment]
> * row: change `close` to `try again` please
> 
> * row: from which flow this screen comes? When users would see this?
> 
> * row: 👌🏻

Changed all the button texts to `TRY AGAIN` in this error screen.

The second one comes when you are asked for PIN and you give an incorrect one. So `TRY AGAIN` makes sense there as well

**Comment by Hannsek** [comment]
> The second one comes when you are asked for PIN and you give an incorrect one. So TRY AGAIN makes sense there as well

There shouldn't be a separate screen. There should be this: 
image
and after the first move it should change
image

**Comment by grdddj** [comment]
> > The second one comes when you are asked for PIN and you give an incorrect one. So TRY AGAIN makes sense there as well
> 
> There shouldn't be a separate screen. There should be this: image and after the first move it should change image

Right, let's rather create a separate issues for this? I will record the test changes here and will be ready for merge

**Review by mmilata — APPROVED** [review]
LGTM! Please fix style before merging.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.10.1 (6c8d061f7305947b0270a2560e4cc65d1f7ded27)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.10.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2B1 2.6.2 regular (revision 6e5967af25de87bebd331d697e6ef940e64286ef)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
