### PR TITLE
fix(core/ui): hold to confirm when finializing replacement transaction

### PR DESCRIPTION
**Pull request by mmilata**
Currently the button has label NEXT even though it's the last confirmation shown.

Before and after:
Screenshot 2023-04-09 at 18-44-59 TT-device_tests-bitcoin-test_signtx_replacement py test_p2wpkh_payjoin 19909859-89800-02483045022100af3a87-80428fad

### CODE REVIEW

**Review by matejcik — APPROVED** [review]
utACK

**Comment by Hannsek** [comment]
Are you sure it is the last confirmation screen? I saw this several times not on the last screen. -> https://github.com/trezor/trezor-firmware/issues/2938

**Comment by mmilata** [comment]
It's called from the same place as `confirm_total` and in our UI testcases it's always last: https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/4084193934/artifacts/master_diff/index.html.

Linked issue uses different layouts and this PR does not affect them.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.6.1 (bddd516378beadfcff94523e7c94834ba14f147f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.6.1 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision 089ff768229f543c89927ff34c4d45d830a2442f)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
