### PR TITLE
Docs: Update links in changelog

### PR DESCRIPTION
**Pull request by Carlosbogo**
Updates the links in the changelogs so that they are not broken anymore due to changes from Github, as mentioned in #2011.

### CODE REVIEW

**Comment by prusnak** [comment]
What do you think @matejcik?

It (mis)uses the fact that `/pull/` -> `/issues/` redirect still works on GitHub and IMO that's good enough at least for now.

**Comment by Carlosbogo** [comment]
I actually checked all the files mentioned in #2011 and the only ones that had broken links are the ones I changed. If I missed something please tell me and I'll be glad to help.

**Comment by prusnak** [comment]
> and the only ones that had broken links are the ones I changed.

You missed `python/CHANGELOG.md`, but you are right about the rest that no changes were necessary.

**Comment by Carlosbogo** [comment]
Sorry about that, I just added those changes too. Thanks for pointing it out.

**Comment by matejcik** [comment]
Good enough for now, I suppose. In the future we'll want to do something like, ping `/issues/` and use `/pull/` if it fails

**Comment by prusnak** [comment]
@Carlosbogo thank you for your contribution!

**Pull request merged**
