### PR TITLE
Fix firmware initialization

### LINKED ISSUE #2130: Do not initialize touch controller in firmware
Touch controller comes pre-initialized from bootloader. I believe we don't need to re-initialize in firmware's `main.c` (doing so incurs ~500 ms delay waiting for the controller to power down and boot back up).

Is there any reason not doing the initialization would be a problem? @hiviah @prusnak 

The only thing comes to mind is, bootloader might be using different configuration. Even in that case, it should be sufficient to (a) check that the controller is up and (b) send the configuration commands.

### PR DESCRIPTION
**Pull request by TychoVrahe**
This PR partially reintroduces touch controller initialization in firmware:
- turns out that if we want to change operation mode of the controller in future, we might have issues when settings from bootloader being incompatible with algorithm used in firmware - this could happen for example if new bootloader is used with intentionally downgraded firmware
- the removal of initialization also caused uninitialized i2c handler being used, which only accidentally didn't cause crashes due to fact that the touch_read function evaluated the uninitialized handler as being BUSY, and thus did I2C reset cycle, which fixed things - but this introduced some unnecessary delays
- this PR also fixes Model R firmware initialization, where some stuff wasn't called and some stuff was called twice or erroneously. A little reorganization of compilation conditions was make the process more clear.

closes #2130

### CODE REVIEW

**Review by hiviah — APPROVED** [review]
LGTM, though at first the ifdef regrouping was a bit confusing.

**Comment by matejcik** [comment]
please remove or modify this changelog entry: https://github.com/trezor/trezor-firmware/blob/master/core/.changelog.d/2130.removed

**Comment by TychoVrahe** [comment]
Modified the log entry.

**Review by matejcik — APPROVED** [review]

**Comment by matejcik** [comment]
please squash the fixup and merge

**Pull request merged**
