### PR TITLE
implement Zpub-s for multisig GetAddress

### PR DESCRIPTION
**Pull request by prusnak**
This builds on top of PR https://github.com/trezor/trezor-firmware/pull/1420 so that needs to be merged first!

Fixes https://github.com/trezor/trezor-firmware/issues/855 (first bug out of two, the second one has been fixed already) - reported here: https://twitter.com/_benma_/status/1227900614505566208

### CODE REVIEW

**Comment by matejcik** [comment]
what is the usecase for `ignore_xpub_magic` here?

**Review by matejcik — APPROVED** [review]
tentative approve, code LGTM

**Comment by prusnak** [comment]
> what is the usecase for `ignore_xpub_magic` here?

So client can select whether they want to show multisig xpubs with `xpub` or `Zpub` prefix

**Review by mmilata — APPROVED** [review]
Tested with Electrum:
* create 2of2 p2wsh m/48'/0'/0'/2' wallet using 2xTT
* create payment request in _Receive_ tab
* clicking on the _eye icon_, TT displays address, QR code, and the public keys in Zpub format
* public keys equal those in _Wallet>Information_ window

Changes LGTM, dunno why the cardano tests fail.

**Review by matejcik — APPROVED** [review]

**Comment by prusnak** [comment]
Rebased and force pushed - if the tests will be green again, we can merge

**Comment by IanMichaelHarper** [comment]
> * clicking on the _eye icon_, TT displays address, QR code, and the public keys in Zpub format

I just tried this in electrum with the Trezor One and the eye icon fails to display. I don't know if there's another way to get the Trezor One to display its Zpub.

**Comment by prusnak** [comment]
> > * clicking on the _eye icon_, TT displays address, QR code, and the public keys in Zpub format
> 
> I just tried this in electrum with the Trezor One and the eye icon fails to display. I don't know if there's another way to get the Trezor One to display its Zpub.

Are you using multisig or not?

**Comment by IanMichaelHarper** [comment]
> > > * clicking on the _eye icon_, TT displays address, QR code, and the public keys in Zpub format
> > 
> > 
> > I just tried this in electrum with the Trezor One and the eye icon fails to display. I don't know if there's another way to get the Trezor One to display its Zpub.
> 
> Are you using multisig or not?

I am

**Comment by prusnak** [comment]
> I am

Will you please open an issue in the Electrum repository - https://github.com/spesmilo/electrum?  Thanks!

**Pull request merged**
