### PR TITLE
Add BitZeny for Trezor-Common

### PR DESCRIPTION
**Pull request by y-chan**

### CODE REVIEW

**Comment by prusnak** [comment]
Don't add any other files except the bitzeny.json

**Comment by y-chan** [comment]
I fixed it.

**Comment by y-chan** [comment]
@prusnak May I edit wallet.json?

**Comment by prusnak** [comment]
y-chan: yes

**Comment by y-chan** [comment]
ok

**Comment by y-chan** [comment]
Added Wallet.

**Pull request merged**
