### PR TITLE
xmr: fix new transaction type for CLSAG, HF=13

### PR DESCRIPTION
**Pull request by ph4r05**
- Changes required to make CLSAG working.
- Transaction type was not set accordingly
- Related to the https://github.com/monero-project/monero/pull/6798
- New binary tests testing both HF=12 and HF=13: https://github.com/ph4r05/monero/releases/tag/v16.0.0.0-tests-u18.04-01

### CODE REVIEW

**Comment by prusnak** [comment]
@ph4r05 What is the date this should appear in the firmware update? We haven't planned to do a firmware update soon, so knowing that will help us plan accordingly.

**Comment by ph4r05** [comment]
@sarangNoether do we pls have any time estimate when CLSAG appears on the Mainnet?

**Comment by SarangNoether** [comment]
> @SarangNoether do we pls have any time estimate when CLSAG appears on the Mainnet?

Binaries should be released around September 17, and CLSAG functionality will be activated on the network at a set block height around October 17 (and will be mandatory).

**Review by onvej-sl — APPROVED** [review]
utACK

**Comment by onvej-sl** [comment]
So it means that:
  * Transaction sending in Monero won't work after the hardfork until we release a new firmware with activated CLSAG.
  * CLSAG is activated by setting `self.hard_fork = 13` [here](https://github.com/trezor/trezor-firmware/blob/61c8d2404c292591e7eb8c8afa9dda42465716ca/core/src/apps/monero/signing/state.py#L65).

Am I right, @ph4r05 ?

**Comment by ph4r05** [comment]
@onvej-sl 
- correct, after hardfork activation, no transaction could be signed without this PR merged. 
- I am not sure what do you mean. `state.hard_fork` is set by the client in the first protocol step `state.hard_fork = tsx_data.hard_fork`. This PR also fixes a bug setting correct transaction type. i.e., `state.tx_type`. Without this, the transaction won't be accepted.

**Comment by onvej-sl** [comment]
My mistake, I missed that.

**Comment by SarangNoether** [comment]
@ph4r05: Will any additional Monero codebase PRs be required to ensure Trezor support?

**Comment by ph4r05** [comment]
> @ph4r05: Will any additional Monero codebase PRs be required to ensure Trezor support?

No, this was all. All required PRs are merged. I've tested it with integration tests on both HF=12 and 13 blockchains and Trezor-signed transactions passed the verification process.

**Comment by SarangNoether** [comment]
> > @ph4r05: Will any additional Monero codebase PRs be required to ensure Trezor support?
> 
> No, this was all. All required PRs are merged. I've tested it with integration tests on both HF=12 and 13 blockchains and Trezor-signed transactions passed the verification process.

Great! Monero binaries will be prepared and released soon, and CLSAG functionality will be activated (and required) around 17 October 2020.

**Comment by SarangNoether** [comment]
@ph4r05 (and others): Is it expected that Trezor firmware will be updated/released in advance of the CLSAG activation date?

**Comment by tsusanka** [comment]
@SarangNoether our original plan was to release on November 4th. Is the date Oct 17th already set in stone and definite?

**Comment by SarangNoether** [comment]
> @SarangNoether our original plan was to release on November 4th. Is the date Oct 17th already set in stone and definite?

The upgrade block height has already been merged. I posed the situation to the developer IRC channel, but any potential decision to delay this is not up to me.

**Comment by tsusanka** [comment]
Ok in worst case scenario we will release on Oct 6th. It messes up some planning of ours but we'll manage :). Let me know. Thanks!

**Comment by SarangNoether** [comment]
> Ok in worst case scenario we will release on Oct 6th. It messes up some planning of ours but we'll manage :). Let me know. Thanks!

Sounds good! I will follow up here with any developments.

**Comment by SarangNoether** [comment]
> Ok in worst case scenario we will release on Oct 6th. It messes up some planning of ours but we'll manage :). Let me know. Thanks!

I did not hear support in the development channel to change the upgrade block height, so I think it is safe to assume that it will remain the same and take place around October 17.

**Comment by prusnak** [comment]
@SarangNoether Is the upcoming hardfork already deployed on Stagenet/Testnet? Where do I find info like this - roadmap of hardforks?

**Comment by selsta** [comment]
It is deployed on testnet and will be deployed to stagenet on 2020-09-28.

- https://www.getmonero.org/2020/08/18/network-upgrade-october-2020.html
- https://github.com/monero-project/monero#scheduled-software-upgrades

**Comment by tsusanka** [comment]
We will release on Oct 6th then, firmware version 2.3.4.

**Comment by bosomt** [comment]
@SarangNoether 
is there way to test new FW before fork ?

1) is there publick testnet node that we can use ?
2) where we can get some testnet XMRs

**Comment by prusnak** [comment]
@bosomt AFAIK you can use both Stagenet and Testnet to perform the test, here are the public servers and faucets info:
* https://monerodocs.org/infrastructure/networks/#stagenet
* https://monerodocs.org/infrastructure/networks/#testnet

**Comment by selsta** [comment]
Alternatively you can find testnet / stagenet nodes here: https://community.xmr.to/nodes.html

Faucet:

- https://community.xmr.to/faucet/stagenet/
- https://community.xmr.to/faucet/testnet/

**Comment by bosomt** [comment]
**QA OK**


sent tests transactions via gui client:

- Monero - v0.17.0.1-release Oxygen Orion
- KUbuntu 
- FW Revision: 55baf3ac

RingCT/type: yes/5

**Send XMR transaction**
https://community.xmr.to/explorer/testnet/search?value=a9acffe1137dc13aac08ededbc4630ff6bef68dbcf7654d4f7829b09f27ab1b4

 **Send and receive XMR with passphrase**
https://community.xmr.to/explorer/testnet/search?value=0df427f0b7d6bc16a66e60c02a4298e38feb68e63be222e9b58ccd157fc86c9b

**Comment by ph4r05** [comment]
Nice! Thanks @bosomt !

**Comment by selsta** [comment]
Thank you for publishing the new firmware version with CLSAG support. We will take the extra potential time necessary for firmware updates into account in future network upgrades.

**Pull request merged**
