### PR TITLE
fix(core/ui): T2T1: display coinjoin icon on lockscreen

### LINKED ISSUE #3004: Coinjoin icon on locked device
When cj is running, display cj icon on blurred/locked screen

https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?type=design&node-id=8315%3A68021&t=iuOSNFxA4iwjgsGw-1

image

### PR DESCRIPTION
**Pull request by mmilata**
Fixes #3004.

[UI diff](https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/5322995536/artifacts/master_diff/index.html) | [differing screens](https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/5322995536/artifacts/master_diff/master_diff.html)

d4d69b9f6d3d18b563764036a479fe26da1cc217fd44cc94136711eb05ea6444

### CODE REVIEW

**Comment by Hannsek** [comment]
Is this done also for T2B1?

**Comment by mmilata** [comment]
no

**Comment by Hannsek** [comment]
Please add it to T2B1 as well. 
image


position it 2 px from the side and top.

[cj.png.zip](https://github.com/trezor/trezor-firmware/files/13040357/cj.png.zip)

**Comment by TychoVrahe** [comment]
the TT icon is not centered and its triggering my OCD :)

**Comment by mmilata** [comment]
Updated:
33d43aa7430fffc71558b9da0b01c14871d948b0948bc441b74105f3127c31c0
d983eba5666c9f8934ec1d47c2b9672b97e103e0e4c5e99e51a71cd09548bc8d

Note to self: update commit message when rebasing.

**Review by grdddj — APPROVED** [review]
Code-wise LGTM!

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.11.1 (091c08da42e804460aa8f54b1155f6888b470391)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.11.1 Chrome/116.0.5845.228 Electron/26.4.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2B1 2.6.3 regular (revision 297b2bade72c55033fc3c93c1da818c42b7f453d)
 - Transport: BridgeTransport 2.0.32

**Pull request merged**
