### PR TITLE
style(core): use PEP515 Underscores in Numeric Literals

### PR DESCRIPTION
**Pull request by prusnak**
It is what it is :smile: 

This helps tremendously when dealing with values such as `0x7FFFFFFFF` or `500000000`

### CODE REVIEW

**Comment by prusnak** [comment]
I wonder whether there is a style check which would enforce this for numeric literals? Maybe @matejcik knows?

**Review by andrewkozlik — APPROVED** [review]
LGTM, although I must say that `0x10000` somehow seems a bit more legible to me than `0x1_0000`.

**Comment by prusnak** [comment]
I don't mind reverting `0x1_0000` back to `0x10000` ...

**Comment by andrewkozlik** [comment]
> I don't mind reverting `0x1_0000` back to `0x10000` ...

I don't mind it too much. Just making an observation.

**Pull request merged**
