### PR TITLE
Show account in dialogs

### PR DESCRIPTION
**Pull request by andrewkozlik**
Implements https://github.com/trezor/trezor-firmware/issues/2151 and https://github.com/trezor/trezor-firmware/issues/2152.

image image image

I also added similar information to `GetAddress`:

image image image

### CODE REVIEW

**Comment by Hannsek** [comment]
There are new designs for each flow, please do not merge this.

**Comment by Hannsek** [comment]
New design here: https://github.com/trezor/trezor-firmware/issues/2680#issuecomment-1424502234

**Comment by andrewkozlik** [comment]
So I take it the code in this PR will be taken over by @mmilata as part of https://github.com/trezor/trezor-firmware/issues/2680?

**Comment by mmilata** [comment]
Will do that. I was unaware of this PR and was going to use 117c79212561269807c94449db8e9ee824e47bb1 from #2803 but this one seems more comprehensive.

**Comment by Hannsek** [comment]
@mmilata Should we then change it in model R as well?

**Comment by Hannsek** [comment]
Closing in favour of #2680.

**Pull request closed without merging**
