### PR TITLE
feat(python): add pretty-printing of protobuf messages in IPython

### PR DESCRIPTION
**Pull request by dlitz**
This makes protobuf messages look much nicer in IPython:

Before:
<tt>In[5]: client.features
Out[5]:
<Features: {'vendor': 'trezor.io', 'major_version': 2, 'minor_version': 7, 'patch_version': 2, 'device_id': '[redacted]', 'pin_protection': True, 'language': 'en-US', 'label': '[redacted]', 'initialized': True, 'revision': b'\xdau\xd8\xf4\xb6t\x10\xb4\n\x9c\xfd)T\xd1\x83\xd8\x1d\xd6\xe8\xe8', 'unlocked': False, 'model': 'T', 'fw_vendor': 'SatoshiLabs', 'capabilities': [<Capability.Bitcoin: 1>, <Capability.Bitcoin_like: 2>, <Capability.Binance: 3>, <Capability.Cardano: 4>, <Capability.Crypto: 5>, <Capability.Ethereum: 7>, <Capability.Monero: 9>, <Capability.Ripple: 11>, <Capability.Stellar: 12>, <Capability.Tezos: 13>, <Capability.U2F: 14>, <Capability.Shamir: 15>, <Capability.ShamirGroups: 16>, <Capability.PassphraseEntry: 17>, <Capability.Solana: 18>, <Capability.Translations: 19>, <Capability.NEM: 10>, <Capability.EOS: 6>, <Capability.Brightness: 20>], 'sd_card_present': True, 'busy': False, 'homescreen_format': <HomescreenFormat.Jpeg: 2>, 'internal_model': 'T2T1', 'homescreen_width': 240, 'homescreen_height': 240, 'language_version_matches': True}>
</tt>

After:
```
In[5]: client.features
Out[5]:
<Features: {'vendor': 'trezor.io',
            'major_version': 2,
            'minor_version': 7,
            'patch_version': 2,
            'device_id': '[redacted]',
            'pin_protection': True,
            'language': 'en-US',
            'label': '[redacted]',
            'initialized': True,
            'revision': b'\xdau\xd8\xf4\xb6t\x10\xb4\n\x9c\xfd)T\xd1\x83\xd8\x1d\xd6\xe8\xe8',
            'unlocked': False,
            'model': 'T',
            'fw_vendor': 'SatoshiLabs',
            'capabilities': [<Capability.Bitcoin: 1>,
                             <Capability.Bitcoin_like: 2>,
                             <Capability.Binance: 3>,
                             <Capability.Cardano: 4>,
                             <Capability.Crypto: 5>,
                             <Capability.Ethereum: 7>,
                             <Capability.Monero: 9>,
                             <Capability.Ripple: 11>,
                             <Capability.Stellar: 12>,
                             <Capability.Tezos: 13>,
                             <Capability.U2F: 14>,
                             <Capability.Shamir: 15>,
                             <Capability.ShamirGroups: 16>,
                             <Capability.PassphraseEntry: 17>,
                             <Capability.Solana: 18>,
                             <Capability.Translations: 19>,
                             <Capability.NEM: 10>,
                             <Capability.EOS: 6>,
                             <Capability.Brightness: 20>],
            'sd_card_present': True,
            'busy': False,
            'homescreen_format': <HomescreenFormat.Jpeg: 2>,
            'internal_model': 'T2T1',
            'homescreen_width': 240,
            'homescreen_height': 240,
            'language_version_matches': True}>
```

### CODE REVIEW

**Comment by matejcik** [comment]
```
./src/trezorlib/protobuf.py:39:5: I900 'IPython' not listed as a requirement
49
./src/trezorlib/protobuf.py:283:43: F541 f-string is missing placeholders
```
you can proooobably just silence the I900 ? the only problem I can think of is if pyright (or mypy) suddenly decided that they need to be able to import that class.

(adding ipython as a requirement for this is a no-go obviously)

also please add a short docstring explaining what `_repr_pretty_` is for, it's not exactly common

**Comment by dlitz** [comment]
Sounds good.  I just pushed an update with the following changes:
* ignored I900 'IPython' not listed as a requirement -- as you suggested
* ignored F541 f-string is missing placeholders -- I did this on purpose so that generic brace-matching algorithms in text editors don't get confused
* docstring added
* rebased onto main

**Comment by matejcik** [comment]
> * ignored F541 f-string is missing placeholders -- I did this on purpose so that generic brace-matching algorithms in text editors don't get confused

uhhh what sort of editor do you have that will get confused by `}}` in a normal string but not in a f-string??

**Comment by dlitz** [comment]
Vim's brace-matching "showmatch" feature just blindly matches every `{` with every `}`, including inside strings and comments (although the syntax-error highlighting seems to override this in some cases :shrug:).  The `f"}}"` is meant to match up with the `prefix = f"... {{"` above.

**Comment by matejcik** [comment]
weird but whatever i guess :woman_shrugging: 

please add a changelog entry about this: https://docs.trezor.io/trezor-firmware/misc/changelog.html

**Comment by prusnak** [comment]
`import IPython` should be put in try except if the module does not exist

**Comment by matejcik** [comment]
> `import IPython` should be put in `try except` if the module does not exist

it's under `TYPE_CHECKING` so it should not be an issue

**Comment by prusnak** [comment]
> it's under `TYPE_CHECKING` so it should not be an issue

How come?

**Comment by matejcik** [comment]
> > it's under `TYPE_CHECKING` so it should not be an issue
> 
> How come?

`TYPE_CHECKING` is `False` at run-time so this never executes
only the typecheckers will read this code, and they handle missing imports without hiccups

**Comment by prusnak** [comment]
> they handle missing imports without hiccups

Aha, I did not know this (that type checkers can gracefully handle missing imports). Thanks, TIL

**Review by matejcik — CHANGES_REQUESTED** [review]
hello @dlitz, would you mind rebasing on current main and adding a changelog entry?
https://docs.trezor.io/trezor-firmware/misc/changelog.html

i'd do it but pushing to others' branches is messy on github

**Comment by dlitz** [comment]
Sure, done.

**Comment by matejcik** [comment]
ohhh drat i messed up my own edit by calling it a `fixup!` and now the mandatory "block fixup" job won't let me squash & merge as I wanted originally.

please fixup my fixup into your commit so that we can merge this

**Review by matejcik — APPROVED** [review]

**Pull request merged**
