### PR TITLE
add bitcoin clone

### PR DESCRIPTION
**Pull request by MachaUniverse**
cducoin is a bitcoin clone

### CODE REVIEW

**Comment by prusnak** [comment]
Duplicate of https://github.com/trezor/trezor-firmware/pull/1823

**Comment by MachaUniverse** [comment]
https://wiki.trezor.io/Developers_guide:Contributing

"If the coin you are adding is a fork of Bitcoin or other cryptocurrency we already support (in other words, new app is not needed) you can modify the definitions in the trezor-firmwarerepository and file a PR. In such case the coin does not have to be in TOP30"

**Comment by prusnak** [comment]
Quoting from the same wiki:

> At the moment, we do not have the capacity to add new coins that do not fit the aforementioned category. Our current product goal is to unite what we support in firmware and in Trezor Suite and since firmware is way ahead of Suite we want to pause for a bit, implement the remaining coins into Suite and then consider adding new coins. This effectively means that our team will not be accepting any requests to add new cryptocurrencies.

**Comment by prusnak** [comment]
Which CDU wallet supports Trezor so we can test the integration?

**Comment by MachaUniverse** [comment]
Lookout for the cdu wallet via email as the coin is not publicly released yet.

**Pull request closed without merging**
