### PR TITLE
Small update of copy in tutorial flow

### PR DESCRIPTION
**Pull request by obrusvit**
Instruction of the last screen changed from "Exit tutorial" to "Hold to exit tutorial Adjustments of some strings were needed in other langs so that they fit on screen.

This PR also adds inverted exclamation mark  `¡` for spanish language -> some UI changes might be visible in all core models.

### CODE REVIEW

**Comment by mmilata** [comment]
Nice fixes! Still, not everything fits:

42487548f516d6818d8190c7edf724f9dda44d45865955508c8d448b03a605db 89e8f8101fb47c6b021cc4a2ec2e3f43f7e37c0713150a75d96f0c2be76e151b

Third line would kinda sorta work?

89e8f8101fb47c6b021cc4a2ec2e3f43f7e37c0713150a75d96f0c2be76e151b-m

**Comment by obrusvit** [comment]
> Nice fixes! Still, not everything fits:

@mmilata True, however, I kept it this way for `fr` and `es` because the sentence is grammatically correct and makes sense. It basically reads "Hold to confirm" and "Hold to confirm actions" respectively instead of the most correct "Hold to confirm important actions". I'd keep it this way until we have a better solution, perhaps the 3-line header.

**Comment by obrusvit** [comment]
For some reason, there are UI tests failing for all non-`en` langs in `device_tests/test_msg_applysettings.py::test_experimental_features`. They run fine locally.
image

**Review by mmilata — APPROVED** [review]

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.7.3 (19fd64f5b2ab1bc265821e34d4c4b9c910864d0e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.1 regular (revision 008490bf4b8a04a085c59e217f743c9713727480)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
