### PR TITLE
docs(core): differentiate changelog entries between models

### LINKED ISSUE #3159: Differentiate changelog entries between core models
We should be able to produce changelog for T2T1 independent of changelog for T2B1, and not include T2B1-specific items for T2T1 and vice versa.

Probably as simple as creating a convention for changelog entries, e.g., `[T2B1] Changelog goes here` for model-specific?

### PR DESCRIPTION
**Pull request by mmilata**
Fixes #3159. Not sure if we actually want the `CHANGELOG.XXXX.md` files but we should at least update the docs.

Rendered:
* [CHANGELOG.md](https://github.com/trezor/trezor-firmware/blob/mmilata/changelog-models/core/CHANGELOG.md)
* [CHANGELOG.T2B1.md](https://github.com/trezor/trezor-firmware/blob/mmilata/changelog-models/core/CHANGELOG.T2B1.md)
* [CHANGELOG.T2T1.md](https://github.com/trezor/trezor-firmware/blob/mmilata/changelog-models/core/CHANGELOG.T2T1.md)

### CODE REVIEW

**Comment by matejcik** [comment]
@matejkriz @Hermez-cz does this look good to you?

**Review by matejcik — APPROVED** [review]
LGTM codewise but let's wait for Suite guys to see the results

**Comment by matejkriz** [comment]
Technically, I would expect T2B1 changelog starting with 2.6.1 and filtering out versions with no changes related to the model like this https://github.com/trezor/trezor-firmware/blob/mmilata/changelog-models/core/CHANGELOG.T2T1.md#262-internal-release. But the product priority seems to be low, so it's up to @Hermez-cz if and when we want to deal with this...

**Comment by matejcik** [comment]
let's keep it as-is then

**Pull request merged**
