### PR TITLE
T2B1 tutorial and buttons

### PR DESCRIPTION
**Pull request by grdddj**
Fixes https://github.com/trezor/trezor-firmware/issues/3080:
- modified tutorial copy and other smaller changes (buttons, titles)

To make the buttons  - Fixes https://github.com/trezor/trezor-firmware/issues/3016:
- regenerating icons to match new designs and not to have an empty bottom row

One screen is not exact as in `Figma` - the `...doesn't fit` - it is not centered vertically as that would require a special layout for this screen. Same thing with the left button - it is the last page of the two-page flow, so it does not have "fat" up arrow on the left, but just "slim"

image

### CODE REVIEW

**Comment by Hannsek** [comment]
> utACK for code

this was the fastest review I ever saw. 🧙🏻‍♂️

**Comment by grdddj** [comment]
> I belive we can _fix_ the vertical centering by addind header: image

Unfortunately, this is not possible currently, there is no concept of "header" in this flow - it is just hardcoded `bold` text at the top and then the rest in `normal` font 

> Btw, I don't thing the body text is centered between the header and pressed button: image


Right, it might not be precisely centered - I have just put some pixel margin on top "from the eye" as I was not sure it is precisely centered in `Figma`. Do we want it or is this good enough?

**Comment by Hannsek** [comment]
> Unfortunately, this is not possible currently, there is no concept of "header" in this flow - it is just hardcoded bold text at the top and then the rest in normal font

Can we introduce the concept of header in this flow? We have headers in other flows so why not in this one?

> Right, it might not be precisely centered - I have just put some pixel margin on top "from the eye" as I was not sure it is precisely centered in Figma. Do we want it or is this good enough?

Ok, but yeah, we want this everywhere. I thought that we center the _body_ text on every screen, at least on TT (@mmilata)

**Comment by grdddj** [comment]
> > Unfortunately, this is not possible currently, there is no concept of "header" in this flow - it is just hardcoded bold text at the top and then the rest in normal font
> 
> Can we introduce the concept of header in this flow? We have headers in other flows so why not in this one?
> 
> > Right, it might not be precisely centered - I have just put some pixel margin on top "from the eye" as I was not sure it is precisely centered in Figma. Do we want it or is this good enough?
> 
> Ok, but yeah, we want this everywhere. I thought that we center the _body_ text on every screen, at least on TT (@mmilata)

Both the header and centering introduced in recent commits

image

**Comment by grdddj** [comment]
> Nice, perfect.👌🏻 Just please add a line to the second _screen scroll_ screen to look like this: image

Done during the rebase and force-push. I can already merge this if you agree.

(There is this difference in line count, it will fit on Trezor on one line - hope it is not a problem)

image

**Comment by Hannsek** [comment]
Btw how big is the gap between individual letters in fonts on TR?

**Comment by grdddj** [comment]
> Btw how big is the gap between individual letters in fonts on TR?

Seems that one pixel - at least here in regular and bold - I guess same everywhere else (but is attribute of the font)

image

**Pull request merged**
