### PR TITLE
improve header signing tools

### LINKED ISSUE #111: rework signing tools
- `keyctl` and friends
  - signature checking VALID/INVALID
  - Pyro4 reconnecting

### PR DESCRIPTION
**Pull request by matejcik**
fixes #111 and helps with #660

keyctl-proxy modifications are not tested at this moment, because I don't have a T1 at home. That's why this is a draft.

I chose to create a new file called `headertool.py`, which might be renamed to `headertool`. But the usage is close enough to original `binctl` so that we can also call it `binctl` if desired?

headertool can:
* display information about headers
* tell you whether signatures/hashes are MISSING, INVALID, VALID or DEVEL
* output digest and exit (regardless of whether hashes are generated or not)
* force rehash (but that's rarely needed as rehashing now happens as part of signing)
* insert externally provided signature (like `binctl -s CAFE1337` did)
* directly sign with privkeys (like `binctl -s $(keyctl 01BEEF 02CACE)`)
* connect to keyctl-proxies and insert the resulting signature in a single step
* replace vendor-header with a different one, if the other one has the same size (`headertool -D -V otherheader.bin` does what #660 wants)

keyctl-proxy can:
* parse the built header image, calculate digest locally and check if the remote side is asking for the correct one
* verify commitment public key against the list of known signers and re-ask for passphrase if you mistype

generate_vendorheader now consumes JSON-defined headers, which just seems nicer than having to specify everything on the command line

keyctl and keyctl-coordinator functionality is now included in headertool, see e.g. https://github.com/trezor/trezor-firmware/commit/43ad26c3475b25050e4145115ac72ca6d4e7c77e#diff-3f7ac6afb30d956cd3c6f20c0cc88ae2R183
it seemed cleaner to keep keyctl-proxy as a separate executable, but it can also be merged in, if desired.

the original report #111 mentions "Pyro4 reconnecting", i'm not sure what that is about?

i will also write a summary of the signing process

### CODE REVIEW

**Comment by matejcik** [comment]
`keyctl-proxy` now actually works, and is prettier too! :) :100:

**Comment by prusnak** [comment]
Great changeset!

> the original report #111 mentions "Pyro4 reconnecting", i'm not sure what that is about?

I meant that the process should survive (short) network interruptions. Maybe that's something that is already solved by Pyro4 gracefully, I just put the note there to check whether that works fine.

**Comment by matejcik** [comment]
the commit 6bf7ef0 is untested for now, but it should make a good situation even better:
- the commitment was already generated offline before this change
- signature is now cached on the proxy as well, so in case of a problem, you just hit headertool again and it will run fast this time
- every remote call is its own connection to the proxy, so network problems at A should not affect B
- enabled Pyro's timeout and auto-retry facility to (try to) make it succeed even in the face of a failing network

**Comment by matejcik** [comment]
> * enabled Pyro's timeout and auto-retry facility to (try to) make it succeed even in the face of a failing network

This turns out to interfere badly with the interactive nature of Trezor signing, so I have dropped that feature.

Anyway, ISTM that as defined now, the network fault resilience is sufficient. Within a single call, the tcp session can survive a brief network disconnection (presumably as long as no packets are actually dropped?). The connection is closed and reopened between calls, so there is nothing to lose here. In case a problem does arise, re-running headertool will get cached results from all participants who already have them. And keyctl-proxy will exit cleanly when the coordinator signals that signing is done, so all the signers have to do is commit once and sign once.

Related, wouldn't it be better to make commit-and-sign a single two-step operation on Trezor? :) with only one confirmation screen.

**Comment by prusnak** [comment]
Btw, currently this fails here: https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/409210202#L585

(you used 3.6+ format syntax and we still test for py3.5 compatibility)

I let you decide whether we'll fix it or we drop py3.5 compatibility. (Seems that debian stable is on python3.7 already).

**Comment by matejcik** [comment]
thanks for the catch. I'll keep py3.5 compatibility for a couple more months

**Comment by prusnak** [comment]
Fixed in f4d5b473c29180bbe18225ce7318a4cae3e69aa8

**Comment by prusnak** [comment]
Great work! Merged! \o/

**Pull request merged**
