### PR TITLE
chore(ci): update alpine-linux to 3.14.0 and nix to 2.3.14

### PR DESCRIPTION
**Pull request by prusnak**

### CODE REVIEW

**Review by tsusanka — APPROVED** [review]

**Comment by matejcik** [comment]
style check is failing. did clang-format version change?

**Comment by prusnak** [comment]
> clang-format version change?

I think it did, although I don't understand how this could happen.

**Comment by mmilata** [comment]
It's failing in master too, fix: #1689.

**Review by mmilata — COMMENTED** [review]
There's another `ALPINE_VERSION` set inside `ci/environment.yml`. I wonder if we can drop it from there and download the minirootfs in the Dockerfile?

**Comment by prusnak** [comment]
> I wonder if we can drop it from there and download the minirootfs in the Dockerfile?

Might be possible too, but for now I just changed the `ci/environment.yml` too.

**Pull request merged**
