### PR TITLE
feat: add xDai network support

### PR DESCRIPTION
**Pull request by yuval-k**
Note: I tested the firmware with this change on my device.
Now the unknown chain id error doesn't happen!

But i get a different error - "Forbidden key path". I will try to look and see what change is needed to solve that.
related: https://github.com/trezor/trezor-firmware/issues/1327

### CODE REVIEW

**Comment by yuval-k** [comment]
update: `trezorctl set safety-checks prompt` gets rid of the forbidden key path error, and I can confirm the firmware after this change works

**Comment by matejcik** [comment]
the forbidden key path error, if you're using Ethereum derivation path, will be fixed with #1184

**Comment by yuval-k** [comment]
good to know @matejcik. then this is ready for review.

**Comment by matejcik** [comment]
xdai will instead be integrated in #1345

**Pull request closed without merging**
