### PR TITLE
Adds Sapphire support

### PR DESCRIPTION
**Pull request by decenomy**
We at Decenomy want to fully integrate all our coins with Trezor devices and software, this PR has all the changes needed to support our major coin Sapphire.

We tested these changes in a real device with the firmware built by us on our electrum wallet for Sapphire.

https://sappcoin.com/
https://github.com/sappcoin-com/SAPP
https://explorer.decenomy.net/SAPP/blocks

PS: Just two questions: how can we include Sapphire in the Trezor Suite? and, is possible to integrate with the C++ QT wallet?

Thanks in advance,
  Pedro Simões, Decenomy.

### CODE REVIEW

**Comment by pedro-at-decenomy** [comment]
Hi @prusnak and @matejcik, is everything OK with the review process? do we need to change something? Best regards.

**Comment by prusnak** [comment]
We are not accepting new coins to Trezor firmware unless the coin is in TOP30 on CoinMarketCap. Your coin does not fit this criteria.

**Comment by pedro-at-decenomy** [comment]
"We are not accepting new coins to Trezor firmware unless the coin is in TOP30 on CoinMarketCap"

TOP30 with or without tokens?

**Comment by prusnak** [comment]
I am talking about coins - tokens are different animals.

**Comment by pedro-at-decenomy** [comment]
@prusnak Thank you for your time.

**Comment by pedro-at-decenomy** [comment]
Hi @prusnak can this PR be reconsidered? From my understanding, you always have the right to reject the PR and I don't question that, but we are a Bitcoin-derived coin and by the published rules we don't need to be on CMC TOP30, right? Or, am I wrong?

https://wiki.trezor.io/Developers_guide:Contributing#Adding_a_new_coin sub-section Forks and derivatives: 
"If the coin you are adding is a fork of Bitcoin or other cryptocurrency we already support (in other words, new app is not needed) you can modify the definitions in the trezor-firmware repository and file a PR. In such case the coin does not have to be in TOP30 (see below), but we still reserve the right not to include the coin. The location depends on the type of the asset to be added:" 

Thanks in advance

**Comment by pedro-at-decenomy** [comment]
If yes, I will proceed with additional verifications and/or fixes to meet with the last firmware code.

**Pull request closed without merging**
