### PR TITLE
ci: public storage index upload fix

### PR DESCRIPTION
**Pull request by vdovhanych**
this is hopefully the last fix for uploading, last one was also broken as it was not uploading the index correctly

### CODE REVIEW

**Review by matejcik — APPROVED** [review]

**Comment by matejcik** [comment]
why are github actions not running here...?

**Comment by vdovhanych** [comment]
No idea but I think most likely it's due to the fact I pushed the already merged branch back to Github?

**Comment by vdovhanych** [comment]
force push with changed commit message did not help.

**Comment by matejcik** [comment]
Ah, it's a site-wide problem. I can't merge without the block-fixup check anyway so this will have to wait.

**Pull request merged**
