### PR TITLE
feat(core,rust): TR PIN dialogue going to ENTER when user enters 4th digit

### PR DESCRIPTION
**Pull request by grdddj**
Fixes https://github.com/trezor/trezor-firmware/issues/3025

As soon as the user enters the 4th PIN digit, it will bring him to the `ENTER` choice

### CODE REVIEW

**Comment by Hannsek** [comment]
Are we ok with this? As If user has 6 digits pin and someone listening to clicks, attacker will know the 5th number. @andrewkozlik

**Comment by andrewkozlik** [comment]
> If user has 6 digits pin and someone listening to clicks, attacker will know the 5th number.

I don't like that. But there is a much bigger problem. An attacker can determine the entire PIN with high probability just by listening to the correct PIN entry enough times. I didn't do the exact math, but we are talking something like ~20 times.

**Comment by Hannsek** [comment]
How come? We shuffle the position after every entry.

**Comment by Hannsek** [comment]
> As soon as the user enters the 4th PIN digit, it will bring him to the ENTER choice
Maybe if we shift it on 6th number, it would be enough as only few users would have pin longer then 6 digits imo.

**Comment by Hannsek** [comment]
Closing this in favour of https://github.com/trezor/trezor-firmware/issues/3061.

**Pull request closed without merging**
