### PR TITLE
convert chunk to bytes before logging it as hex

### PR DESCRIPTION
**Pull request by timthelion**
https://github.com/trezor/trezor-firmware/commit/9a330f34756c7f553c187d007ddce14eea73ca65#r38896929

### CODE REVIEW

**Comment by matejcik** [comment]
fixed instead in 59f43514be9c577393e316709dc10b111cdf5834

i'm wondering how you hit that particular codepath though? with trezor-agent and trezorlib 0.12, you should never be using the hid transport

**Comment by timthelion** [comment]
well most things were broken. for example `trezorctl list` gave that error.

**Comment by timthelion** [comment]
though I will admit that I later ran into other problems and ended up updating trezord. Now I think it is using webusb rather than whatever it was using before

**Comment by prusnak** [comment]
What is the version of `trezorctl` and `trezorlib`? How did you install them?

**Comment by timthelion** [comment]
@prusnak The latest versions. The bug is only 2 months old ;)

**Comment by prusnak** [comment]
And second part of my question: How did you install them?

**Comment by matejcik** [comment]
@prusnak there is (was) an actual bug with HID handling code.

The more interesting question is, how does one, in this day and age, get to run HID code paths with trezorlib 0.12.
Minimum supported fw version is still 1.8.0 which communicates via webusb. So @timthelion either edited their trezorlib to lower the requirement, or maybe has an old Trezor One connected and the enumeration is somehow hitting it even without connecting to it.

**Comment by timthelion** [comment]
I did have a very old firmware version. Now upgraded. Trezorctl was installed via pip3. Now everything is fine though.

**Pull request closed without merging**
