### PR TITLE
ci: add T3W1 builds

### PR DESCRIPTION
**Pull request by mmilata**
Just FW & emulator build, no integration tests yet. I believe this is needed by trezor-user-env.

### CODE REVIEW

**Review by grdddj — COMMENTED** [review]
Thanks for that! From `trezor-user-env` point, we need to:
- [x] upload the `T3W1` emulators to this URL - https://data.trezor.io/dev/firmware/emu-nightly/trezor-emu-core-T3W1-universal - I believe this is achieved by `core.yml` changes
- [ ] new release of `trezorlib` with `T3W1` support

**Comment by mmilata** [comment]
Thanks for the review! `trezorctl` release will be taken care of in different PR.

**Comment by grdddj** [comment]
Hello, sorry to bother after merging, but I found out that the `ARM` version emulator is not exported for the new model:
- this URL works for the `t3t1` model - https://data.trezor.io/dev/firmware/emu-nightly/trezor-emu-arm-core-T3T1-universal
- it is expected that the same modified link will be also for `t3w1` - https://data.trezor.io/dev/firmware/emu-nightly/trezor-emu-arm-core-T3W1-universal ... currently it gives 404

**Comment by mmilata** [comment]
That's because all ARM builds are currently failing for `main`. No idea if anybody is working on fixing that, but if it helps I can manually push some dummy emulators to data.trezor.io.

**Comment by vdovhanych** [comment]
So, it's some cross-compile issue?

**Comment by mmilata** [comment]
Looks more like native linker issue: https://github.com/trezor/trezor-firmware/actions/runs/11564251985/job/32189106102

**Comment by grdddj** [comment]
> That's because all ARM builds are currently failing for `main`. No idea if anybody is working on fixing that, but if it helps I can manually push some dummy emulators to data.trezor.io.

Pushing some dummy ARM would be helpful, so Suite can test it on MAC - doesn't matter if it is an older version

**Comment by Hannsek** [comment]
@cepetr almost has the fix. I'd wait for him.

**Comment by mmilata** [comment]
https://data.trezor.io/dev/firmware/emu-nightly/trezor-emu-arm-core-T3W1-universal now hosts the T3T1 ARM emulator, it will be overwritten automatically when the build is fixed. No btconly as I don't see it for the other models.

**Pull request merged**
