### PR TITLE
chore(vendor): update micropython to version with more precise memory profiling

### PR DESCRIPTION
**Pull request by mmilata**
Counterpart of trezor/micropython#4.

### CODE REVIEW

**Comment by CustodialPro** [comment]
MICHAEL STETZ has sent you an email via Gmail confidential mode:

[image: Gmail logo] <https://confidential-mail.google.com/msg/AF-DAF3mYTzwmTCuZIgOf3gOW3G1R1uTvr5U3bEw0us7Y8rkzkFVi1Vp6PoD5vERLo4YsyRQG_OJ1i0jOGsFvzO4c8tdxgRoOLa9rm8GWBexxhCmfVFygUaKufTaSV8evODcorkWOSJX-CGYhVGzjCLlk0t6mQiTlEIBbs5zZZ4gsW2JIdpx_Ybj2dfrHUpyljhyVZySq9vt729Uk7oY>

This message was sent on Dec 7, 2020 at 11:57:12 AM PST
You can open it by clicking the link below. This link will only work for reply@reply.github.com.

View the email <https://confidential-mail.google.com/msg/AF-DAF3mYTzwmTCuZIgOf3gOW3G1R1uTvr5U3bEw0us7Y8rkzkFVi1Vp6PoD5vERLo4YsyRQG_OJ1i0jOGsFvzO4c8tdxgRoOLa9rm8GWBexxhCmfVFygUaKufTaSV8evODcorkWOSJX-CGYhVGzjCLlk0t6mQiTlEIBbs5zZZ4gsW2JIdpx_Ybj2dfrHUpyljhyVZySq9vt729Uk7oY>

Gmail confidential mode gives you more control over the messages you send. The sender may have chosen to set an expiration time, disable printing or forwarding, or track access to this message. Learn more <https://support.google.com/mail/answer/7674059>
Gmail: Email by Google
Use is subject to the Google Privacy Policy <https://myaccount.google.com/privacypolicy?hl=en>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
You have received this message because someone sent you an email via Gmail confidential mode.
[image: Google logo]

**Comment by mmilata** [comment]
* html report: https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/895292333/artifacts/core/prof/memperf-html/index.html
* 3w old master: https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/849559347/artifacts/core/prof/memperf-html/index.html

**Comment by mmilata** [comment]
@CustodialPro looks like you tried to post a comment using gmail but it didn't work & we can't see it?

**Comment by prusnak** [comment]
It was a spam

**Review by prusnak — APPROVED** [review]

**Review by tsusanka — APPROVED** [review]

**Comment by tsusanka** [comment]
cc @jpochyla

**Pull request merged**
