### PR TITLE
ci: bump nixpkgs to latest nixpkgs-unstable + use poetry 1.4.0

### PR DESCRIPTION
**Pull request by prusnak**
- bumping nixpkgs alllows us to use poetry 1.4.0
- regenerate poetry.lock file (with `--no-update`)

Fixes https://github.com/trezor/trezor-firmware/issues/2805

### CODE REVIEW

**Comment by prusnak** [comment]
the build failures are really weird because the downloads of the same file end up with different hashes, see:
* https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/3958105335#L105
* https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/3958105334#L33

**Comment by prusnak** [comment]
ISTM the env in GitLab needs to be regenerated, otherwise the tests will fail?

**Comment by matejcik** [comment]
legacy fails because protobuf version in poetry does not match protoc version in the nix env.
upgrading protobuf package messes up nanopb in a way that is maybe fixable but maybe not ... my Christmas wish is to have a full-featured proto file parser in Python without the fragile code generator step :crying_cat_face: 

could we downgrade protoc easily?

**Comment by matejcik** [comment]
got a workaround in [b780936](https://github.com/trezor/trezor-firmware/pull/2890/commits/b7809366a8b1f8668b493fe21f3e3383dca0cdb1)

but for that matter, with the above nix env I have poetry 1.3.2, i thought this was supposed to be 1.4.0 ?

**Comment by matejcik** [comment]
3.19 is what we had before so let's go with that.
the workaround worked for me locally but it's still failing in CI so :woman_shrugging:

**Comment by mmilata** [comment]
Pinned to protobuf-3.19 in 41865a7, bumped to today's nixpkgs-unstable in 0e89c4f as it seems to contain poetry-1.4.0.

**Comment by mmilata** [comment]
Seems like poetry-side issue, perhaps clearing gitlab cache could help?

@vdovhanych can you please clear it and retrigger this branch? https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/pipelines

**Comment by matejcik** [comment]
we're left with:
https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/3974380500
```
In file included from /nix/store/1zsc48wwlplpkzms83m7zr94xnfalq2q-glibc-2.35-224-dev/include/string.h:535,
                 from cardano.c:25:
In function ‘memcpy’,
    inlined from ‘hdnode_from_secret_cardano’ at cardano.c:162:3:
/nix/store/1zsc48wwlplpkzms83m7zr94xnfalq2q-glibc-2.35-224-dev/include/bits/string_fortified.h:29:10: error: ‘__builtin_memcpy’ offset [0, 31] is out of the bounds [0, 0] [-Werror=array-bounds]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

and some weird btconly failures:
https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/3974380625
https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/3974380691
```
$ $NIX_SHELL --run "poetry run ./tools/check-bitcoin-only legacy/firmware/trezor.bin"
zUYPYNYZYXYbY`YgYlYiYxY
Wsjshspsxsus{szs
ERROR: Altcoin strings found in Bitcoin-only firmware.
```
not worried about matching some altcoins that will be gone very soon(tm)
but wtf are those strings??

**Comment by matejcik** [comment]
managed to reproduce it, it only manifests with `ADDRESS_SANTIZER=1`

wtf, this is the offending line: https://github.com/trezor/trezor-firmware/blob/master/crypto/cardano.c#L162
this works:
```
  memcpy(out->private_key_extension, secret, 32);
```
this works:
```
  memcpy(out->private_key, secret + 32, 32);
```
this doesn't:
```
  memcpy(out->private_key_extension, secret + 32, 32);
```
either there's miscompilation or the ASAN thing is getting confused, or I don't know
@onvej-sl or @hiviah any ideas? this might be in your purview

**Comment by prusnak** [comment]
Btw, I just noticed that pyright is already a part of nixpkgs, so we might want to drop our custom code.

**Comment by mmilata** [comment]
Hypothesis: ASan instrumentation confuses gcc's `array-bounds` analysis causing it to emit false positive. We can opt `hdnode_from_secret_cardano` out of ASan, not sure if it's possible the other way: https://github.com/google/sanitizers/wiki/AddressSanitizer#turning-off-instrumentation

Still might be worth investigating further in case it's a gcc bug.

**Comment by matejcik** [comment]
> We currently have `1.1.204`, nixpkgs has `1.1.298`.

we don't typecheck with that version. haven't looked into whether it's easily fixable or not

**Comment by grdddj** [comment]
> We used to require a very specific version of pyright while nixpkgs has _whatever's the latest on NPM_. Is it still the case or can we now use the latter? (cc @grdddj)
> 
> We currently have `1.1.204`, nixpkgs has `1.1.298`.

It would be nice to increase the version, it might bring some improvements (enable us to do less `type: ignores`, etc.)

So I think we can use the `1.1.298` - and as is mentioned above - we will not need our custom code specifying the version

**Comment by onvej-sl** [comment]
> either there's miscompilation or the ASAN thing is getting confused, or I don't know

You found a gcc bug!

This is a minimum working example:
```
gcc -fsanitize=undefined -Werror=array-bounds bug.c
```
```
#include <string.h>

#define LENGTH 17

typedef struct {
  char first[LENGTH];
  char second[LENGTH];
  char third[LENGTH];
} triple;

void bug(char in[3 * LENGTH], triple *out) {
  memcpy(out->first, in, LENGTH);
  memcpy(out->second, in + LENGTH, LENGTH);
  memcpy(out->third, in + 2 * LENGTH, LENGTH);
}
```

The gcc that is used to compile the tests is pulled by the `rustNightly` dependency in `shell.nix`. And this build of gcc seems to be buggy. So we can either
  * update `rustProfiles` (if it doesn't break anything) or
  * introduce `gcc` dependency and force the tests to use it.

**Comment by onvej-sl** [comment]
Updating `rustProfiles` doesn't seem to fix it. The same version of gcc (12.2.0) from `gcc` seems to be ok.

**Comment by mmilata** [comment]
Forced use of GCC 11 in d38d80c, seems to work now. @onvej-sl did you report this bug to GCC?

**Review by matejcik — APPROVED** [review]
ahhh, the new clippy with the unnecessary_cast lint :))

**Comment by onvej-sl** [comment]
> @onvej-sl did you report this bug to GCC?

No, I didn't.

**Pull request merged**
