### PR TITLE
feat(cardano): allow address_index in staking paths

### PR DESCRIPTION
**Pull request by davidmisiak**
Changes:
- Cardano multidelegation - allowing address index to be non-zero in staking paths (in line with [CIP-11](https://cips.cardano.org/cips/cip11/)).
- A little note that Cardano token decimals are unknown displayed when sending/minting tokens.

### CODE REVIEW

**Comment by davidmisiak** [comment]
Hi @matejcik, just wanted to ask whether you have an idea when could this PR be processed.

**Comment by davidmisiak** [comment]
@matejcik any updates please?

**Comment by matejcik** [comment]
code LGTM.
please also regenerate fixtures for model R (build the emulator with `TREZOR_MODEL=R`)

**Comment by davidmisiak** [comment]
All fixtures should be up to date; rebased on master.

**Comment by davidmisiak** [comment]
@matejcik is this ready to be merged?

**Comment by matejcik** [comment]
code-wise yes, but github has a problem (seems related to the master -> main rename)
please rebase manually on top of current main branch and force-push

**Comment by davidmisiak** [comment]
Rebased. There was also a conflict in `fixtures.json`, but it should be fixed now.

**Comment by matejcik** [comment]
waiting for CI

**Review by matejcik — APPROVED** [review]

**Pull request merged**
