### PR TITLE
Do not send ButtonRequests for paging events

### PR DESCRIPTION
**Pull request by matejcik**
partial revert of 54db2291f2335585fc14c0c5317353527fb2f452 from #1671, and adapting the test suite to cope.

Should fix https://github.com/trezor/trezor-suite/issues/3990 and remove most potential compatibility headaches.

We want this to go to the 2.4.1 release branch.

### CODE REVIEW

**Comment by matejcik** [comment]
no changelog as the change goes directly to the generated `CHANGELOG.md`

**Review by tsusanka — APPROVED** [review]
Quick LGTM but I did not review #1671 so @mmilata should definitely have a look :)

**Review by mmilata — APPROVED** [review]
Changes look straightforward, however [test_msg_signtx_replacement.py::test_p2wpkh_in_p2sh_fee_bump_from_external](https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/1412673532) needs fixing.

**Comment by matejcik** [comment]
test fixed, all ready.
leaving merging to you @mmilata so that you can also cherry-pick to the release branch

**Pull request merged**
