### PR TITLE
Use pitrezor with other boards

### PR DESCRIPTION
**Pull request by mathewriver**
Is there a way to get pitrezor to work with other boards, such as orange pi and banana pi?
I'm also wondering about ESP32 (not much of a hardware, but I'd like to ask about it anyway) and some generic chinese handheld consoles (the ones with enough hardware to run even Dreamcast games)., those sold on websites like AliExpress.

### CODE REVIEW

**Comment by matejcik** [comment]
You seem to have made a pull request to the official Trezor repository, instead of opening an issue / discussion in the pitrezor repository. Please correct your mistake .)

**Comment by mathewriver** [comment]
https://www.pitrezor.com/2018/02/pitrezor-homemade-trezor-bitcoin-wallet.html

image

**Comment by mathewriver** [comment]
When I click New Pull Request from the author's page here on github https://github.com/heneault/trezor-firmware/pulls, I get redirected to https://github.com/trezor/trezor-firmware/compare/master...heneault:trezor-firmware:pitrezor

**Comment by matejcik** [comment]
That would do it, yes. But you're not supposed to be making a pull request in the first place.

**Pull request closed without merging**
