### PR TITLE
Seed recovery for model R

### PR DESCRIPTION
**Pull request by grdddj**
Connected with https://github.com/trezor/trezor-firmware/issues/2265:
- allowing for seed recovery - `BIP39` only so far

How to try locally:
- `TREZOR_MODEL=R make build_unix`
- `./emu.py -ea`
- `trezorctl device recover` - starting recovery process

image
image
image
image
image

### CODE REVIEW

**Comment by sime** [comment]
@grdddj I attempt to enter the seed word 'day' and I get a FATAL error.
```
1653038217268704 trezor.wire DEBUG 0:0 expect: ()

FATAL ERROR:
expr:
msg : rs
file: :0
func:
rev : ba4037b251
Hint:
Isn't the emulator already running?
SHUTDOWN
```

**Comment by sime** [comment]
Same for the word 'tissue'.

**Comment by sime** [comment]
Trying to load this firmware fails too. P_20220520_120729

**Comment by grdddj** [comment]
> @grdddj I attempt to enter the seed word 'day' and I get a FATAL error.
> Same for the word 'tissue'.

Thanks for the report, this was actually affecting a lot of words - when we were switching from "more-than-10-possible-words" to "only-one-possible-word" with adding a single character.

Should be fixed in [250ca14](https://github.com/trezor/trezor-firmware/pull/2268/commits/250ca14e6dcf8f2c7f92d87672b861e350c11274)

**Comment by sime** [comment]
@grdddj Can we tackle the on device error?

**Comment by grdddj** [comment]
> @grdddj Can we tackle the on device error?

Not sure how to fix this `secp256` issue. There was some recent `master` commit from @onvej-sl - https://github.com/trezor/trezor-firmware/commit/db0da196a802ff434d5f972f98be6524c323ead1 - that was updating the version.

On my local machine, I remember seeing something with `secp256` in my unstaged changes after rebasing on `master`. Could you please look at `git status`, and if you will see something there, just get rid of those things?

**Comment by onvej-sl** [comment]
This is because the value of `SECP256K1_CONTEXT_SIZE` is not correctly set in the build process. I'm looking at it and I will fix it.

**Comment by sime** [comment]
Thanks @onvej-sl 

Also happens on Model T. 
P_20220520_152645

**Comment by onvej-sl** [comment]
I fixed it with https://github.com/trezor/trezor-firmware/pull/2280. Thank you for reporting it. Rebasing this branch on the current master should fix the issue.

**Comment by sime** [comment]
@grdddj Could you rebase please?

**Comment by grdddj** [comment]
> @grdddj Could you rebase please?

Sure, rebased and force-pushed all the `trezor_r_*` branches, so they can be built and they follow each other well in PRs

**Comment by sime** [comment]
On the hardware I see this screen right after booting.
P_20220523_122235

**Comment by grdddj** [comment]
> 



> @grdddj I'm getting Firmware error after launching `device recover`.
> 
> ```
> NotImplementedError:
> 1653301243907018 trezor.workflow DEBUG default closed: <generator object 'recovery_homescreen' at 145e639e0>
> 1653301243907032 trezor.loop DEBUG spawn new task: <generator object 'recovery_homescreen' at 145e669a0>
> 1653301243907046 trezor.workflow DEBUG start default: <generator object 'recovery_homescreen' at 145e669a0>
> 1653301243907211 trezor.loop ERROR exception:
> Traceback (most recent call last):
>   File "trezor/loop.py", line 186, in _step
>   File "apps/management/recovery_device/homescreen.py", line 27, in recovery_homescreen
>   File "apps/management/recovery_device/homescreen.py", line 33, in recovery_process
>   File "apps/management/recovery_device/homescreen.py", line 63, in _continue_recovery_process
>   File "apps/management/recovery_device/homescreen.py", line 153, in _request_word_count
>   File "apps/management/recovery_device/layout.py", line 151, in homescreen_dialog
>   File "trezor/ui/layouts/tr/recovery.py", line 40, in continue_recovery
> ```

I think you have a different branch, because in my current version of `grdddj/trezor_r_seed_recovery` the `"trezor/ui/layouts/tr/recovery.py", line 40` is not in  `continue_recovery` function. In mu current state, it starts at line `76` and is already implemented

**Comment by matejcik** [comment]
will be merged with #2277

**Pull request closed without merging**
