### PR TITLE
chore: update trezor_tests binary

### PR DESCRIPTION
**Pull request by ph4r05**
Improved Monero-Trezor test suite as occasionally passphrase-related bug reports have surfaced.

Tests revamp, always use passphrase flow with transaction signing, more passphrase-related tests, pin test, invalid passphrase test. Chain generation optimized. 

Using release: https://github.com/ph4r05/monero/releases/tag/v0.18.1.1-dev-tests-u18.04-02
Related to this PR: https://github.com/monero-project/monero/pull/8752

### CODE REVIEW

**Review by matejcik — APPROVED** [review]

**Comment by matejcik** [comment]
you marked this as draft, any reason not to merge?

**Comment by ph4r05** [comment]
Thanks for approval @matejcik! I've just noticed there is an issue I need to investigate with passphrase tests. Will ping you once this is done, thanks!

**Comment by ph4r05** [comment]
@matejcik I had to implement few fixes, can you pls try it now? Thanks!

**Comment by ph4r05** [comment]
btw should I add a changelog to this PR? Is it relevant?

**Pull request merged**
