### PR TITLE
keyctl-proxy fixes

### PR DESCRIPTION
**Pull request by prusnak**
* don't use format strings in keyctl-proxy
* fix typo in keyctl-proxy help
* rename fw_or_type to image_type in keyctl-proxy to avoid confusion

### CODE REVIEW

**Comment by matejcik** [comment]
huh, so with this change keyctl proxy still works on 3.5? despite trezorlib being gradually upgraded to 3.6 ?

**Comment by prusnak** [comment]
> huh, so with this change keyctl proxy still works on 3.5? despite trezorlib being gradually upgraded to 3.6 ?

Didn't go as far as to check this :-/

**Comment by matejcik** [comment]
i guess it should be usable with an older version of trezorlib in any case

**Comment by prusnak** [comment]
> i guess it should be usable with an older version of trezorlib in any case

What's the latest version of trezorlib that works with Python 3.5 ?

**Comment by matejcik** [comment]
the currently released 0.12.2 works with py3.5
it's only 0.13 in master that broke compatibility

**Comment by matejcik** [comment]
#810

**Comment by prusnak** [comment]
That's great news, thanks!

**Review by matejcik — APPROVED** [review]

**Pull request merged**
