### PR TITLE
fix(python): add default value to protobuf.Field

### PR DESCRIPTION
**Pull request by grdddj**
Connected with https://github.com/trezor/trezor-firmware/issues/2527:
- add missing default value into creation of `protobuf.Field` in `python/src/trezorlib/messages.py`

There were two possible ways how to include the `default` kwarg :
1. when `field.default_value is not None`, as `None` is the "default-default" value
2. when `not field.required` - for all fields that do not enforce a value to be set

In the end, I chose `#2`, so seeing `default=...` is another sign that the field is not required.

> (Somewhat related, the Rust protobuf descriptors [wrongly decode](https://github.com/trezor/trezor-firmware/blob/master/common/protob/pb2py#L641) default=true as false)

I did not look into this, how can I replicate the issue?

### CODE REVIEW

**Comment by matejcik** [comment]
> I did not look into this, how can I replicate the issue?

i believe https://github.com/trezor/trezor-firmware/pull/2507/commits/bd1324384ca533e4080409d9f9db2e9f8a1424ef is fixing that part

**Comment by grdddj** [comment]
Unexpectedly, `legacy device tests` have failed because of the change, with couple `NEM` UI tests failing with [one extra screen](https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/3231519415/artifacts/test_ui_report/failed/T1_nem-test_signtx_transfers.py::test_nem_signtx_multiple_mosaics.html).

The reason was that `NEMTransfer::payload` had the default value of `b""`, and `Unencrypted message` layout was shown even in this case (`if (transfer->has_payload)`).

Fixed in [c2515bd](https://github.com/trezor/trezor-firmware/pull/2586/commits/c2515bd15db24be88761b5bbc3c16f6a6e703adf) by removing the explicit default from `messages-nem.proto`, which made `None` the default.

**Comment by matejcik** [comment]
the NEM change should be a separate commit, otherwise LGTM and please get this ready to merge

**Comment by matejcik** [comment]
there is still (or again?) a conflict

**Comment by grdddj** [comment]
> there is still (or again?) a conflict

Yeah, `Coinjoin` previously, `Cardano` now. Resolved and force-pushed

**Pull request merged**
