### PR TITLE
fix(python): use unified descriptor format <a;b>

### PR DESCRIPTION
**Pull request by prusnak**
use unified descriptor format introduced in https://github.com/bitcoin/bitcoin/pull/22838

### CODE REVIEW

**Comment by matejcik** [comment]
please add changelog entry. in `python/` directory, `towncrier create 1885.changed --edit`

**Comment by prusnak** [comment]
> please add changelog entry. in `python/` directory, `towncrier create 1885.changed --edit`

This is just a fixup to (not yet relased) `python/.changelog.d/1710.added`, so I prefer not to add another changelog entry.

**Comment by prusnak** [comment]
> please add changelog entry.

Added in 5dc60b35db39e2a4a08141848f91accfcc20d30b

**Review by matejcik — APPROVED** [review]

**Comment by matejcik** [comment]
you need to re-run UI tests because the testcase identifiers have changed.

**Comment by prusnak** [comment]
Review addressed in a86eb3a924597aaea18518271fcb4eb0800aa496

**Comment by matejcik** [comment]
:+1: please squash the fixup and merge

**Pull request merged**
