### PR TITLE
common/defs/fido: add gemini webauthn

### PR DESCRIPTION
**Pull request by mcudev**
this makes the fido security key functionality on the model t for gemini.com more complete by showing the gemini logo.

currently, the relevant `publicKeyCredentialCreationOptions` from gemini.com are:
`"rp":{"name":"Gemini Trust Company, LLC","id":"gemini.com"},`
`"pubKeyCredParams":[{"alg":-7,"type":"public-key"},{"alg":-257,"type":"public-key"}],`
`"authenticatorSelection":{"requireResidentKey":false,"userVerification":"preferred"},`
`"attestation":"none",`
`"extensions":{}`

i looked at the people associated with @gemini and was wondering if maybe we can get a test, review, and/or approval on this from @hansenlin too

### CODE REVIEW

**Review by andrewkozlik — APPROVED** [review]
ACK. Tested on T1 device and TT emulator.

**Review by matejcik — APPROVED** [review]
utACK

**Comment by mcudev** [comment]
@andrewkozlik First, thanks for testing. I tested on a TT device too. Second, I'm wondering how you were able to test FIDO2 on the TT emulator? I've been trying and haven't found a way with `trezorctl`, or the Chrome browser (both with and without the bridge running). I don't think the bridge is necessary because Chrome uses the USB HID device (at least with the physical device plugged in). There must be a step that registers the emulator with the host machine or the browser that I'm missing. Thanks!

**Comment by andrewkozlik** [comment]
> Second, I'm wondering how you were able to test FIDO2 on the TT emulator?

You need to have `hid-bridge` running along with the emulator: https://github.com/trezor/trezor-firmware/tree/master/core/tools/hid-bridge.

**Comment by mcudev** [comment]
@andrewkozlik The hid-bridge is so cool and just what I needed, thanks!

notes to people that may want to use the Trezor T emulator to test FIDO2 in the future:

1. my emulator used `TREZOR_FIDO2_UDP_PORT=21326` so i had to run `hid-bridge -e 21326`.
1. In the Chrome browser, `chrome://device-log/` was useful for watching FIDO events.
1. For a quick test on the emulator, in Chrome, go to gemini.com (or whatever site you want to test -- be sure to modify the domain in the code below) and open the developer tools, then on the console tab run:
```
navigator.credentials.create({
  publicKey: {
  "rp": {
    "name": "Gemini Trust Company, LLC",
    "id": "gemini.com"
  },
  user: {
    id: new Uint8Array([1]),
    name: "user@email.test",
    displayName: "whatever"
  },
  challenge: new Uint8Array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]),
  "pubKeyCredParams": [{"alg": -7, "type": "public-key"}, {"alg": -257, "type": "public-key"}],
  "authenticatorSelection": {"requireResidentKey": false, "userVerification": "preferred"},
  "attestation": "none",
  "extensions":{}
}
});
```

**Comment by andrewkozlik** [comment]
@mcudev thanks for this PR and for the usage notes. I didn't know `chrome://device-log/` showed such excellent logs!
 
The FIDO2 UDP port is 21326 for the debug emulator `./emu.py` and 21325 for the production emulator `./emu.py -d`. It's an annoyance that I have been unhappy about for a while, so I just created a PR to unify the port numbers: https://github.com/trezor/trezor-firmware/pull/1418.

**Pull request merged**
