### PR TITLE
Add blockchain_link field to coin definitions

### PR DESCRIPTION
**Pull request by szymonlesisz**

### CODE REVIEW

**Comment by prusnak** [comment]
Why do you want to duplicate all the blockbook fields?

**Comment by matejcik** [comment]
we want to move to a new data structure, but some users are still using the old ones (classic wallet iirc?)

perhaps we could (finally) drop `bitcore` and `blockbook` fields, and generate them with cointool when exporting the data

**Comment by prusnak** [comment]
Let's discuss that shortly IRL altogether

**Comment by szymonlesisz** [comment]
Closing this in favour of #404
As discussed IRL, For BTC-like and Ethereum-like "blockchain_link" field will be dynamically transformed from "blockbook" field, form "misc" coins "blockchain_link" remains as it was

**Pull request closed without merging**
