### PR TITLE
Update zcash branch id for the upcoming Heartwood fork

### PR DESCRIPTION
**Pull request by tsusanka**
Source: https://zips.z.cash/zip-0250

I am still unsure whether this affects Komodo/Koto as well but since these coins are used rarely I do not want to devote more time into this.

### CODE REVIEW

**Comment by matejcik** [comment]
we aren't using the values of these fields. this needs review from @szymonlesisz

**Comment by tsusanka** [comment]
Also cc @mroz22

**Comment by prusnak** [comment]
For reference:
* suite value will be updated in https://github.com/trezor/trezor-suite/pull/2072
* mytrezor value will be updated via trezor.js in https://github.com/trezor/trezor.js/commit/5f626a123c66a2b03c62b677e5d4d78572270609

At this point I am questioning whether the value from trezor-common is used anywhere (it seems that it's not used in firmware, suite, nor mytrezor). Or am I wrong?

**Comment by mroz22** [comment]
Sticks observations are right. We don't use it properly and need some architectural redesign/clean up. Idea of having single source of thruth seems ok to me, still there are few questions:
- which layer of the frontend stack should provide default (via trezor-common)? (probably connect)? 
- should the topmost layer provide option to override default in case user needs to do something special?

**Comment by tsusanka** [comment]
Ok, @mroz22 this is probably not the place to discuss this, should I merge these changes then and you will discuss it in the Suite team at some point?

**Comment by mroz22** [comment]
yes!

**Pull request merged**
