### PR TITLE
feat(core/mercury): use less severe icon color

### PR DESCRIPTION
**Pull request by obrusvit**
Not using danger color during onboarding.

image

cc @Hannsek , @lapohoda

### CODE REVIEW

**Comment by Hannsek** [comment]
Perfect, thank you!

**Comment by Hannsek** [comment]
One thought, @lapohoda, won't we use the white colour here?

**Review by mmilata — APPROVED** [review]

**Review by Hannsek — APPROVED** [review]

**Comment by obrusvit** [comment]
Cov report seemed to fail after re-running jobs, ignoring.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.9.0 (dea394b61290428b18d191b05391a5b365b6fa8b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.9.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 4ac28e60f639db05abf286efa832df92a67f5ff2)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
