### PR TITLE
Add Connect support indicator for Ritocoin

### PR DESCRIPTION
**Pull request by Scotty0448**

### CODE REVIEW

**Comment by prusnak** [comment]
Do you plan to develop a wallet that uses Trezor Connect or why do you want this added?

**Comment by Scotty0448** [comment]
Yes, the wallet is already in development.

**Comment by prusnak** [comment]
Okay, we'll merge these changes once your wallet is ready. Please reopen once you have something to show.

**Comment by Scotty0448** [comment]
The wallet software is ready now. It's a Trezor-only wallet. It's currently deployed for another coin (FLO) at https://wallet.chaintek.net. It's my understanding that this PR is needed to get Ritocoin details pulled into Trezor Connect so the wallet can work for that coin as well.

**Pull request closed without merging**
