### PR TITLE
core/seed: Add SLIP-0077 derivation to Keychain

### PR DESCRIPTION
**Pull request by romanz**
Following #66 and #317, it would allow [deriving confidential addresses](https://github.com/romanz/trezor-firmware/blob/a9ec7775b4fe01a0ab6814970f3ba1189dffa002/core/src/apps/wallet/get_address.py#L28) and
[unblinding confidential transactions' outputs](https://github.com/romanz/trezor-firmware/blob/a9ec7775b4fe01a0ab6814970f3ba1189dffa002/core/src/apps/liquid/unblind_output.py#L19) (according to [SLIP-0077](https://github.com/satoshilabs/slips/blob/master/slip-0077.md)).

### CODE REVIEW

**Comment by prusnak** [comment]
@romanz is there a strong reason why to introduce Slip77 class? If not, it might be more consistent with the rest to just introduce two new `Keychain` methods:

* `derive_slip77_blinding_private_key`
* `derive_slip77_blinding_public_key`

What do you think?

**Comment by romanz** [comment]
> is there a strong reason why to introduce Slip77 class?

Not really :)
Fixed and force-pushed

**Comment by prusnak** [comment]
Thanks

**Comment by matejcik** [comment]
Heads-up: i'm removing the slip0077 methods from the `Keychain` class in #959. ISTM that instead of methods of Keychain, these should be helper functions of the Elements signer, as they are only using the public `derive()` method.

**Comment by romanz** [comment]
Sound good, thanks for the update!

**Pull request merged**
