### PR TITLE
Merge 21.12 release branch

### PR DESCRIPTION
**Pull request by mmilata**
We want a merge commit (see #1812) so someone will have to push this manually or override the linear-history setting.

### CODE REVIEW

**Comment by prusnak** [comment]
The conflicts need to be addressed first

**Comment by matejcik** [comment]
the conflicts are mentioned but the merge commit seems to fix them

**Review by matejcik — APPROVED** [review]

**Comment by prusnak** [comment]
Ok,  merged manually via CLI.

The GitHub UI was confused ...

**Comment by mmilata** [comment]
I botched the merge commit and added some wrong fixtures, please review fix: #2002

**Pull request merged**
