### PR TITLE
Translations fixes/shortenings

### PR DESCRIPTION
**Pull request by grdddj**
Translations fixes before beta release - @Hannsek

### CODE REVIEW

**Comment by grdddj** [comment]
> What about fixtures?

I am recording them from CI, as running all the various tests locally is a nightmare.

Are there some more changes we want to do here?

**Comment by Hannsek** [comment]
@matejcik is it ready to merge and low hanging? If not, let's put it into the next release

**Comment by matejcik** [comment]
it's just this one commit and the only thing needed is to run UI tests and check that it didn't break anything

**Comment by grdddj** [comment]
> it's just this one commit and the only thing needed is to run UI tests and check that it didn't break anything

I have included the commit here, with `make gen` fixup and with one fix for `description_param` - commit [69743d1](https://github.com/trezor/trezor-firmware/pull/3552/commits/69743d189126f81e3cf0b19d6d823b5330878bdd) -  was broken here - 
image

**Review by matejcik — APPROVED** [review]

**Pull request merged**
