### PR TITLE
Rust UI: Keyboards

### PR DESCRIPTION
**Pull request by jpochyla**

### CODE REVIEW

**Review by matejcik — APPROVED** [review]
LGTM, to be merged after #2109 which brings the new Rust we need

**Review by mmilata — COMMENTED** [review]
Overall this looks great but is not working:
* in `PassphraseKeyboard` the character cycling doesn't seem to work,
* `Bip39` draws single button covering whole screen.

But these are probably some small bugs which I can iron out later as part of making this look like the new design.

Question: we're adding new timer for each key press, and have capacity for 4 timers. Can the user crash the firmware by typing really fast?

**Comment by jpochyla** [comment]
The timers are drained after the event pass, so the capacity is for max timers per event pass, which will most probably be constant in all cases.

**Comment by matejcik** [comment]
```
error: manual `!RangeInclusive::contains` implementation
```
whoa :)

**Pull request merged**
