### PR TITLE
Add Bitcoin 2 Support

### PR DESCRIPTION
**Pull request by Hiromono**

### CODE REVIEW

**Comment by prusnak** [comment]
Which Bitcoin2 wallet will integrate Trezor support?

**Comment by Hiromono** [comment]
Bitcoin 2 and Bitcoin address formats are the same and one's private key works for the other chain too so perhaps your existing wallet could handle it? Only Bitcoin's Bech32 address format is not supported. Not much developer documentation for Trezor. Will be creating our version of a Secure Masternode Tool and/or fork Electrum if needed.

**Comment by prusnak** [comment]
OK, once you have clear answer what wallet will integrate Trezor then we will merge.

**Comment by Hiromono** [comment]
Alright, will be creating our version of a Secure Masternode Tool that will integrate Trezor.

**Comment by prusnak** [comment]
Okay, please ping us when this is ready to test.

**Comment by prusnak** [comment]
Reopen when you have wallet ready to test.

**Pull request closed without merging**
