### PR TITLE
Don't show WebUSB popup in firmware, in bootloader only if no firmware present

### LINKED ISSUE #841: Show USB Chrome pop up dialog only if no firmware is present
This was brought up by @matejzak and the Suite team again.

Screenshot from 2020-02-11 15-36-37

------

We went back and forth on the Chrome pop up dialog. Removing it at some point and adding it back later because of phishing concerns if I remember correctly.

Many users find this annoying. Also with the introduction of Suite it does not make any sense anymore, does it?

I suggest to remove the pop up completely or we could show it only if the device is new (= no firmware installed) to simplify the onboarding and downloading of Suite.

### PR DESCRIPTION
**Pull request by prusnak**
Fixes #841

### CODE REVIEW

**Comment by prusnak** [comment]
There seems to be a lot of code added into the legacy, but actually this adds a very little to the final binary image.

**Comment by prusnak** [comment]
The relevant changes are also present in the bootloader. We need to provide devices with an altered bootloader.

**Comment by tsusanka** [comment]
We have agreed I will test this myself. I can confirm this works:

- The popup IS shown in case the device is in bootloader mode and firmware is missing.
- The popup IS NOT shown once the device loads up (aka in firmware).
- The popup IS NOT shown in case the device is in bootloader mode and firmware is present.

**Comment by tsusanka** [comment]
Once @hiviah reviews this and the CI passes, this is ready to go.

**Pull request merged**
