### PR TITLE
fix(core): restore ellipsis functionality on TR

### PR DESCRIPTION
**Pull request by matejcik**
#4121 broke a little thing that Rust's unused variable detection told me about

for passphrase, this PR restores to pre-4121 state
the PIN confuses me a little, it might be more broken than what this single change affected?

### CODE REVIEW

**Comment by Hannsek** [comment]
I cannot see any diffs. Is it expected?

**Comment by Hannsek** [comment]
So the only change is for T3B1 in passphrase entry?

**Review by TychoVrahe — APPROVED** [review]
Ack.

The pin input is also affected, but a bit differently, it doesn't show the dots it just limits number of characters rendered. The difference is that `PinEntry` uses this `ChangingText` with `without_ellipsis` called. 

The `translations` fixtures need updating too probably.

**Comment by obrusvit** [comment]
This can be abandoned in favor of https://github.com/trezor/trezor-firmware/pull/4328

**Comment by bieleluk** [comment]
The fix has already been merged to `main` as part of the global layout implementation:
https://github.com/trezor/trezor-firmware/blob/main/core/embed/rust/src/ui/model_tr/component/changing_text.rs#L147

**Pull request closed without merging**
