### PR TITLE
Add initial support for Hedera

### PR DESCRIPTION
**Pull request by mehcode**
Support for three kinds of transactions are implemented for now. Creating a new account, sending hbar (currency), and confirming your account ID.

No tests are added at this time. I'd like to have an initial review and some direction on how and where to add tests if needed.

Please let me know if there are any questions or concerns with the implementation.

---

A wallet that supports Hedera + Trezor will be made available at http://github.com/hashgraph/myhbarwallet at a later date.

---

Companion PR for trezor-connect: https://github.com/trezor/connect/pull/449

### CODE REVIEW

**Comment by prusnak** [comment]
This coin does not seem relevant enough for addition.

**Comment by kenthejr** [comment]
@prusnak Hedera is going into "Open Access" on September 16th, which is when exchanges can start creating accounts for users.

At the same time, there are already thousands of users (15,229 users to be precise: https://hash-hash.info/new) who hold hbars and want to secure their accounts with hardware wallets. We've commissioned @mehcode to build the Trezor integration.

FWIW, I am the Chief Developer Advocate for Hedera and would be happy to answer any questions.

**Comment by prusnak** [comment]
Please reopen once your coin is in TOP 30 on Coinmarketcap.

**Comment by kenthejr** [comment]
@prusnak do you mind if I email you on your listed github email? I have additional information that I think will change the discussion a bit. If we just look that funds raised so far and total supply, we more than meet your requirement, but as you know, CoinMarketCap isn't going to list until hbars have been on exchanges for a bit and I think the opportunity to have a reputable hardware wallet on board before then is strong. I just don't want to use github for that conversation.

**Comment by prusnak** [comment]
There is no need to discuss. You might approach us again when your coin is relevant. At the moment it is not.

**Pull request closed without merging**
