### PR TITLE
python: Allow overriding some Trezor specific things

### PR DESCRIPTION
**Pull request by achow101**
When working with Trezor clones, it is useful to use trezorlib over their forks of the library. As such, we need to be able to specify alternative vendors, minimum firmware versions, and alternative message classes to use for those devices. This PR adds attributes to `TrezorClient` that allow a caller to override those things.

Specifically, `msg_type_to_class_override` is a map of wire types to message classes. When decoding a message, the wire type is looked up in this message first before falling back to the default Trezor messages. `vendors` is added for the vendors check. This defaults to the `VENDORS` tuple, but can be overridden with another tuple by the caller. Lastly `minimum_versions` replaces `MINIMUM_FIRMWARE_VERSION` in the `is_outdated` check. This defaults to `MINIMUM_FIRMWARE_VERSION` but can be overridden by the caller.

### CODE REVIEW

**Review by prusnak — APPROVED** [review]
utACK

**Comment by matejcik** [comment]
re supported vendors, minimum fw versions, also USB IDs in #1448, i would move in a slightly different direction: introduce something like a "DeviceModelDescriptor" that has a name, USB ID, vendor, and minimum FW version. This would be part of `transport` and the client could query things it cares about -- and `enumerate()` would get a list of these descriptors to know which things to recognize.

i'll try to implement this probably tomorrow; it is also practical for trezorlib internally, as it allows us to handle T1 vs TT split more nicely

re message overrides: wondering why you think this is a better solution than inserting the overrides into `mapping` directly? ISTM for HWI's usage that would be sufficient?

**Comment by achow101** [comment]
> i'll try to implement this probably tomorrow; it is also practical for trezorlib internally, as it allows us to handle T1 vs TT split more nicely

Sounds good.

> re message overrides: wondering why you think this is a better solution than inserting the overrides into `mapping` directly? ISTM for HWI's usage that would be sufficient?

Since `mapping` is global, inserting into it directly causes the message to change globally. It's problematic for enumerate which needs to communicate with all devices that are plugged in. So if both a Trezor and Keepkey are plugged in, it can end up overwriting the mapping with the Keepkey message before a Trezor is being enumerated which then causes Trezor enumeration to fail. Having specific overrides within the `TrezorClient` itself lets us have the overrides be contained within the scope that actually needs them.

**Comment by matejcik** [comment]
@achow101 would you mind looking at the current state of hwi-compat branch https://github.com/trezor/trezor-firmware/compare/hwi-compat, in particular commits 9caa6671b070227d519796f01e27e701668f5c12 and cab4ca9a0aa8f616890d3570884609091b8ef301, and see if this works for your usecase?

**Comment by matejcik** [comment]
closing in favor of #1967

**Pull request closed without merging**
