### PR TITLE
fix(core): add missing semicolon into the passphrase choice for TS3

### PR DESCRIPTION
**Pull request by grdddj**
Fixes https://github.com/trezor/trezor-firmware/issues/3476:
- adds semicolon character as a passphrase choice

TODO:
- record the changed UI tests (if any)
- consider whether to add a changelog entry

### CODE REVIEW

**Comment by prusnak** [comment]
What is the sort order of the special characters? Is it the same as on Trezor Model T?

**Comment by grdddj** [comment]
> What is the sort order of the special characters? Is it the same as on Trezor Model T?

Yeah, the order should be the same - I have somehow omitted the semicolon for TS3 in the past:

https://github.com/trezor/trezor-firmware/blob/c09f9e88e207c531d73850a04220a2837b17ae65/core/embed/rust/src/ui/model_tt/component/keyboard/passphrase.rs#L39

https://github.com/trezor/trezor-firmware/blob/c09f9e88e207c531d73850a04220a2837b17ae65/core/embed/rust/src/ui/model_tr/component/input_methods/passphrase.rs#L34

No idea from where the order came from, seems historical reasons

**Comment by Hannsek** [comment]
@prusnak do you have some position change in your mind?

**Comment by prusnak** [comment]
> @prusnak do you have some position change in your mind?

No. I was just curious.

**Review by Hannsek — APPROVED** [review]

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.1.1 (c4cf80383d5f554ff118ba507b743074e73216d4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.5 regular (revision 988ba0b74c8da9d4a720d88b7450862fdf818834)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
