### PR TITLE
T2B1 vertical centering

### PR DESCRIPTION
**Pull request by grdddj**
Fixes https://github.com/trezor/trezor-firmware/issues/3225:
- vertically centering some screens

### CODE REVIEW

**Comment by Hannsek** [comment]
I don't think that helped :/. 🤷🏻
image

image
image
image

**Comment by Hannsek** [comment]
I don't think that helped everywhere
image

But somewhere yes! 
image

**Comment by Hannsek** [comment]
I'd merge it and iterate on it more.

**Comment by grdddj** [comment]
> I'd merge it and iterate on it further later.

Force-pushed with recorded fixtures, can be approved and merged

**Review by mmilata — APPROVED** [review]
Looking good!

**Pull request merged**
