### PR TITLE
fix(core): fix the chunkification of longer Cardano addresses in send flow

### PR DESCRIPTION
**Pull request by grdddj**
Fixes https://github.com/trezor/trezor-firmware/issues/3403:
- decrease the horizontal space in chunkified view when there is a scrollbar on the right

image

Diff: https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/5576547749/artifacts/test_ui_report/differing_screens.html

### CODE REVIEW

**Comment by Hannsek** [comment]
So the horizontal space is the same as in receive flow now?

**Comment by grdddj** [comment]
> So the horizontal space is the same as in receive flow now?

Yes, they share the same chunkified properties

**Review by mmilata — APPROVED** [review]
LGTM

**Comment by Hannsek** [comment]
@grdddj I oversaw one mistake. In cardano send flow we currently display 5 rows instead od 4 as with any other coins. Suite team is not happy because of that. Can we please fix it? 🙏🏻

**Comment by grdddj** [comment]
> @grdddj I oversaw one mistake. In cardano send flow we currently display 5 rows instead od 4 as with any other coins. Suite team is not happy because of that. Can we please fix it? 🙏🏻

Right, done in https://github.com/trezor/trezor-firmware/pull/3413

**Comment by bosomt** [comment]
**QA OK**

checked via
https://connect.trezor.io/9/#/method/cardanoGetAddress

**Pull request merged**
