### PR TITLE
prodtest for T2B1

### LINKED ISSUE #2756: Prodtest for T2B1
Current `prodtest` binary is not adjusted for T2B1 - remove touch, sd card, add buttons etc.

### LINKED ISSUE #2885: Add trezor color into device during assembling (T2B1)
We need to differentiate colors of produced device. We need to add a color flag somewhere during production.
 
One way that comes to mind is to use OTP memory which would be programmed dur8ng device testing

### PR DESCRIPTION
**Pull request by TychoVrahe**
closes #2756 
closes #2885 

builds on https://github.com/trezor/trezor-firmware/pull/2961

### CODE REVIEW

**Comment by TychoVrahe** [comment]
i will rebase and fix this after #2961 gets merged

**Comment by TychoVrahe** [comment]
rebased.

**Review by mmilata — COMMENTED** [review]
Can't be built due to missing vendorheader, is that expected? Untested but otherwise looks good.

**Comment by TychoVrahe** [comment]
Yeah we don't have keys for TR prodtest vendor header yet.

**Review by mmilata — APPROVED** [review]

**Pull request merged**
