### PR TITLE
Add Monacoin testnet support

### PR DESCRIPTION
**Pull request by wakiyamap**
I added a Monacoin testnet because I want to use it for testing.
Please tell me if there is anything missing.

### CODE REVIEW

**Comment by prusnak** [comment]
Just build your own firmware using this patch and use that for testing.

**Comment by wakiyamap** [comment]
Is there no problem with this sauce?
OK!! Thanks!

**Comment by prusnak** [comment]
No, I just don't see many people using this feature except for developers. And developers can always build their own firmware.

**Comment by wakiyamap** [comment]
Hmm. So does this source have a problem? 
You don't have to merge them, but it sounds like there's a problem with the source.

Sorry for letting you take your time, but if it have any problems, please teach me know.

**Comment by prusnak** [comment]
There is no problem with the source

**Comment by wakiyamap** [comment]
Okay. Then, I will use this for now. Thank you!

P.S. I will continue to support trezor and bitcoin.

**Pull request closed without merging**
