### PR TITLE
Update Cardano to support Shelley era

### PR DESCRIPTION
**Pull request by gabrielKerekes**
As discussed in #948 I am creating a draft PR of our Cardano Byron to Shelley update.

_It's still a work in progress so be gentle please. However feel free to bring up any concerns you might have._

**What's changing:**
- 3 new address types are being added
- certificates are being added to transactions
- the old byron (bootstrap) addresses still need to be supported

**What's been done so far:**
- address derivation/verification should be close to done
- some basic transaction signing works, but there's much to be done still

**Some things that need pointing out:**
- it turns out that the CBOR Set is not needed, so changes to this file and the tests will eventually be dropped
- seed.py - When signing a single transaction it may happen that we will need both a node with the Byron namespace and also a node with the Shelley namespace. This isn't in line with how caching of the nodes was done. I am not sure whether the way I've implemented is OK, so please let me know if you have any thoughts.

### CODE REVIEW

**Comment by prusnak** [comment]
I strongly suggest you submit only changes that are relevant for the network update. Staking features should come in the subsequent PR. This simplifies the review process and makes chance we'll be able to accept the code in time much higher.

**Comment by gabrielKerekes** [comment]
It's not really that simple to separate it into two PRs - the protocol updates are pretty much the staking features. It's also possible that the second PR would make som changes to things added in the first PR - I don't know if that would be a problem.

**Comment by prusnak** [comment]
> the protocol updates are pretty much the staking features.

So if a person does not want to stake, they can use the current version of firmware to make transactions on the network without any problems?

**Comment by gabrielKerekes** [comment]
Well, no. But making it work requires that much of the functionality of staking be in place also. Staking is pretty much only about adding certificates to the transaction body and enabling withdrawals of funds. That's maybe 20% of the whole update. However if you insist on splitting it, I will try to do so.

**Comment by prusnak** [comment]
> That's maybe 20% of the whole update. 

I think you are underestimating the complexity added by staking. Looking at [messages-cardano.proto from your PR](https://github.com/trezor/trezor-firmware/pull/1048/files#diff-422e258dd6831027b5fe5b433df93480) it seems that 80% of changes in the protocol are because of the staking. Changes in the protocol mean changes in Connect, trezorlib and other parts of our technology stack.

**Comment by gabrielKerekes** [comment]
Ok, we figured out a way to split it up into three independent, reasonably sized, working parts.
1. Transactions sending from Byron addresses to Byron addresses and opaque Shelley addresses (the hw wallet does not know if a Shelley address is user's own or not and will always ask for a confirmation). This will include the new transaction format and the introduction of some of the new protobuf types.
2. Shelley address verification and support for new address types, including using them as both inputs and outputs in transactions. This also includes some changes to key derivation and the use of new key paths. Most of the new address types include staking information (the user will not have the ability to register a staking key yet, but can create addresses derived from the key).
3. Certificates, withdrawals from reward addresses, metadata.

We think this should make it easier to review and each PR would actually work without the subsequent PRs. Does this sound good to you?

**Comment by prusnak** [comment]
> We think this should make it easier to review and each PR would actually work without the subsequent PRs. Does this sound good to you?

Perfect!

**Comment by matejcik** [comment]
now that the independent PRs are coming, is it OK to close this @gabrielKerekes ?

**Comment by gabrielKerekes** [comment]
Yes, thank you.

**Pull request closed without merging**
