### PR TITLE
Remove ontology and xfails

### PR DESCRIPTION
**Pull request by tsusanka**
Ontology is not yet finished in core and xfails are not needed anymore since we have monorepo.

After this is merged let's comment here https://github.com/trezor/trezor-core/pull/323 to inform about the removal (and that the code is now in `ontology` branch).

Slightly connected to https://github.com/trezor/trezor-firmware/pull/160

---

@matejcik please mainly check the core/docs/testing.md doc file.

### CODE REVIEW

**Comment by tsusanka** [comment]
Tests are currently failing because of `test_msg_signtx_komodo.py`, which was marked as xfail and is now failing.

**Comment by prusnak** [comment]
Please don't merge as is, but rather squash commits where you remove ONT into one commit. Eventually leading to two commits "tests: remove xfail" and the rest as another commit.

**Comment by prusnak** [comment]
Did the changes above by myself and merged to master. Thanks!

**Comment by prusnak** [comment]
Created draft PR for Ontology: https://github.com/trezor/trezor-firmware/pull/177

**Comment by tsusanka** [comment]
> Please don't merge as is, but rather squash commits where you remove ONT into one commit.

Wasn't sure myself what's better. Thanks!

**Pull request closed without merging**
