### PR TITLE
fix haptic driver initialization

### PR DESCRIPTION
**Pull request by TychoVrahe**
uninitialized struct causing mayhem

### CODE REVIEW

**Review by cepetr — APPROVED** [review]

**Comment by prusnak** [comment]
Note: there are uninitialized structures all around the HAL code, should we fix them all?

(Some are fine, because then we initialize all structure members, but it is hard to tell by eye)

You can discover them by using the following regexp (in vscode/ripgrep):

`\w+TypeDef \w+;`

**Comment by TychoVrahe** [comment]
yeah we should. future extensibility along with using same code with HAL drivers for different MCUs is very strong argument to do this

**Comment by prusnak** [comment]
> yeah we should. future extensibility along with using same code with HAL drivers for different MCUs is very strong argument to do this

```
$ rg -Hn --no-heading '\w+TypeDef \w+;'  | grep ^core/embed/trezorhal 
core/embed/trezorhal/stm32f4/lowlevel.c:163:  PWR_PVDTypeDef pvd_config;
core/embed/trezorhal/stm32f4/i2c.c:49:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/i2c.c:123:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/backlight_pwm.c:32:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/optiga_hal.c:8:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/rgb_led.c:93:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/rgb_led.c:102:  TIM_HandleTypeDef TIM4_Handle;
core/embed/trezorhal/stm32f4/rgb_led.c:113:  TIM_HandleTypeDef TIM8_Handle;
core/embed/trezorhal/stm32f4/rgb_led.c:123:  TIM_OC_InitTypeDef TIM_OC_InitStructure;
core/embed/trezorhal/stm32f4/sbu.c:25:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/displays/ili9341_spi.c:188:static SPI_HandleTypeDef SpiHandle;
core/embed/trezorhal/stm32f4/displays/ili9341_spi.c:282:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/displays/ug-2828tswig01.c:280:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/displays/vg-2864ksweg01.c:125:SPI_HandleTypeDef spi_handle;
core/embed/trezorhal/stm32f4/displays/vg-2864ksweg01.c:164:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/touch/stmpe811.c:327:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/touch/stmpe811.c:474:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/touch/ft6x36.c:65:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/touch/ft6x36.c:92:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/touch/ft6x36.c:140:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/displays/st7789v.c:371:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/sdram.c:63:static SDRAM_HandleTypeDef SdramHandle;
core/embed/trezorhal/stm32f4/sdram.c:64:static FMC_SDRAM_TimingTypeDef Timing;
core/embed/trezorhal/stm32f4/sdram.c:65:static FMC_SDRAM_CommandTypeDef Command;
core/embed/trezorhal/stm32f4/sdram.c:292:  static DMA_HandleTypeDef dmaHandle;
core/embed/trezorhal/stm32f4/sdram.c:293:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/sdram.c:412:  static DMA_HandleTypeDef dma_handle;
core/embed/trezorhal/stm32f4/usbd_conf.c:66:static PCD_HandleTypeDef pcd_fs_handle;
core/embed/trezorhal/stm32f4/usbd_conf.c:69:static PCD_HandleTypeDef pcd_hs_handle;
core/embed/trezorhal/stm32f4/sdcard-set_clr_card_detect.h:47:  SDIO_CmdInitTypeDef sdmmc_cmdinit;
core/embed/trezorhal/stm32f4/dma2d.c:57:  DMA2D_CLUTCfgTypeDef clut;
core/embed/trezorhal/stm32f4/button.c:11:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/sdcard.c:80:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/sdcard.c:112:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/sdcard.c:223:  HAL_SD_CardInfoTypeDef cardinfo;
core/embed/trezorhal/stm32f4/sdcard.c:322:  DMA_HandleTypeDef dummy_dma;
core/embed/trezorhal/stm32f4/sdcard.c:384:  DMA_HandleTypeDef dummy_dma;
core/embed/trezorhal/stm32f4/consumption_mask.c:45:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32f4/consumption_mask.c:54:  TIM_HandleTypeDef TIM8_Handle;
core/embed/trezorhal/stm32f4/consumption_mask.c:64:  TIM_OC_InitTypeDef TIM_OC_InitStructure;
core/embed/trezorhal/stm32f4/usb.c:68:static USBD_HandleTypeDef usb_dev_handle;
core/embed/trezorhal/stm32f4/usb.c:69:static const USBD_DescriptorsTypeDef usb_descriptors;
core/embed/trezorhal/stm32f4/usb.c:70:static const USBD_ClassTypeDef usb_class;
core/embed/trezorhal/stm32u5/sdcard.c:63:  SDMMC_CmdInitTypeDef sdmmc_cmdinit;
core/embed/trezorhal/stm32u5/sdcard.c:88:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32u5/sdcard.c:119:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32u5/sdcard.c:226:  HAL_SD_CardInfoTypeDef cardinfo;
core/embed/trezorhal/stm32f4/displays/ltdc.c:32:LTDC_HandleTypeDef LtdcHandler;
core/embed/trezorhal/stm32f4/displays/ltdc.c:33:static RCC_PeriphCLKInitTypeDef PeriphClkInitStruct;
core/embed/trezorhal/stm32f4/displays/ltdc.c:82:  LTDC_LayerCfgTypeDef Layercfg;
core/embed/trezorhal/stm32f4/displays/ltdc.c:225:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32u5/lowlevel.c:276:  PWR_PVDTypeDef pvd_config;
core/embed/trezorhal/stm32u5/i2c.c:71:  GPIO_InitTypeDef GPIO_InitStructure;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:340:  HAL_SD_CardStatusTypeDef CardStatus;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:470:  SD_InitTypeDef Init;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:673:  SDMMC_DataInitTypeDef config;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:858:  SDMMC_DataInitTypeDef config;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:1045:  SDMMC_DataInitTypeDef config;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:1140:  SDMMC_DataInitTypeDef config;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:1237:  SDMMC_DataInitTypeDef config;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:1336:  SDMMC_DataInitTypeDef config;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:2363:  SDMMC_InitTypeDef Init;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:2945:  HAL_SD_CardStateTypeDef CardState;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:3002:  HAL_SD_CardCSDTypeDef CSD;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:3281:  SDMMC_DataInitTypeDef config;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:3510:  SDMMC_DataInitTypeDef config;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:3680:  SDMMC_DataInitTypeDef sdmmc_datainitstructure;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:3794:  SDMMC_DataInitTypeDef sdmmc_datainitstructure;
core/embed/trezorhal/stm32u5/stm32u5xx_hal_sd.c:3921:  SDMMC_DataInitTypeDef sdmmc_datainitstructure;
core/embed/trezorhal/stm32u5/touch/sitronix.c:815:  GPIO_InitTypeDef gpio_init_structure;
```

**Comment by TychoVrahe** [comment]
created a separate issue for that https://github.com/trezor/trezor-firmware/issues/3643

**Pull request merged**
