### PR TITLE
chore(core): remove some unused assets and code

### PR DESCRIPTION
**Pull request by obrusvit**
Removing model_t leftovers from mercury code.

This also changes the icon used while locking the screen. The previous one was not even in assets for TS5. Cc: @Hannsek

### CODE REVIEW

**Review by mmilata — APPROVED** [review]
UI diff ack
imo `ICON_KEY` is correct since it is displayed on the lockscreen

**Comment by Hannsek** [comment]
Yeah, the old one was horrible. 

I asked Luke to come up with the new lock icon, but the key is fine for now.

**Comment by Hannsek** [comment]
Btw, how much space we've saved by this?

**Comment by obrusvit** [comment]
@Hannsek We saved roughly "šul-nul"

**Pull request merged**
