### PR TITLE
openocd: separate stlink configs deprecated - now combined

### PR DESCRIPTION
**Pull request by prusnak**
Let's merge this AFTER openocd 0.11 stable is released.

### CODE REVIEW

**Comment by mcudev** [comment]
looks good to me

**Comment by mcudev** [comment]
FYI, the Ubuntu 20.10 `openocd` package includes the change that we have been waiting for (I'm not sure when they first included it since I haven't checked the Ubuntu package in a while).

In that package `/usr/share/openocd/scripts/interface/stlink.cfg` is the file that the other deprecated configs includes.

As of right now, it looks like openocd 0.11 is still in release candidate state (v0.11.0-rc1): https://sourceforge.net/p/openocd/code/ref/master/tags/

**Comment by prusnak** [comment]
> FYI, the Ubuntu 20.10 `openocd` package includes the change that we have been waiting for (

Thanks for the info. Hopefully 0.11 stable will come out soon and we'll be able to merge this PR.

**Comment by mcudev** [comment]
looks good to me

**Comment by mcudev** [comment]
0.11.0 is released as of a couple of days ago http://openocd.org/2021/03/openocd-0-11-0-released/

**Comment by prusnak** [comment]
Great! Finally a release after 2 years :)

**Pull request merged**
