### PR TITLE
Add GoByte coin (GBX) support

### PR DESCRIPTION
**Pull request by D0WN3D**
Hello,

I did some changes to add GoByte (GBX).
Antonio Moratti - GoByte Network, Project Co-Founder.

Blockbook
https://blockbook.gobyte.network/

More information:
https://gobyte.network/
https://github.com/gobytecoin/gobyte
https://insight.gobyte.network/

Chainparams:
https://github.com/gobytecoin/gobyte/blob/master/src/chainparams.cpp

Contact:
dev@gobyte.network
antoniom@gobyte.network
Telegram: @AntonioMoratti

### CODE REVIEW

**Comment by D0WN3D** [comment]
I see that CI failed because of 'Files src/trezorlib/coins.json and /tmp/tmp.Xjd5H8nWNz differ'. We haven't commited that file as it's auto-generated by 'make gen' command. Should we upload it there anyway?

**Comment by prusnak** [comment]
What GBX wallet do you plan to integrate Trezor into?

**Comment by D0WN3D** [comment]
Hi @prusnak 

Can you include it in https://wallet.trezor.io/ ?

We also plan to integrate it into our Core wallet and at https://webwallet.gobyte.network/

Thank You

**Comment by prusnak** [comment]
We are not adding new coins to our wallet. Once you have Trezor integration ready in your wallet, we'll merge this request.

**Comment by matejcik** [comment]
> I see that CI failed because of 'Files src/trezorlib/coins.json and /tmp/tmp.Xjd5H8nWNz differ'. We haven't commited that file as it's auto-generated by 'make gen' command. Should we upload it there anyway?

yes, please add all files modified by `make gen` to the PR

**Comment by prusnak** [comment]
Reopen when you have wallet ready to test.

**Pull request closed without merging**
