### PR TITLE
layouts: altcoin apps

### PR DESCRIPTION
**Pull request by mmilata**
This is a follow-up of #1480 which modifies all altcoin apps to use the layout abstraction. To support various multiple page confirms it adds the `paginate_paragraphs` function which is a generalization of `paginate_text` that allows mixing fonts in the paginated output, with the restriction that different font text must start on a new line.

In the previous PR we discussed the `truncate=` parameter which is used here to emulate the old behavior wrt. text that doesn't fit on a single screen. It's used quite a lot to keep the UI diff small (or skip the pagination logic if we know the text fits), even in some cases where pagination might be desirable. Ideas?

My aim was to keep the [UI diff](https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/1113283338/artifacts/master_diff/index.html) reasonably small even though there are some differences especially for Eos and Monero.

Not covered in this PR, to be done in the next (final) one:
* `apps.management` and `apps.webauthn`
* splitting `trezor.ui.layouts.tt` to multiple modules to make it smaller
* review of `br_type` values to have them consistent & useful to Suite

### CODE REVIEW

**Comment by mmilata** [comment]
Rebased to master. [UI diff](https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/1177138423/artifacts/master_diff/index.html).

**Comment by matejcik** [comment]
before this is merged, I want to do two things:

- Implement auto-swiping. I'll do that via a separate PR and then rebase this on top of it. This will improve the UI diff, because right now a lot of screens are not correctly scrolled.

- Finish the TODO with putting property label and value always on the same screen

**Comment by matejcik** [comment]
I rebased this on today's master (incl. auto-pagination) and finished the key+value display above.

@mmilata please review my commits (starting at 85cdddc)

**Comment by mmilata** [comment]
Thanks for finishing confirm_properties, it looks very good! Seems like device tests failed, probably due to the ButtonRequest changes. Am curious about the final UI diff, but the screens I've seen look OK.

**Comment by matejcik** [comment]
CI passing now

**Comment by mmilata** [comment]
Reviewed UI diff for the last time and found only improvements. Let's merge it.

**Comment by bosomt** [comment]
**QA OK** 

`Trezor model T version  2.4.1 revision 01c1ae42`

**Wallets:**
Monero,
SimpleStaking
Cardano, 
MyeEth + MyCrypto, 
Electrum, Electrum Multisig, 
Mycellium - Android, Blockstream GREEN - Andorid
and of course Trezor Wallet /standard + shamir backup and recovery / and Trezor Suite /standard + shamir backup and recovery /

**Pull request merged**
