### PR TITLE
chore(core): update cs.json

### PR DESCRIPTION
**Pull request by Hannsek**
Fixes https://github.com/trezor/trezor-firmware/issues/3697

### CODE REVIEW

**Review by matejcik — APPROVED** [review]

**Comment by matejcik** [comment]
approved but let's wait and update the fixtures before merging

**Comment by Hannsek** [comment]
@obrusvit @mmilata please regenerate 🙏🏻

**Comment by obrusvit** [comment]
I will do it

**Comment by Hannsek** [comment]
@matejcik merge it pls, I cannot.

**Pull request merged**
