### PR TITLE
fix(crypto): avoid warnings and document bitwise operator use

### PR DESCRIPTION
**Pull request by invd**
Discovered via clang-14 warnings for -Wbitwise-instead-of-logical
Closes https://github.com/satoshilabs/trezor-firmware/issues/129

### CODE REVIEW

**Comment by andrewkozlik** [comment]
Hmm, I just realized that maybe the `|` instead of `||` is intentional to avoid short-circuiting and ensure constant time operation.

**Comment by invd** [comment]
@andrewkozlik : I may be missing something here, but in my understanding the `||` operator only skips the second check as part of lazy evaluation if the first check is true. If that is the case, the assert will trigger. 
An attacker with good time observation can figure out if the assert triggered after one or after two checks, so this still leaks information about the exact `cond` value, but AFAIK this is acceptable in the error case.

We can cast the checks to `(int)` and keep the `|` to suppress the warning and keep the non-short-circuit behavior if we're sure that this is functionally correct.

**Comment by andrewkozlik** [comment]
> We can cast the checks to `(int)` and keep the `|` to suppress the compiler warning and keep the non-short-circuit behavior if we're sure that this is functionally correct.

Agreed, and also add a comment explaining that it is intentional, because otherwise it look really weird. But first, let's figure out whether the `|` is intentional or not, or to be more precise whether constant-time operation is required for `cond`. The assertion was introduced in 24ceb0ab6b, so @onvej-sl should weigh in.

**Comment by onvej-sl** [comment]
The `|` is definitely intentional and constant-time operation for `cond` is required.

**Review by prusnak — APPROVED** [review]

**Review by andrewkozlik — APPROVED** [review]

**Review by onvej-sl — APPROVED** [review]

**Pull request merged**
