### PR TITLE
Ethereum improvements

### LINKED ISSUE #800: Show Wei amount and contract address for unknown tokens
We could improve UX of unknown tokens, by:
1) showing wei amount of the token being transacted
2) showing the contract address on the second page of the confirm dialog

### LINKED ISSUE #1335: Looser checks for replay-protected Ethereum networks
With the introduction of strict keychain namespacing, Trezor T stopped working with several not officially supported Ethereum-based networks: see #1326, #1332, #1331 

We believe it is safe to explicitly re-enable support for such networks in the future. There is strong replay protection in the form of EIP-155 chain ID, we use currency symbol `UNKN`, and we can display a warning about "Unknown chain ID" or "Unknown network", whichever seems more user-friendly.

The only open issue is what SLIP44 identifier to use for such networks. We do not want to allow just any, and we can't use chain id in place of SLIP44 because there are mismatches in practice.

One possibility is always using `60`, which is Ethereum id, and the networks often use it in practice. (fwiw, #1184 allows this explicitly, because some networks want cross-signing and token compatibility)
Another is always showing path warning regardless of provided path.

### PR DESCRIPTION
**Pull request by matejcik**
fixes #800 by displaying wei amount for uknown tokens and their contract address
fixes #1335 by allowing any Ethereum network that specifies a chain_id to sign transactions
allows using SLIP44 60 (Ethereum) for any Ethereum network

adds the `ethereum-lists/chains` repo as a source for our Ethereum network definition. due to this icon files are also dropped (we don't use them and upstream doesn't provide them)

removes `blockbook` and `bitcore` fields from individual coin definitions, and adds them in a separate file. This seems nicer to manage, as we generally control these entries, while individual coins can be contributed by 3rd parties.

please review mainly the modifications in `core` and `tests`

### CODE REVIEW

**Comment by matejcik** [comment]
blocked by https://github.com/ethereum-lists/chains/pull/125 -- the referenced commit is not yet merged into the chains repo, although presumably we can access it through github magic

**Comment by matejcik** [comment]
now the CI is finally happy

**Review by prusnak — APPROVED** [review]
utACK

Changes in `core/src/apps/ethereum/` should be reviewed also by someone else

**Review by tsusanka — APPROVED** [review]
LGTM! Please rebase.

I've also looked into the [UI changes](https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/847727674/artifacts/master_diff/index.html) and we show the contract address [also for known tokens](https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/847727674/artifacts/master_diff/diff/test_msg_ethereum_signtx.py-test_ethereum_signtx_known_erc20_token.html). Is that intentional? And is it needed?

I vaguely remember we have discussed this but now I can't remember the reasoning. Because on one hand I understand the token's abbreviation do not have to be unique (right?) on the other hand we are trying to force the user to confirm something they may not understand. And this might be exactly the case where they might just click through blidnly which something we are trying to avoid.

**Comment by matejcik** [comment]
> Is that intentional? And is it needed?

It is intentional, yes. We currently enforce that every token symbol must be unique, but the contract address is the only thing that's guaranteed to be right (and verifiable by the user).

Wherher it's needed is a big question, of course. I honestly didn't worry too much about the UX because the whole Ethereum UX is a mess and this should be fixed in the redesign.

**Comment by matejcik** [comment]
modified the tokens commit, now 2959ae1 after rebase, so that it only shows the contract screen if the token is unknown. The patch is smaller than before too :)

**Comment by prusnak** [comment]
There is one outstanding issue with the PR - the legacy test failed - https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/863315591

I assume there is one extra SignTx screen in TT processing when compared to T1

**Comment by tsusanka** [comment]
Discussed with @matejcik on Slack that I'll push thix. I will merge after it passes.

**Comment by rafx85** [comment]
Any info when xDai will be supported on Trezor with Metamask?

**Comment by matejcik** [comment]
@rafx85 the firmware integrating xDai is slated for February release
but maybe ask Metamask to fix their Trezor integration first...

**Comment by rafx85** [comment]
@matejcik thank you for info, I wrote about it on their Reddit to be public, maybe they will do something about it, some people got stuck with xDai on their wallets as me.

**Comment by Kuphi** [comment]
> @rafx85 the firmware integrating xDai is slated for February release
> but maybe ask Metamask to fix their Trezor integration first...

I transferred some Dai to xDai on my trezor. With metamask + trezor I can not move them. How can I move them?

**Comment by raymonddurk** [comment]
> > @rafx85 the firmware integrating xDai is slated for February release
> > but maybe ask Metamask to fix their Trezor integration first...
> 
> I transferred some Dai to xDai on my trezor. With metamask + trezor I can not move them. How can I move them?

That is what this entire thread is about. You can't. Metamask needs to fix their Trezor integration and then the Trezor firmware needs to be upgraded to support xDAI.

**Comment by Kuphi** [comment]
> > > @rafx85 the firmware integrating xDai is slated for February release
> > > but maybe ask Metamask to fix their Trezor integration first...
> > 
> > 
> > I transferred some Dai to xDai on my trezor. With metamask + trezor I can not move them. How can I move them?
> 
> That is what this entire thread is about. You can't. Metamask needs to fix their Trezor integration and then the Trezor firmware needs to be upgraded to support xDAI.

Hope soon. As workaround I downgraded my model T to v2.3.0 now and works so far. xDai chain is great. Transaction "gas fee" for swap on Honeyswap is just 0.0003 $, imao.

**Pull request merged**
