### PR TITLE
feat(cardano): allow external reward addresses in governance registrations

### PR DESCRIPTION
**Pull request by davidmisiak**
Changes in governance registrations:
- Reward address can be provided as an address string instead of address parameters.
- If the reward address is provided as address parameters, we display its credentials instead of address string.
- If a non-payment reward address is provided, we display a warning that the address is not eligible for voting rewards ([context](https://github.com/cardano-foundation/CIPs/pull/373)).

### CODE REVIEW

**Comment by davidmisiak** [comment]
Hi @matejcik, any updates on this please?

Also, there was a [recent change](https://github.com/cardano-foundation/CIPs/pull/427) in CIP-36:
- The `gov_vk` bech32 prefix was replaced by `cvote_vk`.
- Usage of `governance` in naming is discouraged (they reserve the term for other purposes to avoid confusion) and they recommend using `CIP-36 vote` instead.

Therefore I suggest changing `gov_vk` to `cvote_vk` and replacing all occurences of `governance` in the codebase with `cvote` - what do you think? If you agree, shall I add the change to this PR?

**Comment by matejcik** [comment]
> Therefore I suggest changing `gov_vk` to `cvote_vk` and replacing all occurences of `governance` in the codebase with `cvote` - what do you think? If you agree, shall I add the change to this PR?

I have no opinion on the change. "cvote" is shorter than "governance" so that's nice, the prefixes are completely up to Cardano and/or you.
Feel free to add it to this PR if you can.

**Comment by davidmisiak** [comment]
Done - I changed the bech32 prefix, replaced `governance` by `cvote` and renamed `reward_address` to `payment_address` in CIP36 registrations (as they did in [CIP36](https://cips.cardano.org/cips/cip36/)). I also rebased onto the current master.

**Comment by davidmisiak** [comment]
I added one more minor rename (`voting public key` -> `vote public key`), https://github.com/trezor/trezor-firmware/pull/2692/commits/2752b4c3ca2e8533421671cdd47917bdc314ff81.

Shall I also update UI tests or should I wait?

**Review by matejcik — APPROVED** [review]

**Comment by davidmisiak** [comment]
Rebased, updated UI tests and added changelog entries.

**Comment by bosomt** [comment]
Is there anything that can/needs to be done by QA team ?

**Comment by matejcik** [comment]
don't think so

**Pull request merged**
