### PR TITLE
Consolidate BTC test transactions

### PR DESCRIPTION
**Pull request by grdddj**
Connected with https://github.com/trezor/trezor-firmware/issues/2085 and finalizing the efforts from https://github.com/trezor/trezor-firmware/issues/1018 

Explicitly stating which test transactions are real (existing on the blockchain) and which are not. The former are using `assert_tx_matches` with a connection to `blockbook`, and the latter use plain `assert` of the `serialized_tx` with a comment stating the tx is unexisting.

Done just for `BTC`, not for all the other clones like `BTC Gold`, `Decred` etc., as it is not worth the effort there.

WRT https://github.com/trezor/trezor-firmware/issues/2085, I still need to create 5 transactions, as they currently fail the optional `tx_hex` comparison with `blockbook`

### CODE REVIEW

**Comment by grdddj** [comment]
[f6a901d](https://github.com/trezor/trezor-firmware/pull/2175/commits/f6a901d55bf8074da7d2ece3218aec2b1782db5c) creates three new real taproot transactions.

Two are remaining - one with `ownership_proof` (`test_p2tr_with_proof`) and one with fee-bump and use of `orig_hash` in `TxInputType` (`test_p2tr_fee_bump`) - I do not know how to easily do them.

@onvej-sl I would say that we are finished and ready-to-review

**Comment by onvej-sl** [comment]
Thank you, @grdddj, for your help.

The transactions on blockchain that are referenced in Fujicoin and Groestlcoin tests still don't correspond to the transactions that you get from Trezor. These solutions come to mind:
  1. Find someone who is able to get these transactions on blockchain and ask them to do that. (The guy in https://github.com/trezor/trezor-firmware/pull/2030 should be able to do it for Groestlcoin).
  2. Discard the comments that refer to the transactions.
  3. Leave the comments that refer to the transactions but add explaining comments.
 
Since I have little experience with device tests I don't feel like deciding how to fix it. I expect someone more experienced (@andrewkozlik @matejcik) to review this PR and decide which approach to take.

Just a short note on the intention of this PR: The PR is a prerequisite for updating the secp256k1-zkp module, which is a prerequisite for fixing https://github.com/trezor/trezor-firmware/issues/2085, which is almost done in https://github.com/trezor/trezor-firmware/tree/onvej-sl/update-secp256k1-zkp.

**Comment by matejcik** [comment]
there are still two TODOs left.

also please leave a comment on the fujicoin/grs transactions that have blockbook links, e.g., "transaction hex changed when we fixed #2085" or something?

**Comment by grdddj** [comment]
> there are still two TODOs left.

I did not manage to create these transactions on-chain. If everyone agrees, we could just regard them as any other non-existent transaction with `# Transaction does not exist on the blockchain, not using assert_tx_matches()` - we lose very little verification, and can still include similar comment like below ("tx hex changed because of this, otherwise it is this tx...")


> also please leave a comment on the fujicoin/grs transactions that have blockbook links, e.g., "transaction hex changed when we fixed https://github.com/trezor/trezor-firmware/issues/2085" or something?

Done in [b1a03f9](https://github.com/trezor/trezor-firmware/pull/2175/commits/b1a03f990698be162b68da85d8151ca1dd21ec7f)

**Comment by matejcik** [comment]
OK, please go ahead and remove the assert_tx in these two cases. then please rebase on master and fix the fixture conflict

**Comment by grdddj** [comment]
> OK, please go ahead and remove the assert_tx in these two cases. then please rebase on master and fix the fixture conflict

Done in [a462614](https://github.com/trezor/trezor-firmware/pull/2175/commits/a462614bfe49b42cf72e945b15ebd3bf301643e8)

There is a changelog-check fail, so we might want to include some changelog message or put `[no changelog]` in [58d64a2](https://github.com/trezor/trezor-firmware/pull/2175/commits/58d64a2ca963a3f84c903367a08e2cb7bd875f87)

**Pull request merged**
