### PR TITLE
T1 "go to bootloader" from firmware

### PR DESCRIPTION
**Pull request by hiviah**
Implements function `svc_reboot_to_bootloader()` that can be called from firmware (with MPU and dropped privileges) which makes bootloader to act as if user pushed button to enter bootloader.

The flag needs to be stored in RAM, since all basic registers are cleared on reset, other special registers like `SCB->MMFAR` or `SCB->BFAR` are either undefined or not accessible due to MPU.

Bootloader at very beginning before cleaning RAM copies the flag to register, then cleans RAM, and reads back the flag from register. It is expected that the compiler won't use R11 in the meantime (there is no way to instruct compiler to do that, it just happens that it's not used early in the code).

### CODE REVIEW

**Review by Lord-Of-Gamers — APPROVED** [review]

**Comment by prusnak** [comment]
I pushed a small commit which renames variables {go,return}_to_bootloader => stay_in_bootloader

Quick question: isn't it enough to just store the flag in the register? Do we need to store it in RAM? Are all registers cleared up on device soft reset?

**Comment by hiviah** [comment]
Unfortunately all normal registers are cleared upon reset. There are some things that survive like hardware breakpoints, some of the special registers (System Control Block) - but those are not accessible due to MPU and dropped privileges from firmware at all.

**Comment by mcudev** [comment]
>  It is expected that the compiler won't use R11 in the meantime...

Rather than relying on the compiler behavior of not using R11 in bootloader.c to that point in the code, perhaps save the flag back into SRAM within the `reset_handler` just before calling `main`. Something similar to what the TT boardloader does with `__stack_chk_guard`. We were able to do that without changing the linker script, so I'm assuming that this way can be done with a simpler overall change too.

How are you going to deploy this bootloader change to existing T1 devices? If we can't deploy it to existing devices, then the documentation about how to enter bootloader mode still needs to exist. At that point, we've only made it easier for new users with new devices (which might be good enough, but I'm just pointing it out).

Also including my other comments about re-verification from https://github.com/trezor/trezor-firmware/issues/1047#issuecomment-763253748

**Comment by prusnak** [comment]
> How are you going to deploy this bootloader change to existing T1 devices?

Yes. Via https://github.com/trezor/trezor-firmware/blob/5395c542c1ce3f9595c3e5d900ec01d1e26d0258/legacy/firmware/bl_check.c#L139

We've been upgrading the bootloader to the latest version via firmware for quite some time already.

**Comment by hiviah** [comment]
> Rather than relying on the compiler behavior of not using R11 in bootloader.c to that point in the code, perhaps save the flag back into SRAM within the reset_handler just before calling main

We discussed that it could be done by changing the code that deletes RAM so that the flag is stored at beginning of RAM, erasing memory will skip it and doesn't need to rely on the register. This needs some checks whether it won't affect something else since beginning of RAM is a bit "special" place.

As a side note, System Control Block is after all not writable from CPU (despite documentation) though it is writable through JTAG.

**Comment by prusnak** [comment]
> We discussed that it could be done by changing the code that deletes RAM

The idea was not changing the code that deletes RAM, but rather moving ram_start forwards or even better ram_end backwards by few bytes (32?) and using this 32-byte area as special place to pass stuff from firmware to bootloader and vice-versa.

**Comment by hiviah** [comment]
Purely technically that is changing the code (=the whole RAM isn't deleted anymore). End of RAM looks a bit better, just then it also needs to change in T1 core port (and possibly other places/special firmwares).

**Comment by prusnak** [comment]
> Purely technically that is changing the code (=the whole RAM isn't deleted anymore).

Yeah, I just wanted to make it obvious that we are not going to change the assembler code, but rather to change the bounds of the memory in the linker script.

**Comment by mcudev** [comment]
I think you're right that having the bootloader and firmware linker scripts both agree on a special use area seems like a better approach than what I was thinking.

**Comment by mcudev** [comment]
I just had a thought for the T1. I didn't test it, so it might not work for some reason that I didn't think of (like all methods of soft reset being blocked by the MPU). But, couldn't we get the same effect by just soft resetting it and either 1) just before the soft reset, tell the user to press the button like already is handled, or 2) instead of telling the user to press the button, check for a soft reset, like is done with https://github.com/trezor/trezor-firmware/blob/7d8fbacba7c5945ca93068f6c44e0df134e6b657/core/embed/trezorhal/lowlevel.c#L167, and stay in the T1 bootloader if if is not a full power-on event.
Maybe you want more flexibility than to assume a soft reset is a "stay in bootloader" signal. The reason I was thinking about this is because relying on the value of uninitialized memory feels possibly less reliable than I'd be comfortable with. I guess that could be mitigated some with a value for `STAY_IN_BOOTLOADER_FLAG` that has a hamming distance greater than 2 from zero.

**Comment by prusnak** [comment]
@hiviah See the comment above - checking the contents of `RCC_CSR` might be also the way how to solve this on TT where we can't use RAM to pass the data between the firmware and the bootloader, because the boardloader wipes all of that.

**Comment by hiviah** [comment]
Unfortunately it seems that `RCC CSR` is cleared by the time it reaches bootloader, probably by something in boardloader.

**Comment by mcudev** [comment]
The TT boardloader looks at the reset flags, and if they indicate a non-full-power-on event (for example, a soft reset, but more examples are given in section 6.3.21 in the RM0090 doc) then the boardloader returns from `main` goes into `shutdown`. I think that I did this to avoid an attack that didn't target the chip's boot ROM (my memory's a bit hazy, but this is probably close to what I was thinking). I tested this with my dev hardware and it was pretty reliable (hence the comment about making development painful). So, I wouldn't count on being able to use this flag check on the TT.

The T1 is different and I think those flags could be used as an alternative indicator to how this PR proposed.

The TT boardloader clears the reset flags at https://github.com/trezor/trezor-firmware/blob/7d8fbacba7c5945ca93068f6c44e0df134e6b657/core/embed/trezorhal/lowlevel.c#L180
I think I did that in-case somehow the boardloader didn't catch a non-full-power-on reset event. Processing would continue through the boardloader and I wanted it to appear to later code that it was a normal full-power-on event.

**Comment by hiviah** [comment]
There is something weird going on with soft reset on TT and boardloader. Getting random hard faults after reset. Kind of feels like the MCU errata bug:

    [0] from 0x0800974c
    [1] from 0xfffffff9
    [2] from 0x08007664 in FMC_NORSRAM_Extended_Timing_Init+56 at vendor/micropython/lib/stm32lib/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.c:391
    [3] from 0x08006fea in HAL_SRAM_Init+66 at vendor/micropython/lib/stm32lib/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c:167
    [4] from 0x08004e0a in display_init+382 at embed/extmod/modtrezorui/display-stm32_T.h:302
    [5] from 0x0800529a in main+74 at embed/boardloader/main.c:187

**Comment by prusnak** [comment]
Rebased on top of master, added small fixes in 4b0f41d41ebf15cff1c7c2fb18a6a3a21316512b

**Comment by prusnak** [comment]
@hiviah Does the `*STAY_IN_BOOTLOADER_FLAG_ADDR = STAY_IN_BOOTLOADER_FLAG;` in `legacy/supervise.c` assign an 8-bit value or a 32-bit value? I assume this assigns a 32-bit value, right?

If that's true we might want to change the `STAY_IN_BOOTLOADER_FLAG` magic from 0x11 to e.g. `0x0FC35A96`. Will you try if that value still works, please?

**Comment by hiviah** [comment]
@prusnak `STAY_IN_BOOTLOADER_FLAG` is 32-bit. I tested it with `0x0FC35A96` and it works. (Checked also the disassembler when running

**Comment by prusnak** [comment]
OK, thanks. Merged to master.

**Pull request merged**
