### PR TITLE
fix: Cardano button requests

### PR DESCRIPTION
**Pull request by vladimirvolek**
resolves: https://github.com/trezor/trezor-firmware/issues/1764

### CODE REVIEW

**Comment by matejcik** [comment]
Let's not add 20 new entries to the ButtonRequestType enum. Instead please see propsed solution in  #35, in particular https://github.com/trezor/trezor-firmware/issues/35#issuecomment-903836036

**Comment by matejcik** [comment]
fwiw we could probably move this forward by using Cardano as a testbed for the feature, and then propagating the new usage back to other coins

**Comment by tsusanka** [comment]
Ok let's do it the "new way" which we yet need to fine-tune. Apologies @vladimirvolek. @matejcik let's close both this and the issue?

**Comment by vladimirvolek** [comment]
Closing after the discussion with @tsusanka.

**Pull request closed without merging**
