### PR TITLE
feat(python): extend sign_message to also sign bytes, not only string

### PR DESCRIPTION
**Pull request by grdddj**
Finalizing PR https://github.com/trezor/trezor-firmware/pull/1225:
- just some renaming and docs changes

### CODE REVIEW

**Comment by matejcik** [comment]
please add a changelog entry about the rename

**Comment by grdddj** [comment]
> How do we show raw bytes message on the display?

The `CLI` can call the `btc.sign_message` only with string parameter, so somebody would need to call it themselves with bytes. I tried to simulate it with random bytes (`os.urandom(16)`) and it seems to be printing hex nicely:

image

**Comment by prusnak** [comment]
> it seems to be printing hex nicely:

Nice. How about T1?

**Comment by matejcik** [comment]
> Nice. How about T1?

https://github.com/trezor/trezor-firmware/blob/update-deps/legacy/firmware/fsm.c#L334-L340

**Review by prusnak — APPROVED** [review]

**Review by matejcik — APPROVED** [review]

**Pull request merged**
