### PR TITLE
ci: actions: upload emulator binaries to data.trezor.io

### LINKED ISSUE #3676: Push emulators from main branch to trezor.io
Both core and legacy emulators from main branch ... name them as you want, e.g. trezor-emu-core-T2B1-main etc.

### PR DESCRIPTION
**Pull request by mmilata**
Fixes #3676

URLs:
* core: https://data.trezor.io/dev/firmware/emu-latest/trezor-emu-core-INTERNALMODEL-COINS where
* legacy: https://data.trezor.io/dev/firmware/emu-latest/trezor-COINS.elf

Where INTERNALMODEL is e.g. T2T1 and COINS is either `universal` or `btconly`.

### CODE REVIEW

**Review by grdddj — APPROVED** [review]
Thanks! Core works all fine.

However, legacy does not, e.g. https://data.trezor.io/dev/firmware/emu-latest/trezor-universal.elf

**Comment by mmilata** [comment]
Final location:
* https://data.trezor.io/dev/firmware/emu-nightly/trezor-emu-legacy-T1B1-btconly
* https://data.trezor.io/dev/firmware/emu-nightly/trezor-emu-core-T3T1-universal
* ...

**Comment by vdovhanych** [comment]
Can we build arm emulators but on x86? Perhaps with some flag to do the cross-compile during the build?

**Comment by vdovhanych** [comment]
Well, why I'm asking, there are currently no arm runners available for GitHub actions, so we won't be able to build arm emulators (needed for apple silicon macs) on GitHub for a while. Github started a private beta for arm runners in January but who knows when tat will be available.

**Comment by mmilata** [comment]
Can we connect our own arm runner? Don't the arm macs have some kind of x86 emulation?

**Pull request merged**
