### PR TITLE
refactor(core): disable SD card, SBU, fatfs for T1 build

### LINKED ISSUE #1163: Disable Core features for T1 port
Currently the T1 port includes the following features which are not available on T1:

  - `core/embed/extmod/modtrezorio/modtrezorio-fatfs.h`
  - `core/embed/extmod/modtrezorio/modtrezorio-sdcard.h`
  - `core/embed/extmod/modtrezorio/modtrezorio-sbu.h`

We should remove these from `core/embed/extmod/modtrezorio/modtrezorio.c` and make sure these (`trezor.io.fatfs`, `trezor.io.sdcard`, `trezor.io.sbu`) are never called from MicroPython while running on T1.

### PR DESCRIPTION
**Pull request by mmilata**
Fixes #1163.

### CODE REVIEW

**Comment by matejcik** [comment]
the `sdcard_tt` redirect is weird.

why can't we exclude `trezor/sdcard.py` directly, and fix this at import sites?

**Comment by mmilata** [comment]
I wanted to postpone changing `apps/common/request_pin.py` until we get to implementing T1 pin entry (which needs layouts). Still, I suppose it can be done better, let me see.

**Comment by matejcik** [comment]
`apps.common.request_pin` should not be importing `storage.sd_salt` on top level (ideally not at all, but it seems it's the best way to implement `can_lock_device` so the model difference should be handled there)

`apps.common.sdcard` seems like a very good place for the redirect of the sort you did

**Comment by mmilata** [comment]
I've moved the redirect to `apps/common/sdcard.py`, PTAL. Also relevant parts of trezorhal are now built only for TT. It's getting a bit messy but at least it shaves ~30K off the fw image size.

**Comment by matejcik** [comment]
> at least it shaves ~30K off the fw image size.

does this also factor the Python sources?

I was comparing the earlier version with the current one, and ISTM the earlier approach from a199eb2 is more correct. That is, localizing the difference to `trezor.sdcard`, and have the module available but returning different data.

What do you think about this? https://github.com/trezor/trezor-firmware/compare/matejcik/sdcard?expand=1
(also removing the `trezor.fatfs` redirect, it didn't seem to help anything)

**Comment by mmilata** [comment]
> does this also factor the Python sources?

Not sure what you mean, it was the difference in size of firmware.bin files.

> What do you think about this?

Looks reasonable, merged it with the C/buildsystem changes and force-pushed, hopefully that's what you had in mind. PTAL

**Review by matejcik — APPROVED** [review]
utACK

**Comment by mmilata** [comment]
Resolved conflicts, please take a look when you have time @prusnak.

**Comment by alex-jerechinsky** [comment]
@prusnak please review when possible

**Review by prusnak — APPROVED** [review]

**Review by prusnak — APPROVED** [review]
LGTM

**Pull request merged**
