### PR TITLE
Delete without release in T2B1

### PR DESCRIPTION
**Pull request by grdddj**
Extending https://github.com/trezor/trezor-firmware/pull/3290:
- making the button action happen even without release, after 1 second of holding the middle button

### CODE REVIEW

**Comment by grdddj** [comment]
Should be in a working state now, I have even a click test for it. @Hannsek please try for some inconsistencies

**Comment by Hannsek** [comment]
It doesn't work for me in all flows on emulator. 🤔

**Comment by grdddj** [comment]
> It doesn't work for me in all flows on emulator. 🤔

Sorry for that, I had forgotten something there. Should be fixed in [05a4575](https://github.com/trezor/trezor-firmware/pull/3294/commits/05a4575c0cfe134b42b4eef106f5ae151d635ce5)

**Comment by Hannsek** [comment]
working good now

**Review by mmilata — APPROVED** [review]
utACK

**Comment by STew790** [comment]
**QA OK**

When holding both buttons for >1s it deletes the whole text/PIN input.

**Info:**
 - Suite version: desktop 23.10.0 (e6d29e01e6fc70862133fcb1ebf968132afa7379)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.10.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.6.2 regular (revision c581a37aba5d33f1ad93a368c978c67f698a4087)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
