### PR TITLE
Fix requiring button confirmation with intermediate FW

### LINKED ISSUE #1674: Intermediary FW asks for FW confirmation on new devices
If I install Intermediary 1.10.0 on brand new device from the factory (BL 1.4.0) I am prompted for firmware update confirmation which goes against the intermediary [spec](https://www.notion.so/satoshilabs/Intermediary-FW-3815baff0d4d4682b40dc7a3bcefbb9a). The spec says there should no confirmation needed on user's side.

This is what Trezor looks like after Intermediary FW is installed:
image

If I install normal FW afterwards this is what I get:

image

But the FW should be installed right away without any confirmation because the intermediary FW should delete itself. It should therefore equal to a device on which I run `trezorctl wipe-device --bootloader`, which looks like this and does not prompt before FW install:

image

I believe this is not a blocker for Suite's release - there is simply just an extra confirmation which is not ideal but not blocking as Suite handles it. It would be nice to fix this though so the extra confirmation is removed.

Note that as described in the spec the Intermediary FW **can not erase storage for initialized devices**. Having prompt there is OK as written in the spec.

Full video [here](https://drive.google.com/file/d/10JxEPD1nv5cGpYH1z5YgF-O7kIv_kwAG/view?usp=sharing).

### PR DESCRIPTION
**Pull request by hiviah**
Another attempt to fix #1674.

Build required to find few extra bytes for it to fit into bootloader image which are gained by compressing ECDSA pubkey coordinates.

(bootloader is not yet bundled in intermediate FW)

Script used for conversion of pubkeys for check:

    #!/usr/bin/env python3
    from ecdsa.keys import VerifyingKey
    from ecdsa.curves import SECP256k1

    keys = [
            b"\x04\xd5\x71\xb7\xf1\x48\xc5\xe4\x23\x2c\x38\x14\xf7\x77\xd8\xfa\xea\xf1\xa8\x42\x16\xc7\x8d\x56\x9b\x71\x04\x1f\xfc\x76\x8a\x5b\x2d\x81\x0f\xc3\xbb\x13\x4d\xd0\x26\xb5\x7e\x65\x00\x52\x75\xae\xde\xf4\x3e\x15\x5f\x48\xfc\x11\xa3\x2e\xc7\x90\xa9\x33\x12\xbd\x58",
            b"\x04\x63\x27\x9c\x0c\x08\x66\xe5\x0c\x05\xc7\x99\xd3\x2b\xd6\xba\xb0\x18\x8b\x6d\xe0\x65\x36\xd1\x10\x9d\x2e\xd9\xce\x76\xcb\x33\x5c\x49\x0e\x55\xae\xe1\x0c\xc9\x01\x21\x51\x32\xe8\x53\x09\x7d\x54\x32\xed\xa0\x6b\x79\x20\x73\xbd\x77\x40\xc9\x4c\xe4\x51\x6c\xb1",
            b"\x04\x43\xae\xdb\xb6\xf7\xe7\x1c\x56\x3f\x8e\xd2\xef\x64\xec\x99\x81\x48\x25\x19\xe7\xef\x4f\x4a\xa9\x8b\x27\x85\x4e\x8c\x49\x12\x6d\x49\x56\xd3\x00\xab\x45\xfd\xc3\x4c\xd2\x6b\xc8\x71\x0d\xe0\xa3\x1d\xbd\xf6\xde\x74\x35\xfd\x0b\x49\x2b\xe7\x0a\xc7\x5f\xde\x58",
            b"\x04\x87\x7c\x39\xfd\x7c\x62\x23\x7e\x03\x82\x35\xe9\xc0\x75\xda\xb2\x61\x63\x0f\x78\xee\xb8\xed\xb9\x24\x87\x15\x9f\xff\xed\xfd\xf6\x04\x6c\x6f\x8b\x88\x1f\xa4\x07\xc4\xa4\xce\x6c\x28\xde\x0b\x19\xc1\xf4\xe2\x9f\x1f\xcb\xc5\xa5\x8f\xfd\x14\x32\xa3\xe0\x93\x8a",
            b"\x04\x73\x84\xc5\x1a\xe8\x1a\xdd\x0a\x52\x3a\xdb\xb1\x86\xc9\x1b\x90\x6f\xfb\x64\xc2\xc7\x65\x80\x2b\xf2\x6d\xbd\x13\xbd\xf1\x2c\x31\x9e\x80\xc2\x21\x3a\x13\x6c\x8e\xe0\x3d\x78\x74\xfd\x22\xb7\x0d\x68\xe7\xde\xe4\x69\xde\xcf\xbb\xb5\x10\xee\x9a\x46\x0c\xda\x45",
    ]

    for key in keys:
        vk = VerifyingKey.from_string(key, curve=SECP256k1)
        #pub_key = vk.to_string('uncompressed')
        #print("Uncompressed:", pub_key.hex())
        pub_key = vk.to_string('compressed')
        #print("Compressed:", pub_key.hex())
        print("""(const uint8_t *)"%s",""" % ("".join(["\\x" + "%02x" % b for b in pub_key])))

Warning: can set random things on fire probably

### CODE REVIEW

**Comment by prusnak** [comment]
Looks good at first sight.

I wonder how much longer is the verification using compressed pub keys - I have a feeling this change will make the boot process much longer.

**Comment by tsusanka** [comment]
I am starting to wonder whether this is worth it :-/. We can solve the extra step somehow in Suite instead of fiddling in bootloader. We can discuss on a standup when all three of us are present.

**Comment by prusnak** [comment]
> We can solve the extra step somehow in Suite instead of fiddling in bootloader.

I am definitively for solving the extra step in the Suite for now. This PR is something for later update.

**Comment by onvej-sl** [comment]
> I wonder how much longer is the verification using compressed pub keys - I have a feeling this change (requirement to uncompress the keys first) will make the boot process much longer.

Based on the number of multiplication that is used in `uncompress_coords` I think uncompressing a key takes about 20 ms. ECDSA verification takes about 200 ms.

**Comment by hiviah** [comment]
Though probably we should leave this trick as backup for when we *really* need the extra bytes for some serious fix (since there basically isn't any left unless you want to do things like redraw graphics so we can use the symmetry trick again).

**Comment by tsusanka** [comment]
Closing, it is not worth it, we'll solve this in Suite (https://github.com/trezor/trezor-suite/issues/4047).

**Pull request closed without merging**
