### PR TITLE
bootloader: soft reset after firmware upload.

### PR DESCRIPTION
**Pull request by kedoubitcoin**
Display prompt after firmware upload, then disable all interrupts, and soft reset after delay.

### CODE REVIEW

**Comment by prusnak** [comment]
Have you tried this code? Does it work for you?

**Comment by kedoubitcoin** [comment]
Thank you very much for your reply. Yes, I tested this function, and it will be reset after displaying a prompt after updating the firmware.

**Comment by kedoubitcoin** [comment]
Thank you very much for your reply. Yes, I tested this function, and it will be reset after displaying a prompt after updating the firmware.

**Comment by prusnak** [comment]
Superseded by https://github.com/trezor/trezor-firmware/pull/847 

Thank you!

**Pull request closed without merging**
