### PR TITLE
Fix uzlib window allocation in rust

### PR DESCRIPTION
**Pull request by TychoVrahe**
Fixing window allocation problem in Uzlib. Pins window location on stack.

### CODE REVIEW

**Comment by matejcik** [comment]
@jpochyla care to take a look?

**Comment by jpochyla** [comment]
@matejcik Uuuuuh I'm not sure what I was thinking there, but now that I look at it: with the window decoupled to a separate struct like this, and kept on stack, I think `Pin` is actually not needed here and we can use `&mut`.

**Comment by matejcik** [comment]
it's kind of unwieldy though

another option would be to re-set the window pointer every time we call uncompress

**Comment by TychoVrahe** [comment]
if we don't use Pin, we don't even need the window struct, just a slice in the caller? we need to never return the UzlibContext out of the caller function, otherwise it fails again (which is probably true even with the pin). 

resetting the pointer would discard the work done by C inside the window, wouldn't it?

I went for decoupling of the window because we can save some stack space if we don't need it. And also i couldn't make it compile when trying to Pin the whole struct :]

**Comment by matejcik** [comment]
> we need to never return the UzlibContext out of the caller function, otherwise it fails again (which is probably true even with the pin).

add the `'a` lifetime to the window parameter and Rust won't let you return

> resetting the pointer would discard the work done by C inside the window, wouldn't it?

as long as Rust is actually moving the data -- which it should be -- then no, the pointer and the index into the window is separate

**Comment by TychoVrahe** [comment]
second attempt: removed the pin, using slice in the caller and &mut.

**Review by matejcik — APPROVED** [review]

**Comment by matejcik** [comment]
LGTM, please squash fixups & merge

**Pull request merged**
