### PR TITLE
update micropython to v1.13

### PR DESCRIPTION
**Pull request by prusnak**
Fixes https://github.com/trezor/trezor-firmware/issues/1273

The change also contains `vendor/micropython/lib/tinyusb` submodule change. Ideal is to redo the `git clone --recursive` of the whole repo after this is merged to master.

### CODE REVIEW

**Comment by prusnak** [comment]
Waiting for matejcik's `perf_test` - we will track the following metrics to see how they changes:
* memory consumption
* memory allocations count
* run time

**Comment by prusnak** [comment]
master (upy-1.12):

```
time: 347887 ms
allocs: 2463373
meminfo: 123600 (alloc) / 36656 (free)
```

upy-v1.13:

```
time: 346155 ms
allocs: 2463424
meminfo: 127104 (alloc) / 33152 (free)
```

**Comment by tsusanka** [comment]
@prusnak what is the state of this PR? Do we want to merge it in 2020-10 or should we move it to backlog?

**Comment by prusnak** [comment]
The PR is ready. If we want to start using `x:int = 1` typing feature, we should merge it now. Otherwise, this can wait. But there is reason not to merge this except for the "never touch a running system" rule :-)

**Comment by tsusanka** [comment]
I am a gentle +1. Rebasing PRs can be annoying over time :).

**Review by matejcik — APPROVED** [review]

**Pull request merged**
