### PR TITLE
docs(core): replace Purpose48 with BIP-48

### PR DESCRIPTION
**Pull request by mmilata**
As [BIP-48](https://github.com/bitcoin/bips/blob/master/bip-0048.mediawiki) has been merged, our recently added documentation of Purpose48 derivation path is no longer needed. Please note that the `0'` aka `p2ms` script type is not included.

### CODE REVIEW

**Review by matejcik — APPROVED** [review]
LGTM but please @prusnak ack this as well

**Comment by matejcik** [comment]
do we need a changelog entry?

**Comment by mmilata** [comment]
Added changelog in 64a06c1.

**Review by prusnak — APPROVED** [review]

**Comment by matejcik** [comment]
@mmilata please squash, rebase and merge

**Pull request merged**
