### PR TITLE
feat(common): enable Taproot on Groestlcoin

### PR DESCRIPTION
**Pull request by gruve-p**
Added additional device tests for GRS

Added P2TR GetAddress for GRS mainnet and testnet

Added SignTX spending taproot UTXO (The resulting transaction from the SignTx device test was successfully mined on Testnet.)

### CODE REVIEW

**Review by prusnak — APPROVED** [review]

**Comment by andrewkozlik** [comment]
I don't see any unit tests or device tests. There should at least be a test for `GetAddress` and a test for `SignTx` spending a taproot UTXO. The resulting transaction from the `SignTx` should be successfully mined on Testnet or Mainnet.

**Comment by matejcik** [comment]
I'm ignoring the changelog failure; given that the change is in definitions, it doesn't seem appropriate to add to firmware changelog.

Thanks for the PR @gruve-p

**Comment by matejcik** [comment]
well, it appears that i've been too trigger happy.

The provided testcase is failing:
https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/1907118477

**Comment by matejcik** [comment]
In particular, the witness data is significantly different from the [on-chain version](https://chainz.cryptoid.info/grs-test/tx.dws?2444006.htm), despite the fact that everything else seems to match.
Please advise @gruve-p, otherwise I'll have to revert the change.

**Comment by gruve-p** [comment]
Looking at it now @matejcik

**Comment by gruve-p** [comment]
```
groestlcoin-cli -testnet getrawtransaction "45aeb9af884b4082104b0212c5f40ffca8f0127e627a05810b69f0bad777678c" true
{
  "txid": "45aeb9af884b4082104b0212c5f40ffca8f0127e627a05810b69f0bad777678c",
  "hash": "b6b2517c8f10e17773f1ffc97692f34e8aa1ed8c1b977b637156eb7779203496",
  "version": 1,
  "size": 162,
  "vsize": 111,
  "weight": 444,
  "locktime": 0,
  "vin": [
    {
      "txid": "f79cf536f6516fb2808b4728c403be98aebef49fec5ba206a0a397527214e929",
      "vout": 1,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "txinwitness": [
        "0925acfe20ef34929aab585d0fe0a9c1b11219c1fc512f56572a0201e38f3bc38721a6afc9e19801a5c5bc6e806e07a6fc7412b2fc863057f528e30038554916"
      ],
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.00004450,
      "n": 0,
      "scriptPubKey": {
        "asm": "1 e9af2fc69e20b0be2629cd0e9c34da9f3ef56af7beac4fb4298262bc5a45ec5d",
        "hex": "5120e9af2fc69e20b0be2629cd0e9c34da9f3ef56af7beac4fb4298262bc5a45ec5d",
        "address": "tgrs1paxhjl357yzctuf3fe58fcdx6nul026hhh6kyldpfsf3tckj9a3wsvuqrgn",
        "type": "witness_v1_taproot"
      }
    }
  ],
  "hex": "0100000000010129e914725297a3a006a25bec9ff4beae98be03c428478b80b26f51f636f59cf70100000000ffffffff016211000000000000225120e9af2fc69e20b0be2629cd0e9c34da9f3ef56af7beac4fb4298262bc5a45ec5d01400925acfe20ef34929aab585d0fe0a9c1b11219c1fc512f56572a0201e38f3bc38721a6afc9e19801a5c5bc6e806e07a6fc7412b2fc863057f528e3003855491600000000",
  "blockhash": "00000072cdc5e3e62999a8f4e66c93911b53d7b2580a1be360c2d4e5ecddd31c",
  "confirmations": 1017,
  "time": 1640035432,
  "blocktime": 1640035432
}
```

https://blockbook-test.groestlcoin.org/tx/45aeb9af884b4082104b0212c5f40ffca8f0127e627a05810b69f0bad777678c
`"hex": "0100000000010129e914725297a3a006a25bec9ff4beae98be03c428478b80b26f51f636f59cf70100000000ffffffff016211000000000000225120e9af2fc69e20b0be2629cd0e9c34da9f3ef56af7beac4fb4298262bc5a45ec5d01400925acfe20ef34929aab585d0fe0a9c1b11219c1fc512f56572a0201e38f3bc38721a6afc9e19801a5c5bc6e806e07a6fc7412b2fc863057f528e3003855491600000000"`

https://rpcexplorer-test.groestlcoin.org/tx/45aeb9af884b4082104b0212c5f40ffca8f0127e627a05810b69f0bad777678c#JSON
` "hex": "0100000000010129e914725297a3a006a25bec9ff4beae98be03c428478b80b26f51f636f59cf70100000000ffffffff016211000000000000225120e9af2fc69e20b0be2629cd0e9c34da9f3ef56af7beac4fb4298262bc5a45ec5d01400925acfe20ef34929aab585d0fe0a9c1b11219c1fc512f56572a0201e38f3bc38721a6afc9e19801a5c5bc6e806e07a6fc7412b2fc863057f528e3003855491600000000",`

`groestlcoin-cli -testnet decoderawtransaction` 
```
0100000000010129e914725297a3a006a25bec9ff4beae98be03c428478b80b26f51f636f59cf70100000000ffffffff016211000000000000225120e9af2fc69e20b0be2629cd0e9c34da9f3ef56af7beac4fb4298262bc5a45ec5d01400925acfe20ef34929aab585d0fe0a9c1b11219c1fc512f56572a0201e38f3bc38721a6afc9e19801a5c5bc6e806e07a6fc7412b2fc863057f528e3003855491600000000
{
  "txid": "45aeb9af884b4082104b0212c5f40ffca8f0127e627a05810b69f0bad777678c",
  "hash": "b6b2517c8f10e17773f1ffc97692f34e8aa1ed8c1b977b637156eb7779203496",
  "version": 1,
  "size": 162,
  "vsize": 111,
  "weight": 444,
  "locktime": 0,
  "vin": [
    {
      "txid": "f79cf536f6516fb2808b4728c403be98aebef49fec5ba206a0a397527214e929",
      "vout": 1,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "txinwitness": [
        "0925acfe20ef34929aab585d0fe0a9c1b11219c1fc512f56572a0201e38f3bc38721a6afc9e19801a5c5bc6e806e07a6fc7412b2fc863057f528e30038554916"
      ],
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.00004450,
      "n": 0,
      "scriptPubKey": {
        "asm": "1 e9af2fc69e20b0be2629cd0e9c34da9f3ef56af7beac4fb4298262bc5a45ec5d",
        "hex": "5120e9af2fc69e20b0be2629cd0e9c34da9f3ef56af7beac4fb4298262bc5a45ec5d",
        "address": "tgrs1paxhjl357yzctuf3fe58fcdx6nul026hhh6kyldpfsf3tckj9a3wsvuqrgn",
        "type": "witness_v1_taproot"
      }
    }
  ]
}
```

Trezor test expects `0100000000010129e914725297a3a006a25bec9ff4beae98be03c428478b80b26f51f636f59cf70100000000ffffffff016211000000000000225120e9af2fc69e20b0be2629cd0e9c34da9f3ef56af7beac4fb4298262bc5a45ec5d0140d17017c886692fc511532777e24b95935bc9b5b7b781016e73b8286aab52ac17a318d03955c6bed99970f39984bc38abd26e2955f17686ba8c1fd2e565bc44d800000000` serialized, hex-encoded data for '45aeb9af884b4082104b0212c5f40ffca8f0127e627a05810b69f0bad777678c'

```
groestlcoin-cli -testnet decoderawtransaction 0100000000010129e914725297a3a006a25bec9ff4beae98be03c428478b80b26f51f636f59cf70100000000ffffffff016211000000000000225120e9af2fc69e20b0be2629cd0e9c34da9f3ef56af7beac4fb4298262bc5a45ec5d0140d17017c886692fc511532777e24b95935bc9b5b7b781016e73b8286aab52ac17a318d03955c6bed99970f39984bc38abd26e2955f17686ba8c1fd2e565bc44d800000000
{
  "txid": "45aeb9af884b4082104b0212c5f40ffca8f0127e627a05810b69f0bad777678c",
  "hash": "d137df2c97fe0a6f5a3217a93b4ab88fec0f3a6d1cf4dd1ba6a8704dd7daa99d",
  "version": 1,
  "size": 162,
  "vsize": 111,
  "weight": 444,
  "locktime": 0,
  "vin": [
    {
      "txid": "f79cf536f6516fb2808b4728c403be98aebef49fec5ba206a0a397527214e929",
      "vout": 1,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "txinwitness": [
        "d17017c886692fc511532777e24b95935bc9b5b7b781016e73b8286aab52ac17a318d03955c6bed99970f39984bc38abd26e2955f17686ba8c1fd2e565bc44d8"
      ],
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.00004450,
      "n": 0,
      "scriptPubKey": {
        "asm": "1 e9af2fc69e20b0be2629cd0e9c34da9f3ef56af7beac4fb4298262bc5a45ec5d",
        "hex": "5120e9af2fc69e20b0be2629cd0e9c34da9f3ef56af7beac4fb4298262bc5a45ec5d",
        "address": "tgrs1paxhjl357yzctuf3fe58fcdx6nul026hhh6kyldpfsf3tckj9a3wsvuqrgn",
        "type": "witness_v1_taproot"
      }
    }
  ]
}
```

The blockhash and the txinwitness are different

**Comment by matejcik** [comment]
> Trezor test expects `0100000000010129e914725297a3a006a25bec9ff4beae98be03c428478b80b26f51f636f59cf70100000000ffffffff016211000000000000225120e9af2fc69e20b0be2629cd0e9c34da9f3ef56af7beac4fb4298262bc5a45ec5d0140d17017c886692fc511532777e24b95935bc9b5b7b781016e73b8286aab52ac17a318d03955c6bed99970f39984bc38abd26e2955f17686ba8c1fd2e565bc44d800000000` serialized,

to clarify, the test _expects_ the right data (txhash `b6b2517c8f10e17773f1ffc97692f34e8aa1ed8c1b977b637156eb7779203496`)
Trezor however signs and **produces** the other variant (txhash `d137df2c97fe0a6f5a3217a93b4ab88fec0f3a6d1cf4dd1ba6a8704dd7daa99d`)

how is Groestlcoin txid calculated, btw? why is it different from the txhash?

**Comment by gruve-p** [comment]
Groestlcoin txid for legacy, p2sh and segwit are calculated in single sha256 (instead of Bitcoins double sha256) and are defined in a groestl curve: https://github.com/trezor/trezor-firmware/commit/e7281cf9f5145cd81a9789a91efc8c9f0567cee8

Groestlcoin txid for taproot are calculated in taggedhash (same as Bitcoin)

**Comment by prusnak** [comment]
> Groestlcoin txid for taproot are calculated in taggedhash (same as Bitcoin)

Are you sure? I was under impression that Bitcoin does not use taggedhash to compute the txid.

**Comment by matejcik** [comment]
> how is Groestlcoin txid calculated, btw? why is it different from the txhash?

The true answer is that it's a segwit thing, namely, `txid` excludes witness data but `txhash` doesn't.

Still open: Why does Trezor produce a different signature than what's on chain? Are both signatures correct? @gruve-p

**Comment by gruve-p** [comment]
I have no idea why Trezor produces a different signature, the one on chain is correct @matejcik

**Comment by matejcik** [comment]
Ok, thanks for the info.
I'm reverting the change since Taproot + Groestlcoin apparently doesn't work out of the box. Feel free to open a PR/issue if you figure out more about the issue.

**Comment by andrewkozlik** [comment]
> I have no idea why Trezor produces a different signature, the one on chain is correct @matejcik

I haven't looked at the data above, but I should say that the signature is generally non-deterministic, i.e. there is an immense number of correct signatures. So the mismatch doesn't necessarily mean that there is anything wrong. Trezor produces its signatures deterministically so that they can be checked in the device tests. You should generate the signature by Trezor and broadcast that transaction to be sure, that the implementation is compatible with GroestlCoin. If that doesn't work then we will have to investigate further. It's possible that GroestlCoin uses a different hash function at some point or adds some tag information etc. I haven't looked at the spec of GroestlCoins Taproot, so I can't say.

**Comment by matejcik** [comment]
thanks @andrewkozlik
i was able to create a GRS transaction that has been accepted by the chain in #2033

**Comment by gruve-p** [comment]
Does this mean that the signature produced by Trezor was also correct? If so, how was this PR supposed to be solved? By creating a new taproot transaction untill the signatures were both identical in the tests?

**Comment by matejcik** [comment]
You would have to use Trezor to create the transaction in the first place, then use the already produced transaction as a testcase.

**Comment by gruve-p** [comment]
But mine trezor 1 and trezor T does not support taproot for GRS or do you mean by using the trezor emulator?

**Comment by andrewkozlik** [comment]
> But mine trezor 1 and trezor T does not support taproot for GRS or do you mean by using the trezor emulator?

Yes

**Comment by gruve-p** [comment]
OK good to know for next time, thank you @prusnak @andrewkozlik and @matejcik 
Merry X-mas to the Trezor team and a happy new year !!

**Pull request merged**
