### PR TITLE
Add basic trezor support for Verge (XVG)

### PR DESCRIPTION
**Pull request by marpme**
Add basic wallet support for trezor via the electrum wallet supplied by Verge.

This PR is connected to the initial build of our electrum wallet see: https://github.com/vergecurrency/electrum/pull/13

I've tested most stuff manually via the emulator.

### CODE REVIEW

**Comment by prusnak** [comment]
Is this issue already fixed? https://github.com/vergecurrency/electrum/issues/12

**Comment by marpme** [comment]
@prusnak It has been fixed with vergecurrency/electrum#13 and this PR.
I've locally tested receiving and sending XVG via the electrum wallet + trezor emulator and it has worked.

**Comment by tsusanka** [comment]
Hi there, thank you for your PR. After a thorough discussion in our Product team, we have decided we do not wish to include this PR in our firmware. Due to our limited capacity, we need to restrict our support to coins that we can afford to maintain in the long run. We hope you’ll understand this decision.

**Comment by marpme** [comment]
Hi, I'm completely unable to understand your decision. It's 66 lines of code that have been changed overall with the addition of a +4kb PNG. What do you mean by having a "limited capacity"? 

I think this is the vaguest answer that I've ever got. I'm totally disappointed to get such an answer after 6 months of waiting.

**Comment by justinvforvendetta** [comment]
why would this not be easy to maintain in the longrun? @tsusanka and what kind of firmware storage space does the device have?

**Comment by tsusanka** [comment]
Apologies, we have accidentally included this into a group of PRs which make substantial changes in the code. I did not notice this changes only `common/defs`. If you can rebase and squash into one commit we will try to merge this.

**Pull request closed without merging**
