### PR TITLE
Fix overflow in bip39.rs tests

### PR DESCRIPTION
**Pull request by matejcik**
by using `cstr!` to generate 0-terminated strings

### CODE REVIEW

**Comment by matejcik** [comment]
wondering why the ASAN test didn't catch it when this PR was made....?

**Comment by matejcik** [comment]
`test_lots_of_inputs` fails consistently on the ASAN build.
is this something we saw before?

**Comment by matejcik** [comment]
@mmilata ^^

**Comment by mmilata** [comment]
Seems to be happening more often than not in recent nightly runs. It's exceeding the `PYTEST_TIMEOUT` limit - we can raise it to more than 5m, though looking at the [pipelines](https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/pipelines?source=schedule) it seems that ~month ago around ( ~ bdfc4532) it started to happen more often.

**Comment by matejcik** [comment]
> ~month ago

probably the switch to external runners

i'll increase the time limit in this PR

**Pull request merged**
