### PR TITLE
Cardano Shelley hotfixes

### PR DESCRIPTION
**Pull request by gabrielKerekes**
I've discovered a minor bug while working on Trezor Connect. While deriving a base address with a foreign staking key hash, the displaying of this staking key hash would crash because of missing `.decode()` after `hexlify`. The first commit of this PR fixes that bug.

The second commit deals with script addresses. Support for script addresses wasn't planned at all in this release. However, in conversation with IOHK we came to the conclusion that it would be nice, if it was possible to have them as output addresses. This is possible in Ledger, since its non-change output validation is not so strict, so we would like the same for Trezor.

The implemented solution is one of possible solutions. Another would be to weaken the non-change output validation - perhaps, since the user is shown the output, the checks don't need to be so strict about address types and the length check can maybe be also simpified to check for a range of 29 to 64 bytes.

Also I've added the addresses to `messages-cardano.proto` even though they are not used in protobuf at the moment - I'm not sure whether to keep them there or not. This should not break the validation for Get-Address, since the address type is checked there explicitly.

I can of course split this up into 2 PRs if needed.

### CODE REVIEW

**Comment by gabrielKerekes** [comment]
I will regenerate UI tests before this should get merged.

**Comment by gabrielKerekes** [comment]
Some info about script addresses can be found [here](https://hydra.iohk.io/build/2006688/download/1/delegation_design_spec.pdf#subsubsection.3.2.6).

**Comment by matejcik** [comment]
> The implemented solution is one of possible solutions. Another would be to weaken the non-change output validation - perhaps, since the user is shown the output, the checks don't need to be so strict about address types and the length check can maybe be also simpified to check for a range of 29 to 64 bytes.

Are the different `*_SCRIPT_*` variants needed for anything else than length checks?
If not, let's loosen the length check instead.

**Comment by gabrielKerekes** [comment]
There's also this check:
```
if address_type == CardanoAddressType.BYRON:
    validate_output_byron_address(address_bytes, protocol_magic)
elif address_type in ADDRESS_TYPES_SHELLEY:
    _validate_output_shelley_address(address, address_bytes, network_id)
else:
    raise INVALID_ADDRESS
```
But loosening the check would eliminate the need for `ADDRESS_BYTES_MIN_LENGTHS` and `ADDRESS_BYTES_MAX_LENGTHS` which is also nice at this point.

**Comment by matejcik** [comment]
yes, let's get rid of the individual min/max lengths and keep just the full range

also please modify `_derive_shelley_address` to raise a `wire.DataError` (something like "cannot derive address of this type"?) in place of the `ValueError` for unsupported type

**Comment by gabrielKerekes** [comment]
Length check updated [here](https://github.com/trezor/trezor-firmware/pull/1150/commits/95c4ecec8149f711c5d90acff83a2333512d430a).

`wire.DataError` raising [here](https://github.com/trezor/trezor-firmware/pull/1150/commits/24af8a6e6d550da6986b35d5bc6fdfb5f6c5fb4c).

I'll still wait with the ui tests until it's approved.

**Comment by tsusanka** [comment]
@gabrielKerekes please squash.

**Comment by gabrielKerekes** [comment]
Thanks! Squashed.

**Pull request merged**
