### PR TITLE
ci: hardware tests on TT

### PR DESCRIPTION
**Pull request by mmilata**
Based on @tsusanka's work on #946. The initial problems were actually resolved by upgrading to gitlab-runner 13.3, my commits mostly attempt to improve the robustness of the testing.

* The HW tests are currently manual-only. Should be changed after the tpmb rig is relocated to its usual place. Meanwhile I'm gonna run the tests on `master` in [my gitlab fork](https://gitlab.com/mmilata/trezor-firmware/-/pipelines).
* Tests that need SD card are skipped, should be enabled after installing SD card.
* Some tests known to OOM often are skipped. Should be enabled after #1371 is fixed.
* Only the btconly firmware variant is tested on TT.

### CODE REVIEW

**Review by tsusanka — APPROVED** [review]
Great and exciting :tada: :). LGTM.

The configs will change of course later but I don't mind merging now and modifying later. What do you prefer?

> Only the btconly firmware variant is tested on TT.

Excuse me for forgetting again - but we can't run the full suite on TT because OOM issues as well?

**Comment by mmilata** [comment]
I'd slightly prefer merging this now and then updating it in another PR. Shouldn't break anything else since almost all changes are in `ci/hardware_tests`.

> Excuse me for forgetting again - but we can't run the full suite on TT because OOM issues as well?

That's right. We can run it but it's probably gonna OOM every time.

**Comment by prusnak** [comment]
> That's right. We can run it but it's probably gonna OOM every time.

Maybe if we rebooted the device between the tests it would work, no?

But I agree that's something for the later PR.

**Comment by mmilata** [comment]
> Maybe if we rebooted the device between the tests it would work, no?

It would help a lot but e.g. `TestMultisig::test_15_of_15` OOMs on the regular debug firmware even if it's the first test after boot.

**Comment by tsusanka** [comment]
As discussed on standup, maybe we can run "everything that is not bitcoin related" on the regular firmware? Or even divide into more jobs, 1. bitcoin only 2. management 3. altcoins (for example). And I would skip `TestMultisig::test_15_of_15` for now.

**Comment by tsusanka** [comment]
:heart: :heart: :heart: . @mmilata should I make a final review?

Note: we should enable the nightly builds on Gitlab after this is merged.

**Comment by mmilata** [comment]
@tsusanka yes please

**Review by tsusanka — APPROVED** [review]
LGTM! Let's merge this and see if it survives our daily development :)

**Pull request merged**
