### PR TITLE
chore(common): update chains+tokens

### PR DESCRIPTION
**Pull request by prusnak**
Updated the `common/defs/ethereum/{chains,tokens}` submodules.

@matejcik Can you please have a look at the change in `common/tools/coin_info.py` - it seems the names of the JSON files got changes (there is now `eip155-` prefix in the filename).

@matejcik Also I can't figure out the removals in `core/src/apps/ethereum/networks.py` while it seems the networks are still present in the new JSON files.

### CODE REVIEW

**Comment by matejcik** [comment]
> @matejcik Can you please have a look at the change in `common/tools/coin_info.py` - it seems the names of the JSON files got changes (there is now `eip155-` prefix in the filename

LGTM

> @matejcik Also I can't figure out the removals in `core/src/apps/ethereum/networks.py` while it seems the networks are still present in the new JSON files.

the inclusion relies on support info, and the removed networks got either aliased (the Gorli testnet exists for both ETH and OETH) or their symbol changed (DIO -> DIODE)

please also run `common/tools/support.py fix` at least, and perhaps set the support infos via `support.py release 1` and `support.py release 2` i think

**Comment by prusnak** [comment]
I did run `common/tools/support.py`, `support.py release 1` and `support.py release 2` and pushed the fixup cf27df0

**Comment by matejcik** [comment]
seems you did not re-run `make gen` afterwards

**Comment by prusnak** [comment]
Fixup in dc4cc7af53070d1b0e67c8d64df7dba6552ed001

**Comment by matejcik** [comment]
there are unresolved duplicate symbols
i'm going to fix it

**Comment by prusnak** [comment]
Hm, it seems we are somehow missing `"eth:ETH"` from `coins_details.json`. I checked master and it's there, but `marketcap_usd` is zero. Something fishy is going on ..

**Comment by matejcik** [comment]
good catch.
it's like this since we switched to the `chains` repo, because of course upstream must use names like "Ethereum Mainnet" instead of just "Ethereum"

i'm now stripping out "mainnet" from network names, which seems to help

**Pull request merged**
