### PR TITLE
core/wallet: fix segwit multisig comment

### PR DESCRIPTION
**Pull request by romanz**
Following https://gitter.im/trezor/community?at=5d6ce506d3fda15e7450589d.

### CODE REVIEW

**Comment by tsusanka** [comment]
Uf uf, I have to admit this is like 5th version of this comment, I went back and forth several times, but I'm finally inclining to the fact that you are right :).

I was a bit confused how come the version of the witness program would not be present there (as per your proposal), but then I've realized we are talking about the witness field and not scriptPubKey. I believe that's where the confusion might have occured. In [BIP-141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#p2wsh), there are two zeros in the section about P2WSH:

Screenshot from 2019-09-04 14-03-51

I believe we might have mixed those two up. I'll leave this open for now and merge it tomorrow, because I want some more time to think about it, but I think it is so.

**Comment by prusnak** [comment]
Yes, seems correct.

**Comment by tsusanka** [comment]
Thank you @romanz!

**Comment by romanz** [comment]
You're welcome :)

**Pull request merged**
