### PR TITLE
Show WRONG PIN header in PIN entry

### PR DESCRIPTION
**Pull request by grdddj**
Fixes https://github.com/trezor/trezor-firmware/issues/3239
- before user does any button click, they will see `WRONG PIN` in header row
- after any click, it will change to `ENTER PIN` (or any prompt)

### CODE REVIEW

**Comment by Hannsek** [comment]
image
Please change the font of "15 tries left" to Pixel Operator 8, Regular

**Comment by Hannsek** [comment]
Otherwise looks good! Thanks. :)

**Comment by grdddj** [comment]
> image Please change the font of "15 tries left" to Pixel Operator 8, Regular

Right, changed in the force-push

image

**Comment by grdddj** [comment]
Sorry, I had the MONO font instead of NORMAL. Now it looks like:

image

**Review by mmilata — APPROVED** [review]

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.10.1 (0b3ccfe0b8e9bc2af00609d640bc1be31ab8edaa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.10.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2B1 2.6.2 regular (revision 6e5967af25de87bebd331d697e6ef940e64286ef)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
