### PR TITLE
Merge 21.07 release branch

### PR DESCRIPTION
**Pull request by mmilata**

### CODE REVIEW

**Comment by prusnak** [comment]
Can't we just merge the branch instead of rebasing the change?

**Comment by mmilata** [comment]
I tried that previous release but the repo is configured to enforce linear history iirc.

**Comment by prusnak** [comment]
> I tried that previous release but the repo is configured to enforce linear history iirc.

I think admins can override this rule on merge. I'd prefer merge commit in this case, to make it obvious we are just merging the release branch.

**Comment by tsusanka** [comment]
I agree it would be simpler. I have turned it off for now could you do that @mmilata please? Will turn it on then.

**Review by tsusanka — APPROVED** [review]
I confirm all commits are present.

**Pull request merged**
