### PR TITLE
Add optiga_sec field to Features

### PR DESCRIPTION
**Pull request by andrewkozlik**
Adds a new `optiga_sec` field to `Features`, which contains the value of Optiga's security event counter (SEC). Benefits:
- Makes it easier to diagnose issues involving communication with Optiga
- We can collect analytics in Suite to see how prevalent the issues with Optiga's SEC are.
- Suite could instruct users to keep their Trezor plugged in when the SEC counter is high.

### CODE REVIEW

**Review by matejcik — APPROVED** [review]
utACK

**Comment by tsusanka** [comment]
@mroz22 @komret if we add a new field to Features in FW will it automatically show up in Suite's log?

**Comment by komret** [comment]
@tsusanka yes

**Comment by bosomt** [comment]
**QA OK**

```
❯ trezorctl get-features | grep tiga
    optiga_sec: 5,
```

**Info:**
 - Suite version: desktop 24.7.0 (17f727ae2eb1e934aff84f8d8e5d1859f8c50efd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.7.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision 3a039c505f48b97542e6118d9fb2dc867306770a)
 - Transport: BridgeTransport 2.0.33

**Pull request merged**
