### PR TITLE
synchronous protobuf codec

### PR DESCRIPTION
**Pull request by matejcik**
Obsoletes #190, big parts of code taken from there.

Two key features here:

* USB messages are now loaded into a pre-allocated 8kB buffer and the protobuf data is then decodes via synchronous calls. This saves a lot of allocations. The drawback is that it is now impossible to receive messages longer than 8 kB. This should not matter for our applications, but we will see. Worth special consideration is Monero, cc @ph4r05 
* caching of message field data has been improved, and apps can optionally keep a longer-lived cache, which helps tremendously in the Bitcoin app which requests the same message types over and over

Further includes `PYSTACK` for emulator and firmware, which seems to have a noticeable (although not too well explained) positive effect on performance.

It's questionable if the change from static `FIELDS` to method `get_fields()` is still necessary, what with the import/unimport machinery and apps (in theory) keeping only their own message definitions. If we reverted that, we could remove the caching logic and simplify the code.

That change should be deferred to a separate issue, preferably when we have a solid understanding of contents of the memory.

---

Without these changes, `test_lots_of_inputs`(*) on master takes 1342 s on device
With these changes, this is down to 927 s, so 30% less time.

(*) Stream 100 non-segwit inputs using the same 100-output prevtx, then stream all 100 inputs 100 times in order to sign each one; this comes out to ~20 000 protobuf exchanges.
To run: `pytest tests/device_tests/test_msg_signtx.py -k test_lots_of_inputs`

### CODE REVIEW

**Comment by matejcik** [comment]
TODO: fix core unit tests, which i always forget

**Comment by matejcik** [comment]
it seems that `test_add_remove` for webauthn writes out a message that is too long.
hm.

**Comment by prusnak** [comment]
> The drawback is that it is now impossible to receive messages longer than 8 kB.

I guess the limit should be somewhere around 15 KB. That's what we have in the T1 codebase to accommodate the maximum possible size of `TxAck`.

See https://github.com/trezor/trezor-firmware/blob/ca3dd2bfb9b02cfad8077f77e680740e6de3d9e0/legacy/firmware/messages.h#L27

and the generated nanopb files (`legacy/firmware/protob/messages-common.pb.h` and `legacy/firmware/protob/messages-bitcoin.pb.h`)

``` C
#define HDNodeType_size  121
#define TxAck_size       (8038 + 1*15*HDNodeType_size + 1*15*HDNodeType_size + 1*15*HDNodeType_size + 1*15*HDNodeType_size)
```

making it 15298 bytes altogether.

However, this is hardly possible to reach via transaction data that make sense - it is an upper bound limit when the size of all possible fields and subfields is added together.

**Comment by matejcik** [comment]
this also impacts homescreen uploads. we would either need to design a streaming protocol for homescreens, or change this somehow.

My current idea is to allow larger messages, and allocate a buffer on demand if the message is large. This seems to achieve what we need: we would reuse the same preallocated buffer most of the time, but could use larger messages in the few cases that require it.

**Comment by ph4r05** [comment]
@matejcik ad Monero - if dockerized Monero tests pass it should work. The messages are more or less normalized so I don't expect problems here. 

I just need to check key image sync as there is some batching on UTXOs per message (note for me).

**Comment by matejcik** [comment]
for now I have enlarged the buffer to 16 kB, which seems to work fine for all tests

**Comment by hiviah** [comment]
This definitely works much better with the "lots of segwits inputs" test, we are down from 10:21 to 7:03, and if you also disable `gc.collect` explicit calls in `sign_tx`, you'll get to 5:59)

**Comment by jpochyla** [comment]
> My current idea is to allow larger messages, and allocate a buffer on demand if the message is large. This seems to achieve what we need: we would reuse the same preallocated buffer most of the time, but could use larger messages in the few cases that require it.

I think in most cases the memory will be too fragmented to fit a continuous block >16kb (but it's better than failing every time, i guess).

Btw, with sync code, it would be a tiny bit faster to use polymorphic encode/decode for protobuf types instead of the if-else chain, but it probably won't show up on benchmarks.

**Comment by matejcik** [comment]
@andrewkozlik please have a look at 8c0cb75 and d696543

**Comment by matejcik** [comment]
done in 9ca5256. ready to merge when the CI passes

**Comment by jpochyla** [comment]
<3

**Pull request merged**
