### PR TITLE
Update emulator's device certificate

### PR DESCRIPTION
**Pull request by andrewkozlik**
This updates the testing certificate in the emulator to use the testing CA.

@matejkriz please check that the emulator now works with Suite.

### CODE REVIEW

**Comment by matejkriz** [comment]
@andrewkozlik works with Suite as expected 👌

**Comment by andrewkozlik** [comment]
@mmilata please check that `test_authenticate_device.py::test_authenticate_device` completes successfully on your device.

**Comment by mmilata** [comment]
Emulator works. The device hasn't been provisioned yet so I suppose it's expected that it returns `OptigaError: Signing failed.`?

**Comment by andrewkozlik** [comment]
Yes it is expected.

**Pull request merged**
