### PR TITLE
ci: make hardware core btconly device test pass

### PR DESCRIPTION
**Pull request by mmilata**
What the title says plus:
* better protection of TT from being flashed with production fw
* disable unreliable SD card tests until new card is procured

Regular firmware still doesn't pass due to memory fragmentation, however having passing btconly hardware test in the nightly runs is an improvement IMO.

### CODE REVIEW

**Comment by tsusanka** [comment]
> Regular firmware still doesn't pass due to memory fragmentation, however having passing btconly hardware test in the nightly runs is an improvement IMO.

Definitely! Since it seems quite painful to make the regular firmware work and in the end-game the tests should pass in its wholeness anyway (right?) maybe it does not make sense to agonize ourselves over it?

**Comment by mmilata** [comment]
Yeah, I think (arbitrary permutations of) tests passing without any reboot is a good goal - it worked at some point in the past, didn't it?

It's not really agonizing, I just run the tests once a day, see how far they go, insert a reboot there, and repeat:)

**Review by tsusanka — APPROVED** [review]
LGTM

**Comment by tsusanka** [comment]
Let's squash the commit and we can merge.

**Pull request merged**
