### PR TITLE
fix(core): fix haptic custom effect in loaders

### LINKED ISSUE #4316: Haptic feedback not present during signing of transaction.
**Describe the bug**
Haptic feedback not present during signing of transaction.
Previous 2.8.3 fw had gradually rising vibration feedback but 2.8.4 only has short one vibration after you finish hold to sign process. 

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 24.11.0 (c58454703ba01107ffa6e7938e1608354342b26a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d884daea42e9a1790e830e2fb5007f408413459d)
 - Transport: BridgeTransport 2.0.33

### PR DESCRIPTION
**Pull request by cepetr**
This PR fixes broken custom haptic effect used in loaders (fixes #4316)

### CODE REVIEW

**Review by mmilata — COMMENTED** [review]
Briefly tested and it appears to fix the issue.

**Review by TychoVrahe — APPROVED** [review]

**Comment by mmilata** [comment]
Does this need anything before merging?

**Comment by cepetr** [comment]
> Does this need anything else before merging?

@TychoVrahe tested it as well. I think we can merge it.

**Comment by bosomt** [comment]
**QA OK**

 - Device: Trezor T3T1 2.8.5 regular (revision a61e783448043760a7c925e017bd08a4673a61c8)

**Pull request merged**
