### PR TITLE
Add public_key to ECDHSessionKey

### PR DESCRIPTION
**Pull request by romanz**
This would allow implementing [age](https://age-encryption.org/) decryption plugin without caching the public key on the host: https://github.com/romanz/trezor-agent/commit/13531b8fd2ce09c5fbe0f0c588f507e6ea8791ef

### CODE REVIEW

**Review by matejcik — APPROVED** [review]
lgtm on the code side, but pinging @andrewkozlik for any cryptographic implications

**Comment by prusnak** [comment]
I changed the target branch to the newly created `ecdh-pubkey` which now has the same head as master.

Once Andrew says this is OK, I'll merge this there, finish the legacy implementation (missing from this PR) and merge into master.

**Comment by romanz** [comment]
Pushed 538ea97ca (adding legacy implementation).

**Review by andrewkozlik — APPROVED** [review]
LGTM

**Comment by romanz** [comment]
Many thanks!

**Comment by prusnak** [comment]
Merged to master, will be released next month - 14th of April

**Pull request merged**
