### PR TITLE
fix(legacy,core): use sat/vB only for segwit and sat/B otherwise

### PR DESCRIPTION
**Pull request by prusnak**
Follow-up to https://github.com/trezor/trezor-firmware/pull/2249

### CODE REVIEW

**Comment by matejcik** [comment]
is it intentional that this is for _segwit-enabled_ coins (and not for segwit transactions, i.e., Bitcoin legacy transaction will still show sat/vB) ?

**Comment by prusnak** [comment]
> is it intentional that this is for _segwit-enabled_ coins

Yes. For non-segwit transactions B = vB.

**Comment by matejcik** [comment]
@marnova can you please take over? review the changes, regenerate fixtures etc.

**Comment by marnova** [comment]
@matejcik ok

**Review by matejcik — APPROVED** [review]
utACK, didn't review every UI change but they look right

**Pull request merged**
