### PR TITLE
Adds TEO coin networks , icon to Trezor.

### PR DESCRIPTION
**Pull request by trustfarm-dev**
Adds TEO coin networks , icon to Trezor.

### CODE REVIEW

**Comment by trustfarm-dev** [comment]
@prusnak  , 

Travis has problems, could you check this?

```
"pyflakes" failed during execution due to "maximum recursion depth exceeded"
Run flake8 with greater verbosity to see more details
Makefile:17: recipe for target 'pystyle_check' failed
make: *** [pystyle_check] Error 1
The command "pipenv run make style_check" exited with 2.
```

**Comment by prusnak** [comment]
1) Keep the list sorted according to `chain_id`.
2) I don't see TEO added to https://github.com/satoshilabs/slips/blob/master/slip-0044.md - where does the 640 value come from?

**Comment by trustfarm-dev** [comment]
Ok I changed comment on slip44,
If it is confirmed then I will modify and push again.
Thanks

**Comment by prusnak** [comment]
slip44 PR merged, please update this PR

**Comment by trustfarm-dev** [comment]
@prusnak  CI has failed with above [link](https://github.com/trezor/trezor-firmware/pull/163#issuecomment-494321307)

**Comment by trustfarm-dev** [comment]
icon file is missing,
i will try again.

**Comment by trustfarm-dev** [comment]
@prusnak  I've found , networks.json has missing in [goerlit-testnet support](https://github.com/trezor/trezor-firmware/pull/137/commits/2112f402d72648bc48d977ca27956c16ca45966f)
let me try it.

**Comment by trustfarm-dev** [comment]
@prusnak  I've modified several, but problem is above "pyflakes" , why shown.

**Comment by prusnak** [comment]
Will do

**Comment by Max-Casanova** [comment]
http://skrinshoter.ru/s/230519/n3HmeM3z

send error

**Comment by prusnak** [comment]
@Max-Casanova wait for the firmware update

**Comment by Max-Casanova** [comment]
@prusnak Ок

**Comment by Max-Casanova** [comment]
@prusnak Hello once again. When an updating with a solution of the problem of TEO already there is?

**Comment by Max-Casanova** [comment]
@prusnak  Still work on a wallet?

**Pull request merged**
