### PR TITLE
Added Bitcore insight explorers to crown.json. Changed png.

### PR DESCRIPTION
**Pull request by ashotkhachatryan**
Added Bitcore insight explorers for Crown and updated crown.png file.

### CODE REVIEW

**Comment by prusnak** [comment]
Fix build:

```
ERROR invalid definition for Crown
make sure URLs don't end with '/'
make sure URLs don't end with '/'
make sure URLs don't end with '/'
```

**Comment by prusnak** [comment]
Also there is no API running on `https://insight-01.crown.tech/insight/api`

**Comment by ashotkhachatryan** [comment]
Build is fixed.

The root URL for the API is:
https://insight-01.crown.tech/insight-api-crown
For example you want blocks, it's:
https://insight-01.crown.tech/insight-api-crown/blocks

**Comment by prusnak** [comment]
Change the root URL for the APIs to be `/api`
Afterwards remove the `/insight` from the URLs and submit again

**Comment by ashotkhachatryan** [comment]
The URL is changed can you take a look please?

**Pull request merged**
