### PR TITLE
core/webauthn: Update attestation certificate to comply with WebAuthn

### PR DESCRIPTION
**Pull request by andrewkozlik**

### CODE REVIEW

**Comment by prusnak** [comment]
Shall we also change the legacy? 

https://github.com/trezor/trezor-firmware/blob/e6d884b145d0fb6201c0ae76c552547028793df9/legacy/firmware/u2f/u2f_keys.h

File is generated via https://github.com/trezor/trezor-firmware/blob/e6d884b145d0fb6201c0ae76c552547028793df9/legacy/firmware/u2f/genkeys.sh

**Comment by andrewkozlik** [comment]
> Shall we also change the legacy?

The certificate requirements only apply to the "packed" attestation statement format in FIDO2. I haven't found any similar requirements for U2F attestation certificates. So I think we don't have to apply this to legacy. My plan was to do this in core only for now, see if users run into any problems, and if not, then we can think about changing legacy too, although I don't see any strong motivation.

> File is generated via https://github.com/trezor/trezor-firmware/blob/master/legacy/firmware/u2f/genkeys.sh

I will add a generating script to core/tools.

**Comment by onvej-sl** [comment]
Link to the issue https://github.com/trezor/trezor-firmware/issues/927.
<hr>

I would expect the root certificate to be included in `x5c`.

**Comment by prusnak** [comment]
ACK for not changing the legacy

**Comment by andrewkozlik** [comment]
> I would expect the root certificate to be included in `x5c`.

Well the root is a trust anchor, which is generally not considered a part of the certificate chain. Furthermore, it looks like the webauthn spec considers the tail of the chain to be optional. Indeed, my YubiKey returns only the attestation certificate in the x5c field. So unless we happen to encounter a relying party which requires the root to be included, it seems more reasonable not to.

**Comment by onvej-sl** [comment]
> > I would expect the root certificate to be included in `x5c`.
> 
> Well the root is a trust anchor, which is generally not considered a part of the certificate chain. Furthermore, it looks like the webauthn spec considers the tail of the chain to be optional. Indeed, my YubiKey returns only the attestation certificate in the x5c field. So unless we happen to encounter a relying party which requires the root to be included, it seems more reasonable not to.

My concern was how the RP gets the root certificate? The answer is, I guess, it downloads it from `core/tools/codegen/fido/ca_cert.pem`?

**Comment by andrewkozlik** [comment]
> My concern was how the RP gets the root certificate? The answer is, I guess, it downloads it from `core/tools/codegen/fido/ca_cert.pem`?

Yes.

**Comment by onvej-sl** [comment]
This test is still failing: https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/500481094

**Comment by andrewkozlik** [comment]
> This test is still failing: https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/500481094

It will work once rebased over master.

**Pull request merged**
